import { books } from "@bible-visualizer/bible-data";

/**
 * Maps source-format book codes (USFM 3-letter, legacy WEB codes, OSIS book IDs,
 * Swete LXX codes, and full English names) to our internal `book.code` values
 * seeded in the DB.
 *
 * Sources we handle:
 *   - ebible.org VPL files use mostly USFM codes, with legacy WEB aliases:
 *     MAR=MRK, JOH=JHN, JAM=JAS, PHI=PHP, SOL=SNG, JOE=JOL, NAH=NAM,
 *     EZE=EZK, DNG (Greek Daniel) treated as DAN.
 *   - BSB uses full English names; "Psalm" (singular) instead of "Psalms".
 *   - openscriptures/morphhb (WLC) uses OSIS book IDs: Gen, Exod, Lev, Num, Deut,
 *     Josh, Judg, Ruth, 1Sam, 2Sam, 1Kgs, 2Kgs, 1Chr, 2Chr, Ezra, Neh, Esth, Job,
 *     Ps, Prov, Eccl, Song, Isa, Jer, Lam, Ezek, Dan, Hos, Joel, Amos, Obad, Jonah,
 *     Mic, Nah, Hab, Zeph, Hag, Zech, Mal.
 *   - eliranwong/LXX-Swete-1930 uses 3-letter codes: Gen, Exo, Lev, Num, Deu, Jos,
 *     Jdg, Rut, 1Sa, 2Sa, 1Ki, 2Ki, 1Ch, 2Ch, Ezr, Neh, Est, Job, Pro, Ecc, Sol,
 *     Psa, Isa, Jer, Lam, Eze, Dan, Hos, Joe, Amo, Oba, Jon, Mic, Nah, Hab, Zep,
 *     Hag, Zec, Mal, Tob, Jdt, Wis, Sir, Bar, 1Ma, 2Ma. Swete extras outside the
 *     Catholic 73-book canon (Bel, Sus, Epj, 3Ma, 4Ma, 1En, Ode, Pss, Sip, Sut,
 *     Bet, Dat, Tbs) are skipped.
 *
 * Books outside our seeded canon are explicitly skipped. Additions to
 * Daniel/Esther/Baruch (SUS, BEL, EPJ, ESG, DNG) are normalized onto their
 * parent book where possible; verse-level remapping is left for a follow-up pass.
 */

export const KNOWN_BOOK_CODES: ReadonlySet<string> = new Set(books.map((b) => b.id));

const RAW_TO_INTERNAL: Readonly<Record<string, string>> = {
  GEN: "gen",
  EXO: "exo",
  LEV: "lev",
  NUM: "num",
  DEU: "deu",
  JOS: "jos",
  JDG: "jdg",
  RUT: "rut",
  "1SA": "1sa",
  "2SA": "2sa",
  "1KI": "1ki",
  "2KI": "2ki",
  "1CH": "1ch",
  "2CH": "2ch",
  EZR: "ezr",
  NEH: "neh",
  TOB: "tob",
  JDT: "jdt",
  EST: "est",
  ESG: "est",
  "1MA": "1ma",
  "2MA": "2ma",
  JOB: "job",
  PSA: "psa",
  PRO: "pro",
  ECC: "ecc",
  SNG: "sng",
  SOL: "sng",
  SOS: "sng",
  WIS: "wis",
  SIR: "sir",
  ECS: "sir",
  ISA: "isa",
  JER: "jer",
  LAM: "lam",
  BAR: "bar",
  EZK: "ezk",
  EZE: "ezk",
  DAN: "dan",
  DNG: "dan",
  HOS: "hos",
  JOL: "jol",
  JOE: "jol",
  AMO: "amo",
  OBA: "oba",
  JON: "jon",
  MIC: "mic",
  NAM: "nam",
  NAH: "nam",
  HAB: "hab",
  ZEP: "zep",
  HAG: "hag",
  ZEC: "zec",
  MAL: "mal",
  MAT: "mat",
  MRK: "mrk",
  MAR: "mrk",
  LUK: "luk",
  JHN: "jhn",
  JOH: "jhn",
  ACT: "act",
  ROM: "rom",
  "1CO": "1co",
  "2CO": "2co",
  GAL: "gal",
  EPH: "eph",
  PHP: "php",
  PHI: "php",
  COL: "col",
  "1TH": "1th",
  "2TH": "2th",
  "1TI": "1ti",
  "2TI": "2ti",
  TIT: "tit",
  PHM: "phm",
  HEB: "heb",
  JAS: "jas",
  JAM: "jas",
  "1PE": "1pe",
  "2PE": "2pe",
  "1JN": "1jn",
  "1JO": "1jn",
  "2JN": "2jn",
  "2JO": "2jn",
  "3JN": "3jn",
  "3JO": "3jn",
  JUD: "jud",
  REV: "rev",
  EXOD: "exo",
  DEUT: "deu",
  JOSH: "jos",
  JUDG: "jdg",
  RUTH: "rut",
  "1SAM": "1sa",
  "2SAM": "2sa",
  "1KGS": "1ki",
  "2KGS": "2ki",
  "1CHR": "1ch",
  "2CHR": "2ch",
  EZRA: "ezr",
  ESTH: "est",
  PS: "psa",
  PROV: "pro",
  ECCL: "ecc",
  SONG: "sng",
  EZEK: "ezk",
  JOEL: "jol",
  AMOS: "amo",
  OBAD: "oba",
  JONAH: "jon",
  ZEPH: "zep",
  ZECH: "zec",
};

const FULL_NAME_TO_INTERNAL: Readonly<Record<string, string>> = {
  Genesis: "gen",
  Exodus: "exo",
  Leviticus: "lev",
  Numbers: "num",
  Deuteronomy: "deu",
  Joshua: "jos",
  Judges: "jdg",
  Ruth: "rut",
  "1 Samuel": "1sa",
  "2 Samuel": "2sa",
  "1 Kings": "1ki",
  "2 Kings": "2ki",
  "1 Chronicles": "1ch",
  "2 Chronicles": "2ch",
  Ezra: "ezr",
  Nehemiah: "neh",
  Tobit: "tob",
  Judith: "jdt",
  Esther: "est",
  "1 Maccabees": "1ma",
  "2 Maccabees": "2ma",
  Job: "job",
  Psalm: "psa",
  Psalms: "psa",
  Proverbs: "pro",
  Ecclesiastes: "ecc",
  "Song of Solomon": "sng",
  "Song of Songs": "sng",
  "Wisdom of Solomon": "wis",
  Wisdom: "wis",
  Sirach: "sir",
  Ecclesiasticus: "sir",
  Isaiah: "isa",
  Jeremiah: "jer",
  Lamentations: "lam",
  Baruch: "bar",
  Ezekiel: "ezk",
  Daniel: "dan",
  Hosea: "hos",
  Joel: "jol",
  Amos: "amo",
  Obadiah: "oba",
  Jonah: "jon",
  Micah: "mic",
  Nahum: "nam",
  Habakkuk: "hab",
  Zephaniah: "zep",
  Haggai: "hag",
  Zechariah: "zec",
  Malachi: "mal",
  Matthew: "mat",
  Mark: "mrk",
  Luke: "luk",
  John: "jhn",
  Acts: "act",
  Romans: "rom",
  "1 Corinthians": "1co",
  "2 Corinthians": "2co",
  Galatians: "gal",
  Ephesians: "eph",
  Philippians: "php",
  Colossians: "col",
  "1 Thessalonians": "1th",
  "2 Thessalonians": "2th",
  "1 Timothy": "1ti",
  "2 Timothy": "2ti",
  Titus: "tit",
  Philemon: "phm",
  Hebrews: "heb",
  James: "jas",
  "1 Peter": "1pe",
  "2 Peter": "2pe",
  "1 John": "1jn",
  "2 John": "2jn",
  "3 John": "3jn",
  Jude: "jud",
  Revelation: "rev",
};

/**
 * Codes for books that exist in some sources (Eastern Orthodox additions, alt
 * recensions) but are not in our seeded Catholic 73-book canon. Skipped silently.
 */
const SKIP_CODES: ReadonlySet<string> = new Set([
  "1ES",
  "2ES",
  "3ES",
  "4ES",
  "PRM",
  "MAN",
  "3MA",
  "4MA",
  "ODE",
  "PSS",
  "PSX",
  "LAO",
  "BEL",
  "SUS",
  "EPJ",
  "1EN",
  "SIP",
  "SUT",
  "BET",
  "DAT",
  "TBS",
]);

export function resolveUsfmCode(rawCode: string): string | "skip" | "unknown" {
  const upper = rawCode.toUpperCase();
  if (SKIP_CODES.has(upper)) return "skip";
  const internal = RAW_TO_INTERNAL[upper];
  if (internal) return internal;
  return "unknown";
}

export function resolveBookName(rawName: string): string | "unknown" {
  const trimmed = rawName.trim();
  const internal = FULL_NAME_TO_INTERNAL[trimmed];
  if (internal) return internal;
  return "unknown";
}
