import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import { promises as fs } from "node:fs";
import type { CollectedTranslation } from "./lib/types";
import { collectWeb } from "./sources/web";
import { collectBsb } from "./sources/bsb";
import { collectKjv } from "./sources/kjv";
import { collectBrenton } from "./sources/brenton";
import { collectSblgnt } from "./sources/sblgnt";
import { collectWlc } from "./sources/wlc";
import { collectLxx } from "./sources/lxx";

/*
 * Generates the static verse corpus consumed by the web app at build time,
 * with NO database involved. Reuses the same per-source collectors as the DB
 * ingest path, so every parser quirk (OSIS, Swete CSV, VPL) is shared.
 *
 * Output layout (under packages/bible-data/data/verses/):
 *   <TRANSLATION>/<bookCode>.json   ->  { "<chapter>": [[verse, "text"], ...] }
 *   manifest.json                   ->  per-translation per-book chapter/verse counts
 */

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const BIBLE_DATA_ROOT = resolve(PACKAGE_ROOT, "../../packages/bible-data");
const OUTPUT_DIR = join(BIBLE_DATA_ROOT, "data/verses");
// Generated typed manifest module, imported synchronously by the access layer
// (kept inside src/ so it stays within the package tsconfig rootDir).
const MANIFEST_MODULE_PATH = join(BIBLE_DATA_ROOT, "src/verse-manifest.ts");

type Source = "web" | "bsb" | "kjv" | "brenton" | "sblgnt" | "wlc" | "lxx";

const COLLECTORS: Record<Source, (root: string) => Promise<CollectedTranslation>> = {
  web: collectWeb,
  bsb: collectBsb,
  kjv: collectKjv,
  brenton: collectBrenton,
  sblgnt: collectSblgnt,
  wlc: collectWlc,
  lxx: collectLxx,
};

const SOURCE_ORDER: Source[] = ["web", "bsb", "kjv", "brenton", "sblgnt", "wlc", "lxx"];

type ChapterMap = Map<number, Array<[number, string]>>;

interface BookManifestEntry {
  chapters: number;
  verses: number;
}

interface TranslationManifestEntry {
  code: string;
  books: Record<string, BookManifestEntry>;
  totalVerses: number;
}

interface Manifest {
  translations: Record<string, TranslationManifestEntry>;
}

async function writeTranslation(
  collected: CollectedTranslation,
): Promise<TranslationManifestEntry> {
  const { translationCode, verses } = collected;

  // Group verses: book -> chapter -> [verse, text][]
  const byBook = new Map<string, ChapterMap>();
  for (const v of verses) {
    let chapters = byBook.get(v.bookCode);
    if (!chapters) {
      chapters = new Map();
      byBook.set(v.bookCode, chapters);
    }
    let chapterVerses = chapters.get(v.chapter);
    if (!chapterVerses) {
      chapterVerses = [];
      chapters.set(v.chapter, chapterVerses);
    }
    chapterVerses.push([v.verse, v.text]);
  }

  const translationDir = join(OUTPUT_DIR, translationCode);
  await fs.mkdir(translationDir, { recursive: true });

  const books: Record<string, BookManifestEntry> = {};
  let totalVerses = 0;

  for (const [bookCode, chapters] of byBook) {
    const sortedChapterNums = [...chapters.keys()].sort((a, b) => a - b);
    const fileData: Record<string, Array<[number, string]>> = {};
    let bookVerseCount = 0;

    for (const chapterNum of sortedChapterNums) {
      const chapterVerses = chapters.get(chapterNum)!;
      chapterVerses.sort((a, b) => a[0] - b[0]);
      fileData[String(chapterNum)] = chapterVerses;
      bookVerseCount += chapterVerses.length;
    }

    await fs.writeFile(join(translationDir, `${bookCode}.json`), JSON.stringify(fileData));

    books[bookCode] = {
      chapters: sortedChapterNums[sortedChapterNums.length - 1] ?? 0,
      verses: bookVerseCount,
    };
    totalVerses += bookVerseCount;
  }

  console.log(
    `[${translationCode}] ${totalVerses.toLocaleString()} verses across ${
      Object.keys(books).length
    } books`,
  );

  return { code: translationCode, books, totalVerses };
}

/**
 * Emit the manifest as a typed TS module inside src/. Importing this (rather
 * than the JSON) keeps everything within the package tsconfig rootDir and gives
 * the access layer fully-typed, synchronous metadata. The per-book verse JSON
 * is loaded separately via a variable dynamic import the bundler code-splits.
 */
async function writeManifestModule(manifest: Manifest): Promise<void> {
  const body = `// AUTO-GENERATED by tools/ingest/src/generate-verses.ts — do not edit by hand.

export interface VerseBookStat {
  chapters: number;
  verses: number;
}

export interface VerseTranslationStat {
  code: string;
  books: Record<string, VerseBookStat>;
  totalVerses: number;
}

export interface VerseManifest {
  translations: Record<string, VerseTranslationStat>;
}

export const verseManifest: VerseManifest = ${JSON.stringify(manifest, null, 2)};
`;

  await fs.writeFile(MANIFEST_MODULE_PATH, body);
  const count = Object.keys(manifest.translations).length;
  console.log(`Wrote typed manifest module (${count} translation(s)) to ${MANIFEST_MODULE_PATH}`);
}

async function main(): Promise<void> {
  const arg = (process.argv[2] ?? "all").toLowerCase();
  const sources: Source[] =
    arg === "all"
      ? SOURCE_ORDER
      : arg in COLLECTORS
        ? [arg as Source]
        : (() => {
            console.error(
              `Unknown source: "${arg}". Use one of: ${SOURCE_ORDER.join(", ")}, all.`,
            );
            process.exit(1);
          })();

  await fs.mkdir(OUTPUT_DIR, { recursive: true });

  // Read any existing manifest so a single-source regen doesn't drop the others.
  const manifestPath = join(OUTPUT_DIR, "manifest.json");
  let manifest: Manifest = { translations: {} };
  try {
    manifest = JSON.parse(await fs.readFile(manifestPath, "utf8")) as Manifest;
  } catch {
    /* first run */
  }

  for (const source of sources) {
    console.log(`-> collecting ${source}...`);
    const collected = await COLLECTORS[source](PACKAGE_ROOT);
    const entry = await writeTranslation(collected);
    manifest.translations[entry.code] = entry;
  }

  await fs.writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  console.log(`\nWrote manifest with ${Object.keys(manifest.translations).length} translation(s) to ${manifestPath}`);

  await writeManifestModule(manifest);
}

main().catch((error) => {
  console.error("Verse generation failed:", error);
  process.exit(1);
});
