import type { Book, CanonicalTradition } from "./types";

const ALL_CANONS: CanonicalTradition[] = [
  "protestant",
  "catholic",
  "eastern-orthodox",
  "ethiopian-orthodox",
];

const DEUTEROCANONICAL_CANONS: CanonicalTradition[] = [
  "catholic",
  "eastern-orthodox",
  "ethiopian-orthodox",
];

export const books: Book[] = [
  {
    id: "gen",
    name: "Genesis",
    abbreviation: "Gen",
    testament: "Old",
    order: 1,
    chapters: 50,
    genre: "law",
    authorTraditional: "Moses",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Genesis 1:1", "Genesis 50:26"],
    confidenceLevel: "stated",
    traditionTags: ["Pentateuch", "Torah"],
  },
  {
    id: "exo",
    name: "Exodus",
    abbreviation: "Ex",
    testament: "Old",
    order: 2,
    chapters: 40,
    genre: "law",
    authorTraditional: "Moses",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Exodus 1:1", "Exodus 40:38"],
    confidenceLevel: "stated",
    traditionTags: ["Pentateuch", "Torah"],
  },
  {
    id: "lev",
    name: "Leviticus",
    abbreviation: "Lev",
    testament: "Old",
    order: 3,
    chapters: 27,
    genre: "law",
    authorTraditional: "Moses",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Leviticus 1:1", "Leviticus 27:34"],
    confidenceLevel: "stated",
    traditionTags: ["Pentateuch", "Torah"],
  },
  {
    id: "num",
    name: "Numbers",
    abbreviation: "Num",
    testament: "Old",
    order: 4,
    chapters: 36,
    genre: "law",
    authorTraditional: "Moses",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Numbers 1:1", "Numbers 36:13"],
    confidenceLevel: "stated",
    traditionTags: ["Pentateuch", "Torah"],
  },
  {
    id: "deu",
    name: "Deuteronomy",
    abbreviation: "Deut",
    testament: "Old",
    order: 5,
    chapters: 34,
    genre: "law",
    authorTraditional: "Moses",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Deuteronomy 1:1", "Deuteronomy 34:12"],
    confidenceLevel: "stated",
    traditionTags: ["Pentateuch", "Torah"],
  },
  {
    id: "jos",
    name: "Joshua",
    abbreviation: "Josh",
    testament: "Old",
    order: 6,
    chapters: 24,
    genre: "history",
    authorTraditional: "Joshua",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Joshua 1:1", "Joshua 24:33"],
    confidenceLevel: "stated",
  },
  {
    id: "jdg",
    name: "Judges",
    abbreviation: "Judg",
    testament: "Old",
    order: 7,
    chapters: 21,
    genre: "history",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Judges 1:1", "Judges 21:25"],
    confidenceLevel: "stated",
  },
  {
    id: "rut",
    name: "Ruth",
    abbreviation: "Ruth",
    testament: "Old",
    order: 8,
    chapters: 4,
    genre: "history",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Ruth 1:1", "Ruth 4:22"],
    confidenceLevel: "stated",
  },
  {
    id: "1sa",
    name: "1 Samuel",
    abbreviation: "1 Sam",
    testament: "Old",
    order: 9,
    chapters: 31,
    genre: "history",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["1 Samuel 1:1", "1 Samuel 31:13"],
    confidenceLevel: "stated",
  },
  {
    id: "2sa",
    name: "2 Samuel",
    abbreviation: "2 Sam",
    testament: "Old",
    order: 10,
    chapters: 24,
    genre: "history",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["2 Samuel 1:1", "2 Samuel 24:25"],
    confidenceLevel: "stated",
  },
  {
    id: "1ki",
    name: "1 Kings",
    abbreviation: "1 Kgs",
    testament: "Old",
    order: 11,
    chapters: 22,
    genre: "history",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["1 Kings 1:1", "1 Kings 22:53"],
    confidenceLevel: "stated",
  },
  {
    id: "2ki",
    name: "2 Kings",
    abbreviation: "2 Kgs",
    testament: "Old",
    order: 12,
    chapters: 25,
    genre: "history",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["2 Kings 1:1", "2 Kings 25:30"],
    confidenceLevel: "stated",
  },
  {
    id: "1ch",
    name: "1 Chronicles",
    abbreviation: "1 Chr",
    testament: "Old",
    order: 13,
    chapters: 29,
    genre: "history",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["1 Chronicles 1:1", "1 Chronicles 29:30"],
    confidenceLevel: "stated",
  },
  {
    id: "2ch",
    name: "2 Chronicles",
    abbreviation: "2 Chr",
    testament: "Old",
    order: 14,
    chapters: 36,
    genre: "history",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["2 Chronicles 1:1", "2 Chronicles 36:23"],
    confidenceLevel: "stated",
  },
  {
    id: "ezr",
    name: "Ezra",
    abbreviation: "Ezra",
    testament: "Old",
    order: 15,
    chapters: 10,
    genre: "history",
    authorTraditional: "Ezra",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Ezra 1:1", "Ezra 10:44"],
    confidenceLevel: "stated",
    notes: "Ezra 4:8–6:18 and 7:12–26 are written in Aramaic.",
  },
  {
    id: "neh",
    name: "Nehemiah",
    abbreviation: "Neh",
    testament: "Old",
    order: 16,
    chapters: 13,
    genre: "history",
    authorTraditional: "Nehemiah",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Nehemiah 1:1", "Nehemiah 13:31"],
    confidenceLevel: "stated",
  },
  {
    id: "tob",
    name: "Tobit",
    abbreviation: "Tob",
    testament: "Old",
    order: 17,
    chapters: 14,
    genre: "history",
    canons: DEUTEROCANONICAL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Tobit 1:1", "Tobit 14:15"],
    confidenceLevel: "stated",
    traditionTags: ["Septuagint", "Deuterocanonical"],
    notes:
      "Aramaic and Hebrew fragments found at Qumran indicate a Semitic original; the canonical received form is Greek.",
  },
  {
    id: "jdt",
    name: "Judith",
    abbreviation: "Jdt",
    testament: "Old",
    order: 18,
    chapters: 16,
    genre: "history",
    canons: DEUTEROCANONICAL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Judith 1:1", "Judith 16:25"],
    confidenceLevel: "stated",
    traditionTags: ["Septuagint", "Deuterocanonical"],
    notes:
      "Likely composed in Hebrew; the Hebrew original is lost. Received via the Septuagint.",
  },
  {
    id: "est",
    name: "Esther",
    abbreviation: "Est",
    testament: "Old",
    order: 19,
    chapters: 10,
    genre: "history",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Esther 1:1", "Esther 10:3"],
    confidenceLevel: "stated",
    notes:
      "Catholic and Orthodox canons include the Greek Additions to Esther (107 additional verses) integrated into the text.",
  },
  {
    id: "1ma",
    name: "1 Maccabees",
    abbreviation: "1 Macc",
    testament: "Old",
    order: 20,
    chapters: 16,
    genre: "history",
    canons: DEUTEROCANONICAL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["1 Maccabees 1:1", "1 Maccabees 16:24"],
    confidenceLevel: "stated",
    traditionTags: ["Septuagint", "Deuterocanonical"],
    notes:
      "Originally composed in Hebrew (per Origen and Jerome); the Hebrew original is lost. Surviving Greek form via the Septuagint.",
  },
  {
    id: "2ma",
    name: "2 Maccabees",
    abbreviation: "2 Macc",
    testament: "Old",
    order: 21,
    chapters: 15,
    genre: "history",
    canons: DEUTEROCANONICAL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["2 Maccabees 1:1", "2 Maccabees 15:39"],
    confidenceLevel: "stated",
    traditionTags: ["Septuagint", "Deuterocanonical"],
    notes: "Composed originally in Greek as an epitome of Jason of Cyrene's five-volume work.",
  },
  {
    id: "job",
    name: "Job",
    abbreviation: "Job",
    testament: "Old",
    order: 22,
    chapters: 42,
    genre: "wisdom",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Job 1:1", "Job 42:17"],
    confidenceLevel: "stated",
  },
  {
    id: "psa",
    name: "Psalms",
    abbreviation: "Ps",
    testament: "Old",
    order: 23,
    chapters: 150,
    genre: "wisdom",
    authorTraditional: "David and others",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Psalm 1:1", "Psalm 150:6"],
    confidenceLevel: "stated",
    notes:
      "Eastern Orthodox and Ethiopian Orthodox canons additionally include Psalm 151 (not modeled here).",
  },
  {
    id: "pro",
    name: "Proverbs",
    abbreviation: "Prov",
    testament: "Old",
    order: 24,
    chapters: 31,
    genre: "wisdom",
    authorTraditional: "Solomon",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Proverbs 1:1", "Proverbs 31:31"],
    confidenceLevel: "stated",
  },
  {
    id: "ecc",
    name: "Ecclesiastes",
    abbreviation: "Eccl",
    testament: "Old",
    order: 25,
    chapters: 12,
    genre: "wisdom",
    authorTraditional: "Solomon",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Ecclesiastes 1:1", "Ecclesiastes 12:14"],
    confidenceLevel: "stated",
  },
  {
    id: "sng",
    name: "Song of Solomon",
    abbreviation: "Song",
    testament: "Old",
    order: 26,
    chapters: 8,
    genre: "wisdom",
    authorTraditional: "Solomon",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Song of Solomon 1:1", "Song of Solomon 8:14"],
    confidenceLevel: "stated",
  },
  {
    id: "wis",
    name: "Wisdom of Solomon",
    abbreviation: "Wis",
    testament: "Old",
    order: 27,
    chapters: 19,
    genre: "wisdom",
    authorTraditional: "Solomon (traditional)",
    canons: DEUTEROCANONICAL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Wisdom 1:1", "Wisdom 19:22"],
    confidenceLevel: "stated",
    traditionTags: ["Septuagint", "Deuterocanonical"],
    notes:
      "Composed in Greek by an Alexandrian Jew, traditionally pseudepigraphically attributed to Solomon.",
  },
  {
    id: "sir",
    name: "Sirach",
    abbreviation: "Sir",
    testament: "Old",
    order: 28,
    chapters: 51,
    genre: "wisdom",
    authorTraditional: "Yeshua ben Sira",
    canons: DEUTEROCANONICAL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Sirach 1:1", "Sirach 51:30"],
    confidenceLevel: "stated",
    traditionTags: ["Septuagint", "Deuterocanonical", "Ecclesiasticus"],
    notes:
      "Composed in Hebrew (~180 BCE) by Yeshua ben Sira; translated into Greek by his grandson per the prologue. About two-thirds of the Hebrew text survives in Cairo Geniza and Qumran fragments.",
  },
  {
    id: "isa",
    name: "Isaiah",
    abbreviation: "Isa",
    testament: "Old",
    order: 29,
    chapters: 66,
    genre: "prophecy",
    authorTraditional: "Isaiah",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Isaiah 1:1", "Isaiah 66:24"],
    confidenceLevel: "stated",
  },
  {
    id: "jer",
    name: "Jeremiah",
    abbreviation: "Jer",
    testament: "Old",
    order: 30,
    chapters: 52,
    genre: "prophecy",
    authorTraditional: "Jeremiah",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Jeremiah 1:1", "Jeremiah 52:34"],
    confidenceLevel: "stated",
    notes: "Jeremiah 10:11 is in Aramaic.",
  },
  {
    id: "lam",
    name: "Lamentations",
    abbreviation: "Lam",
    testament: "Old",
    order: 31,
    chapters: 5,
    genre: "prophecy",
    authorTraditional: "Jeremiah",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Lamentations 1:1", "Lamentations 5:22"],
    confidenceLevel: "stated",
  },
  {
    id: "bar",
    name: "Baruch",
    abbreviation: "Bar",
    testament: "Old",
    order: 32,
    chapters: 6,
    genre: "prophecy",
    authorTraditional: "Baruch ben Neriah",
    canons: DEUTEROCANONICAL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Baruch 1:1", "Baruch 6:73"],
    confidenceLevel: "stated",
    traditionTags: ["Septuagint", "Deuterocanonical"],
    notes:
      "Chapter 6 is the Letter of Jeremiah, which Eastern Orthodox tradition treats as a separate book. Chapters 1–5 likely had a Hebrew original; chapter 6 was composed in Greek.",
  },
  {
    id: "ezk",
    name: "Ezekiel",
    abbreviation: "Ezek",
    testament: "Old",
    order: 33,
    chapters: 48,
    genre: "prophecy",
    authorTraditional: "Ezekiel",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Ezekiel 1:1", "Ezekiel 48:35"],
    confidenceLevel: "stated",
  },
  {
    id: "dan",
    name: "Daniel",
    abbreviation: "Dan",
    testament: "Old",
    order: 34,
    chapters: 12,
    genre: "apocalyptic",
    authorTraditional: "Daniel",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Daniel 1:1", "Daniel 12:13"],
    confidenceLevel: "stated",
    notes:
      "Daniel 2:4b–7:28 is in Aramaic. Catholic and Orthodox canons additionally include the Prayer of Azariah, Susanna, and Bel and the Dragon (Greek additions to Daniel).",
  },
  {
    id: "hos",
    name: "Hosea",
    abbreviation: "Hos",
    testament: "Old",
    order: 35,
    chapters: 14,
    genre: "prophecy",
    authorTraditional: "Hosea",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Hosea 1:1", "Hosea 14:9"],
    confidenceLevel: "stated",
  },
  {
    id: "jol",
    name: "Joel",
    abbreviation: "Joel",
    testament: "Old",
    order: 36,
    chapters: 3,
    genre: "prophecy",
    authorTraditional: "Joel",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Joel 1:1", "Joel 3:21"],
    confidenceLevel: "stated",
  },
  {
    id: "amo",
    name: "Amos",
    abbreviation: "Amos",
    testament: "Old",
    order: 37,
    chapters: 9,
    genre: "prophecy",
    authorTraditional: "Amos",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Amos 1:1", "Amos 9:15"],
    confidenceLevel: "stated",
  },
  {
    id: "oba",
    name: "Obadiah",
    abbreviation: "Obad",
    testament: "Old",
    order: 38,
    chapters: 1,
    genre: "prophecy",
    authorTraditional: "Obadiah",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Obadiah 1:1", "Obadiah 1:21"],
    confidenceLevel: "stated",
  },
  {
    id: "jon",
    name: "Jonah",
    abbreviation: "Jonah",
    testament: "Old",
    order: 39,
    chapters: 4,
    genre: "prophecy",
    authorTraditional: "Jonah",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Jonah 1:1", "Jonah 4:11"],
    confidenceLevel: "stated",
  },
  {
    id: "mic",
    name: "Micah",
    abbreviation: "Mic",
    testament: "Old",
    order: 40,
    chapters: 7,
    genre: "prophecy",
    authorTraditional: "Micah",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Micah 1:1", "Micah 7:20"],
    confidenceLevel: "stated",
  },
  {
    id: "nam",
    name: "Nahum",
    abbreviation: "Nah",
    testament: "Old",
    order: 41,
    chapters: 3,
    genre: "prophecy",
    authorTraditional: "Nahum",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Nahum 1:1", "Nahum 3:19"],
    confidenceLevel: "stated",
  },
  {
    id: "hab",
    name: "Habakkuk",
    abbreviation: "Hab",
    testament: "Old",
    order: 42,
    chapters: 3,
    genre: "prophecy",
    authorTraditional: "Habakkuk",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Habakkuk 1:1", "Habakkuk 3:19"],
    confidenceLevel: "stated",
  },
  {
    id: "zep",
    name: "Zephaniah",
    abbreviation: "Zeph",
    testament: "Old",
    order: 43,
    chapters: 3,
    genre: "prophecy",
    authorTraditional: "Zephaniah",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Zephaniah 1:1", "Zephaniah 3:20"],
    confidenceLevel: "stated",
  },
  {
    id: "hag",
    name: "Haggai",
    abbreviation: "Hag",
    testament: "Old",
    order: 44,
    chapters: 2,
    genre: "prophecy",
    authorTraditional: "Haggai",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Haggai 1:1", "Haggai 2:23"],
    confidenceLevel: "stated",
  },
  {
    id: "zec",
    name: "Zechariah",
    abbreviation: "Zech",
    testament: "Old",
    order: 45,
    chapters: 14,
    genre: "prophecy",
    authorTraditional: "Zechariah",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Zechariah 1:1", "Zechariah 14:21"],
    confidenceLevel: "stated",
  },
  {
    id: "mal",
    name: "Malachi",
    abbreviation: "Mal",
    testament: "Old",
    order: 46,
    chapters: 4,
    genre: "prophecy",
    authorTraditional: "Malachi",
    canons: ALL_CANONS,
    originalLanguage: "hebrew",
    scriptureReferences: ["Malachi 1:1", "Malachi 4:6"],
    confidenceLevel: "stated",
  },
  {
    id: "mat",
    name: "Matthew",
    abbreviation: "Matt",
    testament: "New",
    order: 47,
    chapters: 28,
    genre: "gospel",
    authorTraditional: "Matthew",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Matthew 1:1", "Matthew 28:20"],
    confidenceLevel: "stated",
  },
  {
    id: "mrk",
    name: "Mark",
    abbreviation: "Mark",
    testament: "New",
    order: 48,
    chapters: 16,
    genre: "gospel",
    authorTraditional: "John Mark",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Mark 1:1", "Mark 16:20"],
    confidenceLevel: "stated",
  },
  {
    id: "luk",
    name: "Luke",
    abbreviation: "Luke",
    testament: "New",
    order: 49,
    chapters: 24,
    genre: "gospel",
    authorTraditional: "Luke",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Luke 1:1", "Luke 24:53"],
    confidenceLevel: "stated",
  },
  {
    id: "jhn",
    name: "John",
    abbreviation: "John",
    testament: "New",
    order: 50,
    chapters: 21,
    genre: "gospel",
    authorTraditional: "John",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["John 1:1", "John 21:25"],
    confidenceLevel: "stated",
  },
  {
    id: "act",
    name: "Acts",
    abbreviation: "Acts",
    testament: "New",
    order: 51,
    chapters: 28,
    genre: "history",
    authorTraditional: "Luke",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Acts 1:1", "Acts 28:31"],
    confidenceLevel: "stated",
  },
  {
    id: "rom",
    name: "Romans",
    abbreviation: "Rom",
    testament: "New",
    order: 52,
    chapters: 16,
    genre: "epistle",
    authorTraditional: "Paul",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Romans 1:1", "Romans 16:27"],
    confidenceLevel: "stated",
  },
  {
    id: "1co",
    name: "1 Corinthians",
    abbreviation: "1 Cor",
    testament: "New",
    order: 53,
    chapters: 16,
    genre: "epistle",
    authorTraditional: "Paul",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["1 Corinthians 1:1", "1 Corinthians 16:24"],
    confidenceLevel: "stated",
  },
  {
    id: "2co",
    name: "2 Corinthians",
    abbreviation: "2 Cor",
    testament: "New",
    order: 54,
    chapters: 13,
    genre: "epistle",
    authorTraditional: "Paul",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["2 Corinthians 1:1", "2 Corinthians 13:14"],
    confidenceLevel: "stated",
  },
  {
    id: "gal",
    name: "Galatians",
    abbreviation: "Gal",
    testament: "New",
    order: 55,
    chapters: 6,
    genre: "epistle",
    authorTraditional: "Paul",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Galatians 1:1", "Galatians 6:18"],
    confidenceLevel: "stated",
  },
  {
    id: "eph",
    name: "Ephesians",
    abbreviation: "Eph",
    testament: "New",
    order: 56,
    chapters: 6,
    genre: "epistle",
    authorTraditional: "Paul",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Ephesians 1:1", "Ephesians 6:24"],
    confidenceLevel: "stated",
  },
  {
    id: "php",
    name: "Philippians",
    abbreviation: "Phil",
    testament: "New",
    order: 57,
    chapters: 4,
    genre: "epistle",
    authorTraditional: "Paul",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Philippians 1:1", "Philippians 4:23"],
    confidenceLevel: "stated",
  },
  {
    id: "col",
    name: "Colossians",
    abbreviation: "Col",
    testament: "New",
    order: 58,
    chapters: 4,
    genre: "epistle",
    authorTraditional: "Paul",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Colossians 1:1", "Colossians 4:18"],
    confidenceLevel: "stated",
  },
  {
    id: "1th",
    name: "1 Thessalonians",
    abbreviation: "1 Thess",
    testament: "New",
    order: 59,
    chapters: 5,
    genre: "epistle",
    authorTraditional: "Paul",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["1 Thessalonians 1:1", "1 Thessalonians 5:28"],
    confidenceLevel: "stated",
  },
  {
    id: "2th",
    name: "2 Thessalonians",
    abbreviation: "2 Thess",
    testament: "New",
    order: 60,
    chapters: 3,
    genre: "epistle",
    authorTraditional: "Paul",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["2 Thessalonians 1:1", "2 Thessalonians 3:18"],
    confidenceLevel: "stated",
  },
  {
    id: "1ti",
    name: "1 Timothy",
    abbreviation: "1 Tim",
    testament: "New",
    order: 61,
    chapters: 6,
    genre: "epistle",
    authorTraditional: "Paul",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["1 Timothy 1:1", "1 Timothy 6:21"],
    confidenceLevel: "stated",
  },
  {
    id: "2ti",
    name: "2 Timothy",
    abbreviation: "2 Tim",
    testament: "New",
    order: 62,
    chapters: 4,
    genre: "epistle",
    authorTraditional: "Paul",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["2 Timothy 1:1", "2 Timothy 4:22"],
    confidenceLevel: "stated",
  },
  {
    id: "tit",
    name: "Titus",
    abbreviation: "Titus",
    testament: "New",
    order: 63,
    chapters: 3,
    genre: "epistle",
    authorTraditional: "Paul",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Titus 1:1", "Titus 3:15"],
    confidenceLevel: "stated",
  },
  {
    id: "phm",
    name: "Philemon",
    abbreviation: "Phlm",
    testament: "New",
    order: 64,
    chapters: 1,
    genre: "epistle",
    authorTraditional: "Paul",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Philemon 1:1", "Philemon 1:25"],
    confidenceLevel: "stated",
  },
  {
    id: "heb",
    name: "Hebrews",
    abbreviation: "Heb",
    testament: "New",
    order: 65,
    chapters: 13,
    genre: "epistle",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Hebrews 1:1", "Hebrews 13:25"],
    confidenceLevel: "stated",
    notes: "Authorship is historically debated.",
  },
  {
    id: "jas",
    name: "James",
    abbreviation: "Jas",
    testament: "New",
    order: 66,
    chapters: 5,
    genre: "epistle",
    authorTraditional: "James",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["James 1:1", "James 5:20"],
    confidenceLevel: "stated",
  },
  {
    id: "1pe",
    name: "1 Peter",
    abbreviation: "1 Pet",
    testament: "New",
    order: 67,
    chapters: 5,
    genre: "epistle",
    authorTraditional: "Peter",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["1 Peter 1:1", "1 Peter 5:14"],
    confidenceLevel: "stated",
  },
  {
    id: "2pe",
    name: "2 Peter",
    abbreviation: "2 Pet",
    testament: "New",
    order: 68,
    chapters: 3,
    genre: "epistle",
    authorTraditional: "Peter",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["2 Peter 1:1", "2 Peter 3:18"],
    confidenceLevel: "stated",
  },
  {
    id: "1jn",
    name: "1 John",
    abbreviation: "1 John",
    testament: "New",
    order: 69,
    chapters: 5,
    genre: "epistle",
    authorTraditional: "John",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["1 John 1:1", "1 John 5:21"],
    confidenceLevel: "stated",
  },
  {
    id: "2jn",
    name: "2 John",
    abbreviation: "2 John",
    testament: "New",
    order: 70,
    chapters: 1,
    genre: "epistle",
    authorTraditional: "John",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["2 John 1:1", "2 John 1:13"],
    confidenceLevel: "stated",
  },
  {
    id: "3jn",
    name: "3 John",
    abbreviation: "3 John",
    testament: "New",
    order: 71,
    chapters: 1,
    genre: "epistle",
    authorTraditional: "John",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["3 John 1:1", "3 John 1:14"],
    confidenceLevel: "stated",
  },
  {
    id: "jud",
    name: "Jude",
    abbreviation: "Jude",
    testament: "New",
    order: 72,
    chapters: 1,
    genre: "epistle",
    authorTraditional: "Jude",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Jude 1:1", "Jude 1:25"],
    confidenceLevel: "stated",
  },
  {
    id: "rev",
    name: "Revelation",
    abbreviation: "Rev",
    testament: "New",
    order: 73,
    chapters: 22,
    genre: "apocalyptic",
    authorTraditional: "John",
    canons: ALL_CANONS,
    originalLanguage: "greek",
    scriptureReferences: ["Revelation 1:1", "Revelation 22:21"],
    confidenceLevel: "stated",
  },
];

export const oldTestamentBooks: Book[] = books.filter((b) => b.testament === "Old");
export const newTestamentBooks: Book[] = books.filter((b) => b.testament === "New");

export const protestantBooks: Book[] = books.filter((b) => b.canons.includes("protestant"));
export const deuterocanonicalBooks: Book[] = books.filter(
  (b) => !b.canons.includes("protestant"),
);

export const getBookById = (id: string): Book | undefined => books.find((b) => b.id === id);
export const getBookByName = (name: string): Book | undefined =>
  books.find((b) => b.name === name);
