import type { BiblicalEvent } from "./types";

export const events: BiblicalEvent[] = [
  {
    id: "creation",
    name: "Creation",
    category: "primeval",
    description:
      "The creation of the heavens and the earth in six days, climaxing in humanity made in God's image.",
    startYear: -4004,
    endYear: -4004,
    scriptureReferences: ["Genesis 1-2"],
    confidenceLevel: "traditional",
    traditionTags: ["ussher-chronology"],
    notes:
      "Date follows the traditional Masoretic young-earth chronology (Ussher-adjacent: ~4004 BC).",
  },
  {
    id: "fall",
    name: "The Fall",
    category: "primeval",
    description:
      "Adam and Eve's disobedience in Eden and exile from the garden; entry of sin and death into the world.",
    startYear: -4004,
    endYear: -4004,
    scriptureReferences: ["Genesis 3"],
    confidenceLevel: "traditional",
  },
  {
    id: "cain-and-abel",
    name: "Cain Murders Abel",
    category: "primeval",
    description:
      "The first murder: Cain kills his brother Abel out of jealousy over their offerings; Cain is exiled and marked.",
    startYear: -3875,
    endYear: -3875,
    scriptureReferences: ["Genesis 4:1-16", "Hebrews 11:4", "1 John 3:12"],
    confidenceLevel: "traditional",
  },
  {
    id: "translation-of-enoch",
    name: "Translation of Enoch",
    category: "primeval",
    description:
      "Enoch walked with God for 365 years and was no more, for God took him — taken to heaven without dying.",
    startYear: -3017,
    endYear: -3017,
    scriptureReferences: ["Genesis 5:21-24", "Hebrews 11:5", "Jude 1:14-15"],
    confidenceLevel: "traditional",
  },
  {
    id: "flood",
    name: "The Flood",
    category: "primeval",
    description:
      "Yahweh judges the antediluvian world by a year-long flood; Noah and his family preserved in the ark on Ararat. Methuselah dies the year of the flood.",
    startYear: -2348,
    endYear: -2347,
    scriptureReferences: ["Genesis 6-9", "Matthew 24:37-39", "1 Peter 3:20", "2 Peter 2:5"],
    confidenceLevel: "traditional",
    traditionTags: ["ussher-chronology"],
    placeIds: [],
  },
  {
    id: "babel",
    name: "Tower of Babel",
    category: "primeval",
    description:
      "Confusion of languages and scattering of post-flood humanity at Shinar; the origin of the nations.",
    startYear: -2242,
    endYear: -2242,
    scriptureReferences: ["Genesis 11:1-9"],
    confidenceLevel: "traditional",
    traditionTags: ["ussher-chronology"],
  },
  {
    id: "call-of-abraham",
    name: "Call of Abraham",
    category: "patriarchal",
    description:
      "Yahweh calls Abram out of Ur of the Chaldees and Haran with the threefold promise of land, descendants, and blessing to all nations.",
    startYear: -2091,
    endYear: -2091,
    scriptureReferences: ["Genesis 12:1-9", "Acts 7:2-4", "Hebrews 11:8-10"],
    confidenceLevel: "traditional",
    placeIds: ["ur-of-the-chaldees", "haran", "shechem"],
  },
  {
    id: "covenant-with-abraham",
    name: "Abrahamic Covenant",
    category: "patriarchal",
    description:
      "Yahweh formally cuts covenant with Abram (Genesis 15) and ratifies it with the sign of circumcision (Genesis 17).",
    startYear: -2081,
    endYear: -2067,
    scriptureReferences: ["Genesis 15", "Genesis 17"],
    confidenceLevel: "traditional",
  },
  {
    id: "destruction-of-sodom",
    name: "Destruction of Sodom and Gomorrah",
    category: "patriarchal",
    description:
      "Cities of the plain destroyed by fire from heaven; Lot and his daughters delivered.",
    startYear: -2067,
    endYear: -2067,
    scriptureReferences: ["Genesis 18-19", "2 Peter 2:6", "Jude 1:7"],
    confidenceLevel: "traditional",
    placeIds: ["sodom"],
  },
  {
    id: "binding-of-isaac",
    name: "Binding of Isaac (Akedah)",
    category: "patriarchal",
    description:
      "Abraham's testing on Mount Moriah; the ram caught in the thicket as substitutionary sacrifice — a foreshadowing of the cross.",
    startYear: -2042,
    endYear: -2042,
    scriptureReferences: ["Genesis 22", "Hebrews 11:17-19", "James 2:21-23"],
    confidenceLevel: "traditional",
  },
  {
    id: "death-of-sarah",
    name: "Death of Sarah / Cave of Machpelah",
    category: "patriarchal",
    description:
      "Sarah dies at 127. Abraham buys the Cave of Machpelah from Ephron the Hittite — the first piece of the Promised Land owned by the family.",
    startYear: -2030,
    endYear: -2030,
    scriptureReferences: ["Genesis 23"],
    confidenceLevel: "traditional",
    placeIds: ["hebron"],
  },
  {
    id: "birth-of-jacob-and-esau",
    name: "Birth of Jacob and Esau",
    category: "patriarchal",
    description:
      "Twin sons born to Isaac and Rebekah after twenty years of barrenness; the older shall serve the younger.",
    startYear: -2007,
    endYear: -2007,
    scriptureReferences: ["Genesis 25:19-26", "Romans 9:10-13"],
    confidenceLevel: "traditional",
  },
  {
    id: "jacobs-ladder",
    name: "Jacob's Ladder at Bethel",
    category: "patriarchal",
    description:
      "Fleeing Esau, Jacob dreams of a ladder reaching heaven with angels ascending and descending; the LORD reaffirms the Abrahamic covenant.",
    startYear: -1929,
    endYear: -1929,
    scriptureReferences: ["Genesis 28:10-22", "John 1:51"],
    confidenceLevel: "traditional",
    placeIds: ["bethel"],
  },
  {
    id: "jacob-wrestles-at-peniel",
    name: "Jacob Wrestles God at Peniel",
    category: "patriarchal",
    description:
      "On the eve of meeting Esau, Jacob wrestles a divine man until daybreak; renamed Israel — 'one who struggles with God.'",
    startYear: -1909,
    endYear: -1909,
    scriptureReferences: ["Genesis 32:22-32", "Hosea 12:3-4"],
    confidenceLevel: "traditional",
  },
  {
    id: "joseph-into-egypt",
    name: "Joseph Sold into Egypt",
    category: "patriarchal",
    description:
      "Joseph sold by his brothers; Yahweh providentially raises him to be vizier of Egypt; Jacob's family relocates to Goshen.",
    startYear: -1898,
    endYear: -1876,
    scriptureReferences: ["Genesis 37", "Genesis 39-47"],
    confidenceLevel: "traditional",
    placeIds: ["egypt-goshen"],
  },
  {
    id: "burning-bush",
    name: "The Burning Bush",
    category: "exodus",
    description:
      "At Horeb, Yahweh appears to Moses in a bush that burns without being consumed and reveals the divine name 'I AM.'",
    startYear: -1447,
    endYear: -1447,
    scriptureReferences: ["Exodus 3-4", "Acts 7:30-34"],
    confidenceLevel: "traditional",
    placeIds: ["mount-sinai"],
  },
  {
    id: "exodus",
    name: "The Exodus",
    category: "exodus",
    description:
      "Yahweh delivers Israel from Egyptian bondage through the ten plagues, Passover, and the splitting of the Red Sea — the founding redemption of the Old Testament.",
    startYear: -1446,
    endYear: -1446,
    scriptureReferences: ["Exodus 1-15", "1 Kings 6:1"],
    confidenceLevel: "traditional",
    traditionTags: ["early-date-1446BC"],
    placeIds: ["egypt-goshen"],
    notes:
      "Early date (~1446 BC) follows 1 Kings 6:1 + 480 years before Solomon's temple. Late date (~1260 BC) is held by many archaeologists; we use the early date.",
  },
  {
    id: "golden-calf",
    name: "Golden Calf at Sinai",
    category: "exodus",
    description:
      "While Moses is on the mountain, Aaron forms a calf of gold for the people to worship; Moses shatters the first tablets, and 3,000 die.",
    startYear: -1446,
    endYear: -1446,
    scriptureReferences: ["Exodus 32", "Deuteronomy 9:7-21", "1 Corinthians 10:7"],
    confidenceLevel: "traditional",
    placeIds: ["mount-sinai"],
  },
  {
    id: "sinai-covenant",
    name: "Sinai Covenant",
    category: "exodus",
    description:
      "Yahweh gives the Decalogue and the law at Mount Sinai; the tabernacle is built and consecrated.",
    startYear: -1446,
    endYear: -1445,
    scriptureReferences: ["Exodus 19-40", "Leviticus", "Numbers 1-10"],
    confidenceLevel: "traditional",
    placeIds: ["mount-sinai"],
  },
  {
    id: "wilderness-wandering",
    name: "Wilderness Wandering",
    category: "exodus",
    description:
      "Forty years in the wilderness following the spy report; the unbelieving generation dies before entry into the land.",
    startYear: -1446,
    endYear: -1406,
    scriptureReferences: ["Numbers 13-14", "Numbers 20-36", "Deuteronomy"],
    confidenceLevel: "traditional",
  },
  {
    id: "death-of-moses",
    name: "Death of Moses on Mount Nebo",
    category: "exodus",
    description:
      "Moses ascends Nebo, sees the Promised Land, and dies at 120; the LORD himself buries him in an unknown grave.",
    startYear: -1406,
    endYear: -1406,
    scriptureReferences: ["Deuteronomy 34", "Jude 1:9"],
    confidenceLevel: "traditional",
  },
  {
    id: "fall-of-jericho",
    name: "Fall of Jericho",
    category: "conquest",
    description:
      "Israel marches around Jericho seven days; on the seventh, the priests blow trumpets and the walls collapse — the first city of the conquest.",
    startYear: -1406,
    endYear: -1406,
    scriptureReferences: ["Joshua 6", "Hebrews 11:30"],
    confidenceLevel: "traditional",
    placeIds: ["jericho"],
  },
  {
    id: "conquest",
    name: "Conquest of Canaan",
    category: "conquest",
    description:
      "Joshua leads Israel across the Jordan; Jericho, Ai, the southern campaign, and the northern campaign; tribal allotments distributed.",
    startYear: -1406,
    endYear: -1399,
    scriptureReferences: ["Joshua 1-24"],
    confidenceLevel: "traditional",
    placeIds: ["jordan-river", "jericho", "shechem", "shiloh"],
  },
  {
    id: "judges-period",
    name: "Period of the Judges",
    category: "judges",
    description:
      "Cycles of apostasy, oppression, and deliverance through Othniel, Ehud, Deborah, Gideon, Jephthah, Samson, and others.",
    startYear: -1380,
    endYear: -1050,
    scriptureReferences: ["Judges 1-21", "Ruth 1-4", "1 Samuel 1-7"],
    confidenceLevel: "traditional",
  },
  {
    id: "saul-anointed",
    name: "Saul Anointed King",
    category: "monarchy",
    description: "Samuel anoints Saul as Israel's first king at the people's demand.",
    startYear: -1050,
    endYear: -1050,
    scriptureReferences: ["1 Samuel 9-10"],
    confidenceLevel: "traditional",
  },
  {
    id: "david-anointed",
    name: "David Anointed King",
    category: "monarchy",
    description:
      "Samuel anoints David in Bethlehem; David later reigns over Judah at Hebron, then over all Israel at Jerusalem.",
    startYear: -1010,
    endYear: -1003,
    scriptureReferences: ["1 Samuel 16", "2 Samuel 2:1-4", "2 Samuel 5:1-5"],
    confidenceLevel: "traditional",
    placeIds: ["bethlehem", "hebron", "jerusalem"],
  },
  {
    id: "david-and-goliath",
    name: "David and Goliath",
    category: "monarchy",
    description:
      "The young shepherd David fells the Philistine champion Goliath of Gath with a sling and stone in the Valley of Elah.",
    startYear: -1024,
    endYear: -1024,
    scriptureReferences: ["1 Samuel 17"],
    confidenceLevel: "traditional",
  },
  {
    id: "davidic-covenant",
    name: "Davidic Covenant",
    category: "monarchy",
    description:
      "Yahweh promises David an everlasting house, throne, and kingdom through his offspring.",
    startYear: -1000,
    endYear: -1000,
    scriptureReferences: ["2 Samuel 7", "1 Chronicles 17", "Psalm 89", "Psalm 132"],
    confidenceLevel: "stated",
  },
  {
    id: "temple-built",
    name: "First Temple Built",
    category: "monarchy",
    description: "Solomon builds and dedicates the first temple in Jerusalem.",
    startYear: -966,
    endYear: -959,
    scriptureReferences: ["1 Kings 5-8", "2 Chronicles 2-7"],
    confidenceLevel: "traditional",
    placeIds: ["jerusalem"],
  },
  {
    id: "solomons-wisdom",
    name: "Solomon's Wisdom: The Two Mothers",
    category: "monarchy",
    description:
      "Solomon adjudicates between two mothers claiming the same child by ordering it cut in half — exposing the true mother. All Israel feared the king when they heard the verdict.",
    startYear: -970,
    endYear: -970,
    scriptureReferences: ["1 Kings 3:16-28"],
    confidenceLevel: "traditional",
    placeIds: ["jerusalem"],
  },
  {
    id: "queen-of-sheba",
    name: "Queen of Sheba Visits Solomon",
    category: "monarchy",
    description:
      "The Queen of Sheba travels from southern Arabia to test Solomon with hard questions; her breath is taken away by his wisdom and the splendor of his court.",
    startYear: -960,
    endYear: -960,
    scriptureReferences: ["1 Kings 10:1-13", "2 Chronicles 9:1-12", "Matthew 12:42"],
    confidenceLevel: "traditional",
    placeIds: ["jerusalem"],
  },
  {
    id: "kingdom-divided",
    name: "Kingdom Divided",
    category: "monarchy",
    description:
      "After Solomon's death, ten northern tribes secede under Jeroboam I, leaving Rehoboam with Judah and Benjamin.",
    startYear: -931,
    endYear: -931,
    scriptureReferences: ["1 Kings 12", "2 Chronicles 10"],
    confidenceLevel: "traditional",
    placeIds: ["shechem"],
  },
  {
    id: "elijah-carmel",
    name: "Elijah at Mount Carmel",
    category: "prophets",
    description:
      "Elijah confronts the prophets of Baal in front of all Israel; fire falls and consumes the sacrifice. The LORD, he is God.",
    startYear: -860,
    endYear: -860,
    scriptureReferences: ["1 Kings 18"],
    confidenceLevel: "traditional",
    placeIds: ["mount-carmel"],
  },
  {
    id: "elijah-ascends",
    name: "Elijah Taken Up in a Whirlwind",
    category: "prophets",
    description:
      "Elijah is taken up to heaven in a chariot of fire across the Jordan; Elisha receives a double portion of his spirit.",
    startYear: -848,
    endYear: -848,
    scriptureReferences: ["2 Kings 2:1-18", "Malachi 4:5-6"],
    confidenceLevel: "traditional",
    placeIds: ["jordan-river"],
  },
  {
    id: "jonah-nineveh",
    name: "Jonah Preaches to Nineveh",
    category: "prophets",
    description:
      "After fleeing to Tarshish and being swallowed by a great fish, Jonah preaches to Nineveh; the entire city repents from king to cattle.",
    startYear: -760,
    endYear: -760,
    scriptureReferences: ["Jonah 1-4", "Matthew 12:38-41"],
    confidenceLevel: "traditional",
    placeIds: ["nineveh"],
  },
  {
    id: "fall-of-samaria",
    name: "Fall of Samaria / Assyrian Exile",
    category: "exile",
    description:
      "Sargon II of Assyria destroys Samaria and deports the northern kingdom; Israel ceases as a political entity.",
    startYear: -722,
    endYear: -722,
    scriptureReferences: ["2 Kings 17", "2 Kings 18:9-12"],
    confidenceLevel: "stated",
    placeIds: ["samaria-city", "nineveh"],
  },
  {
    id: "sennacherib-invasion",
    name: "Sennacherib's Invasion of Judah",
    category: "monarchy",
    description:
      "Sennacherib of Assyria invades Judah, takes 46 fortified cities, but his siege of Jerusalem under Hezekiah is broken by the angel of Yahweh.",
    startYear: -701,
    endYear: -701,
    scriptureReferences: ["2 Kings 18-19", "2 Chronicles 32", "Isaiah 36-37"],
    confidenceLevel: "stated",
    placeIds: ["jerusalem", "nineveh"],
  },
  {
    id: "fall-of-jerusalem-586",
    name: "Fall of Jerusalem (586 BC)",
    category: "exile",
    description:
      "Nebuchadnezzar II of Babylon destroys Jerusalem and the first temple; Judah deported. Two earlier deportations occurred in 605 (Daniel) and 597 (Jehoiachin, Ezekiel).",
    startYear: -586,
    endYear: -586,
    scriptureReferences: ["2 Kings 25", "2 Chronicles 36:15-21", "Jeremiah 39", "Jeremiah 52", "Lamentations"],
    confidenceLevel: "stated",
    placeIds: ["jerusalem", "babylon"],
  },
  {
    id: "babylonian-exile",
    name: "Babylonian Exile",
    category: "exile",
    description:
      "Seventy-year exile of Judah in Babylon; setting of Daniel and Ezekiel.",
    startYear: -605,
    endYear: -538,
    scriptureReferences: ["2 Chronicles 36:20-21", "Jeremiah 25:11-12", "Jeremiah 29:10", "Daniel 1-9", "Ezekiel 1-48"],
    confidenceLevel: "stated",
    placeIds: ["babylon"],
  },
  {
    id: "daniel-lions-den",
    name: "Daniel in the Lions' Den",
    category: "exile",
    description:
      "Under Darius the Mede, Daniel is thrown to the lions for praying to Yahweh; God shuts the lions' mouths and Daniel emerges unharmed.",
    startYear: -540,
    endYear: -540,
    scriptureReferences: ["Daniel 6", "Hebrews 11:33"],
    confidenceLevel: "stated",
    placeIds: ["babylon"],
  },
  {
    id: "edict-of-cyrus",
    name: "Edict of Cyrus / First Return",
    category: "return",
    description:
      "Cyrus the Great permits the Jews to return and rebuild the temple; Zerubbabel and Joshua lead the first return.",
    startYear: -538,
    endYear: -538,
    scriptureReferences: ["2 Chronicles 36:22-23", "Ezra 1", "Isaiah 44:28", "Isaiah 45:1-7"],
    confidenceLevel: "stated",
  },
  {
    id: "second-temple",
    name: "Second Temple Completed",
    category: "return",
    description:
      "The temple is rebuilt under Zerubbabel and Joshua, encouraged by Haggai and Zechariah, in the sixth year of Darius I.",
    startYear: -520,
    endYear: -516,
    scriptureReferences: ["Ezra 5-6", "Haggai", "Zechariah 1-8"],
    confidenceLevel: "stated",
    placeIds: ["jerusalem"],
  },
  {
    id: "esther-purim",
    name: "Esther Saves the Jews / Purim",
    category: "return",
    description:
      "In Susa under Xerxes I, Esther exposes Haman's genocidal plot; the Jews are delivered and the feast of Purim is instituted.",
    startYear: -473,
    endYear: -473,
    scriptureReferences: ["Esther 1-10"],
    confidenceLevel: "stated",
  },
  {
    id: "ezras-return",
    name: "Ezra's Return",
    category: "return",
    description:
      "Ezra leads a second return to Jerusalem to teach the law and reform the community.",
    startYear: -458,
    endYear: -458,
    scriptureReferences: ["Ezra 7-10"],
    confidenceLevel: "stated",
  },
  {
    id: "nehemiahs-walls",
    name: "Nehemiah Rebuilds the Walls",
    category: "return",
    description:
      "Nehemiah, cupbearer to Artaxerxes I, leads the rebuilding of Jerusalem's walls in 52 days.",
    startYear: -445,
    endYear: -445,
    scriptureReferences: ["Nehemiah 1-7"],
    confidenceLevel: "stated",
    placeIds: ["jerusalem"],
  },
  {
    id: "intertestamental-period",
    name: "Intertestamental Period",
    category: "intertestamental",
    description:
      "The roughly 400 'silent years' between Malachi and John the Baptist; Persian, Hellenistic, Maccabean, and Roman dominations.",
    startYear: -432,
    endYear: -5,
    scriptureReferences: ["Daniel 7-12", "Daniel 11", "1 Maccabees", "2 Maccabees"],
    confidenceLevel: "traditional",
  },
  {
    id: "annunciation",
    name: "The Annunciation",
    category: "christ",
    description:
      "Gabriel appears to Mary in Nazareth and announces that she will conceive by the Holy Spirit and bear the Son of the Most High.",
    startYear: -5,
    endYear: -5,
    scriptureReferences: ["Luke 1:26-38", "Isaiah 7:14"],
    confidenceLevel: "traditional",
    placeIds: ["nazareth"],
  },
  {
    id: "birth-of-christ",
    name: "Birth of Jesus Christ",
    category: "christ",
    description:
      "The incarnation: Jesus is born in Bethlehem of Judea in the days of Herod the Great. The traditional 1 BC dating is 4-5 years late; Herod died in 4 BC, placing the nativity ~6-4 BC.",
    startYear: -5,
    endYear: -4,
    scriptureReferences: ["Matthew 1-2", "Luke 1-2"],
    confidenceLevel: "traditional",
    placeIds: ["bethlehem"],
  },
  {
    id: "visit-of-the-magi",
    name: "Visit of the Magi",
    category: "christ",
    description:
      "Wise men from the east follow a star to the child Jesus and present gold, frankincense, and myrrh; Joseph then flees with the family to Egypt.",
    startYear: -4,
    endYear: -4,
    scriptureReferences: ["Matthew 2:1-18"],
    confidenceLevel: "traditional",
    placeIds: ["bethlehem"],
  },
  {
    id: "baptism-of-christ",
    name: "Baptism of Jesus",
    category: "christ",
    description:
      "John the Baptist baptizes Jesus in the Jordan; the Spirit descends and the Father speaks.",
    startYear: 27,
    endYear: 27,
    scriptureReferences: ["Matthew 3:13-17", "Mark 1:9-11", "Luke 3:21-22", "John 1:29-34"],
    confidenceLevel: "traditional",
    placeIds: ["jordan-river"],
  },
  {
    id: "ministry-of-christ",
    name: "Public Ministry of Jesus",
    category: "christ",
    description:
      "The roughly three-and-a-half-year public ministry from Jesus' baptism to his crucifixion: Galilean ministry, journeys through Samaria and Perea, and Judean confrontations.",
    startYear: 27,
    endYear: 30,
    scriptureReferences: ["Matthew 4-25", "Mark 1-13", "Luke 4-21", "John 1-12"],
    confidenceLevel: "traditional",
    placeIds: ["nazareth", "capernaum", "sea-of-galilee", "jerusalem"],
  },
  {
    id: "sermon-on-the-mount",
    name: "Sermon on the Mount",
    category: "christ",
    description:
      "Jesus delivers the Beatitudes and the manifesto of the kingdom on a mountainside in Galilee — the most extensive sermon of his recorded teaching.",
    startYear: 28,
    endYear: 28,
    scriptureReferences: ["Matthew 5-7", "Luke 6:17-49"],
    confidenceLevel: "traditional",
    placeIds: ["sea-of-galilee"],
  },
  {
    id: "feeding-the-5000",
    name: "Feeding of the 5,000",
    category: "christ",
    description:
      "Jesus multiplies five loaves and two fish to feed five thousand men besides women and children — recorded in all four gospels.",
    startYear: 29,
    endYear: 29,
    scriptureReferences: ["Matthew 14:13-21", "Mark 6:30-44", "Luke 9:10-17", "John 6:1-15"],
    confidenceLevel: "stated",
    placeIds: ["sea-of-galilee"],
  },
  {
    id: "transfiguration",
    name: "The Transfiguration",
    category: "christ",
    description:
      "On a high mountain, Jesus is transfigured before Peter, James, and John; Moses and Elijah appear; the Father's voice declares 'This is my Son.'",
    startYear: 29,
    endYear: 29,
    scriptureReferences: ["Matthew 17:1-13", "Mark 9:2-13", "Luke 9:28-36", "2 Peter 1:16-18"],
    confidenceLevel: "traditional",
  },
  {
    id: "triumphal-entry",
    name: "Triumphal Entry into Jerusalem",
    category: "christ",
    description:
      "Five days before Passover, Jesus enters Jerusalem on a donkey to crowds shouting 'Hosanna' — fulfilling Zechariah 9:9.",
    startYear: 30,
    endYear: 30,
    scriptureReferences: ["Matthew 21:1-11", "Mark 11:1-11", "Luke 19:28-44", "John 12:12-19", "Zechariah 9:9"],
    confidenceLevel: "stated",
    placeIds: ["jerusalem", "mount-of-olives"],
  },
  {
    id: "last-supper",
    name: "The Last Supper",
    category: "christ",
    description:
      "On the night he was betrayed, Jesus eats Passover with the Twelve, washes their feet, institutes the Eucharist, and delivers the Upper Room discourse.",
    startYear: 30,
    endYear: 30,
    scriptureReferences: ["Matthew 26:17-30", "Mark 14:12-26", "Luke 22:7-38", "John 13-17", "1 Corinthians 11:23-26"],
    confidenceLevel: "stated",
    placeIds: ["jerusalem"],
  },
  {
    id: "crucifixion",
    name: "Crucifixion of Jesus",
    category: "christ",
    description:
      "Jesus is crucified outside Jerusalem at Golgotha at Passover; buried in a new tomb. Most likely date: 14 Nisan, AD 30 or AD 33.",
    startYear: 30,
    endYear: 30,
    scriptureReferences: ["Matthew 26-27", "Mark 14-15", "Luke 22-23", "John 18-19", "1 Corinthians 15:3-4"],
    confidenceLevel: "stated",
    traditionTags: ["AD30", "AD33-alternative"],
    placeIds: ["jerusalem", "gethsemane", "golgotha"],
  },
  {
    id: "resurrection",
    name: "Resurrection of Jesus",
    category: "christ",
    description:
      "On the third day, Jesus rises bodily from the dead; appears to Mary Magdalene, the women, the eleven, and 500 brethren over 40 days before ascending.",
    startYear: 30,
    endYear: 30,
    scriptureReferences: ["Matthew 28", "Mark 16", "Luke 24", "John 20-21", "Acts 1:3", "1 Corinthians 15:3-8"],
    confidenceLevel: "stated",
    placeIds: ["jerusalem", "golgotha"],
  },
  {
    id: "ascension",
    name: "Ascension of Jesus",
    category: "christ",
    description:
      "Forty days after the resurrection, Jesus ascends from the Mount of Olives.",
    startYear: 30,
    endYear: 30,
    scriptureReferences: ["Luke 24:50-53", "Acts 1:6-11"],
    confidenceLevel: "stated",
    placeIds: ["mount-of-olives"],
  },
  {
    id: "pentecost",
    name: "Pentecost / Birth of the Church",
    category: "early-church",
    description:
      "Ten days after the ascension, the Holy Spirit is poured out on the 120 in Jerusalem; Peter preaches and 3,000 are baptized.",
    startYear: 30,
    endYear: 30,
    scriptureReferences: ["Acts 2"],
    confidenceLevel: "stated",
    placeIds: ["jerusalem"],
  },
  {
    id: "stephen-martyrdom",
    name: "Martyrdom of Stephen",
    category: "early-church",
    description:
      "Stephen, the first of the seven deacons, is stoned outside Jerusalem; persecution scatters the church and Saul of Tarsus consents.",
    startYear: 34,
    endYear: 34,
    scriptureReferences: ["Acts 6-7", "Acts 8:1-3"],
    confidenceLevel: "stated",
    placeIds: ["jerusalem"],
  },
  {
    id: "conversion-of-paul",
    name: "Conversion of Saul of Tarsus",
    category: "early-church",
    description:
      "On the road to Damascus, the risen Christ confronts Saul; he is blinded, baptized by Ananias, and called to be apostle to the Gentiles.",
    startYear: 34,
    endYear: 34,
    scriptureReferences: ["Acts 9:1-31", "Acts 22:1-21", "Acts 26:1-23", "Galatians 1:11-24"],
    confidenceLevel: "stated",
    placeIds: ["damascus"],
  },
  {
    id: "cornelius-conversion",
    name: "Conversion of Cornelius",
    category: "early-church",
    description:
      "Peter is sent in a vision to the Roman centurion Cornelius in Caesarea; the Holy Spirit falls on Gentiles for the first time, and the door of faith is opened to the nations.",
    startYear: 40,
    endYear: 40,
    scriptureReferences: ["Acts 10", "Acts 11:1-18", "Acts 15:7-9"],
    confidenceLevel: "stated",
  },
  {
    id: "antioch-christians",
    name: "Believers First Called Christians",
    category: "early-church",
    description:
      "At Antioch in Syria — where Greeks first turned to the Lord in numbers — the disciples were first called Christians. Antioch becomes the launching base for the Gentile mission.",
    startYear: 43,
    endYear: 43,
    scriptureReferences: ["Acts 11:19-26"],
    confidenceLevel: "stated",
    placeIds: ["antioch-syria"],
  },
  {
    id: "council-of-jerusalem",
    name: "Council of Jerusalem",
    category: "early-church",
    description:
      "The apostles and elders rule that Gentile believers are not bound by the law of Moses for circumcision; the gospel is freed for the nations.",
    startYear: 49,
    endYear: 49,
    scriptureReferences: ["Acts 15", "Galatians 2:1-10"],
    confidenceLevel: "stated",
    placeIds: ["jerusalem", "antioch-syria"],
  },
  {
    id: "pauls-missionary-journeys",
    name: "Paul's Missionary Journeys",
    category: "early-church",
    description:
      "Three missionary journeys (~AD 47-57) plus the Roman voyage (~AD 60-62), planting churches throughout Asia Minor, Macedonia, Achaia, and ultimately reaching Rome.",
    startYear: 47,
    endYear: 62,
    scriptureReferences: ["Acts 13-28"],
    confidenceLevel: "stated",
    placeIds: ["antioch-syria", "ephesus", "corinth", "athens", "philippi", "thessalonica", "rome"],
  },
  {
    id: "neronian-persecution",
    name: "Neronian Persecution",
    category: "early-church",
    description:
      "After the Great Fire of Rome (AD 64), Nero blames the Christians and launches the first imperial persecution. Peter and Paul traditionally martyred under Nero.",
    startYear: 64,
    endYear: 68,
    scriptureReferences: ["1 Peter 4:12-19", "2 Timothy 4:6-8"],
    confidenceLevel: "traditional",
    placeIds: ["rome"],
  },
  {
    id: "fall-of-jerusalem-70",
    name: "Fall of Jerusalem (AD 70)",
    category: "early-church",
    description:
      "Titus, son of Vespasian, destroys Jerusalem and the second temple, ending the temple sacrificial system. Fulfillment of Jesus' Olivet Discourse prediction.",
    startYear: 70,
    endYear: 70,
    scriptureReferences: ["Matthew 24:1-35", "Mark 13:1-31", "Luke 21:5-24"],
    confidenceLevel: "stated",
    placeIds: ["jerusalem"],
  },
  {
    id: "patmos-revelation",
    name: "John on Patmos / Revelation",
    category: "early-church",
    description:
      "The apostle John, exiled to Patmos under Domitian, receives the Apocalypse — the closing book of the canon.",
    startYear: 95,
    endYear: 96,
    scriptureReferences: ["Revelation 1:9-11"],
    confidenceLevel: "traditional",
    placeIds: ["patmos"],
  },
];
