/*
 * Curated Hebrew names — divine titles and the most theologically/linguistically
 * notable biblical figures. Each entry decomposes the name into morphemes so
 * the UI can color-match the Hebrew text, the transliteration, and the gloss.
 *
 * Scope: this is intentionally a curated selection (~25 divine names, ~60
 * people names). It is NOT exhaustive of every Hebrew name in scripture —
 * that's a much larger lexicographic project. Notes call out debated
 * etymologies; pop-etymological glosses (those given in scripture itself as
 * wordplay) are marked as such.
 *
 * Hebrew text uses Tiberian nikkud where standard. Segments are listed in
 * pronunciation/transliteration order (left-to-right phonetic order); the
 * rendering layer is responsible for applying `dir="rtl"` to the assembled
 * Hebrew string.
 */

export type NameSegment = {
  hebrew: string;
  transliteration: string;
  gloss: string;
};

export type DivineNameCategory =
  | "tetragrammaton"
  | "elohim-family"
  | "adonai-family"
  | "yhwh-compound"
  | "title";

export interface DivineName {
  id: string;
  category: DivineNameCategory;
  hebrew: string;
  transliteration: string;
  meaning: string;
  segments: NameSegment[];
  firstOccurrence: string;
  scriptureReferences: string[];
  notes?: string;
}

export type HebrewNameLanguage = "hebrew" | "aramaic";

export type HebrewNameCategory =
  | "patriarch"
  | "matriarch"
  | "tribe-head"
  | "judge"
  | "king"
  | "prophet"
  | "priest"
  | "leader"
  | "apostle"
  | "disciple"
  | "messianic"
  | "place"
  | "other";

export interface HebrewName {
  id: string;
  englishName: string;
  alternateEnglish?: string[];
  hebrew: string;
  transliteration: string;
  meaning: string;
  segments: NameSegment[];
  language: HebrewNameLanguage;
  category: HebrewNameCategory;
  personId?: string;
  firstOccurrence: string;
  notes?: string;
}

export const DIVINE_NAMES: DivineName[] = [
  {
    id: "yhwh",
    category: "tetragrammaton",
    hebrew: "יהוה",
    transliteration: "YHWH",
    meaning: "He is / He causes to be — the covenant name of God.",
    segments: [
      { hebrew: "י", transliteration: "Y", gloss: "(yod) — 3rd-person prefix 'he'" },
      { hebrew: "ה", transliteration: "H", gloss: "(heh) — from h-y-h, 'to be'" },
      { hebrew: "ו", transliteration: "W", gloss: "(vav) — verbal stem letter" },
      { hebrew: "ה", transliteration: "H", gloss: "(heh) — completing the root" },
    ],
    firstOccurrence: "Genesis 2:4",
    scriptureReferences: ["Genesis 2:4", "Exodus 3:14-15", "Exodus 6:2-3", "Deuteronomy 6:4"],
    notes:
      "The Tetragrammaton — four consonants traditionally not pronounced. Vocalized 'Yahweh' by most scholars; rendered 'LORD' in most English Bibles. Tied to the verb h-y-h ('to be') in Exodus 3:14.",
  },
  {
    id: "yah",
    category: "tetragrammaton",
    hebrew: "יָהּ",
    transliteration: "Yah",
    meaning: "Short form of YHWH — preserved in 'hallelu-Yah' (praise Yah).",
    segments: [
      { hebrew: "יָ", transliteration: "Ya", gloss: "from yod-heh, short form of YHWH" },
      { hebrew: "הּ", transliteration: "h", gloss: "closing heh" },
    ],
    firstOccurrence: "Exodus 15:2",
    scriptureReferences: ["Exodus 15:2", "Psalm 68:4", "Psalm 150:1-6", "Isaiah 12:2"],
    notes: "Found in psalms and theophoric names ending in -yah (Isaiah, Hezekiah, Hallelujah).",
  },
  {
    id: "ehyeh-asher-ehyeh",
    category: "tetragrammaton",
    hebrew: "אֶהְיֶה אֲשֶׁר אֶהְיֶה",
    transliteration: "Ehyeh Asher Ehyeh",
    meaning: "I AM WHO I AM — God's self-disclosure to Moses at the burning bush.",
    segments: [
      { hebrew: "אֶהְיֶה", transliteration: "Ehyeh", gloss: "I will be / I am" },
      { hebrew: "אֲשֶׁר", transliteration: "Asher", gloss: "who / that which" },
      { hebrew: "אֶהְיֶה", transliteration: "Ehyeh", gloss: "I will be / I am" },
    ],
    firstOccurrence: "Exodus 3:14",
    scriptureReferences: ["Exodus 3:14"],
    notes:
      "Also rendered 'I will be what I will be.' The verb is from the same root (h-y-h) as YHWH, making this the etymology God himself gives for the divine name.",
  },
  {
    id: "elohim",
    category: "elohim-family",
    hebrew: "אֱלֹהִים",
    transliteration: "Elohim",
    meaning: "God — the creator-deity name; grammatically plural, treated as singular for the God of Israel.",
    segments: [
      { hebrew: "אֱלֹהִ", transliteration: "Elohi", gloss: "from Eloah, 'god' / 'mighty one'" },
      { hebrew: "ים", transliteration: "im", gloss: "plural ending (intensive plural)" },
    ],
    firstOccurrence: "Genesis 1:1",
    scriptureReferences: ["Genesis 1:1", "Deuteronomy 6:4", "Psalm 19:1"],
    notes:
      "The plural form is debated — classical Christian reading sees a hint of plurality in the Godhead; Hebrew grammar treats it as a 'plural of majesty' or 'intensive plural' taking singular verbs when referring to God.",
  },
  {
    id: "eloah",
    category: "elohim-family",
    hebrew: "אֱלוֹהַּ",
    transliteration: "Eloah",
    meaning: "God — singular form, used heavily in Job and poetic books.",
    segments: [
      { hebrew: "אֱלוֹ", transliteration: "Elo", gloss: "from El, 'god'" },
      { hebrew: "הַּ", transliteration: "ah", gloss: "extended ending" },
    ],
    firstOccurrence: "Deuteronomy 32:15",
    scriptureReferences: ["Deuteronomy 32:15", "Job 3:4", "Habakkuk 3:3"],
  },
  {
    id: "el",
    category: "elohim-family",
    hebrew: "אֵל",
    transliteration: "El",
    meaning: "God — the simple Semitic word for deity, used both alone and as the root of compound names.",
    segments: [
      { hebrew: "אֵ", transliteration: "E", gloss: "(aleph) — strength" },
      { hebrew: "ל", transliteration: "l", gloss: "(lamed) — closing consonant" },
    ],
    firstOccurrence: "Genesis 14:18",
    scriptureReferences: ["Genesis 14:18", "Genesis 33:20", "Numbers 23:8"],
    notes: "Common across Semitic languages. Forms the suffix in names like Daniel, Ezekiel, Israel.",
  },
  {
    id: "el-shaddai",
    category: "elohim-family",
    hebrew: "אֵל שַׁדַּי",
    transliteration: "El Shaddai",
    meaning: "God Almighty — the name by which God revealed himself to the patriarchs.",
    segments: [
      { hebrew: "אֵל", transliteration: "El", gloss: "God" },
      { hebrew: "שַׁדַּי", transliteration: "Shaddai", gloss: "Almighty / Mountain One (etymology debated)" },
    ],
    firstOccurrence: "Genesis 17:1",
    scriptureReferences: ["Genesis 17:1", "Genesis 28:3", "Genesis 35:11", "Exodus 6:3"],
    notes:
      "Etymology debated: traditionally 'Almighty' (from shadad, 'to overpower'); modern scholars often suggest 'God of the Mountain' (from shadu, Akkadian for mountain).",
  },
  {
    id: "el-elyon",
    category: "elohim-family",
    hebrew: "אֵל עֶלְיוֹן",
    transliteration: "El Elyon",
    meaning: "God Most High — sovereign over all powers.",
    segments: [
      { hebrew: "אֵל", transliteration: "El", gloss: "God" },
      { hebrew: "עֶלְיוֹן", transliteration: "Elyon", gloss: "Most High, from alah ('to ascend')" },
    ],
    firstOccurrence: "Genesis 14:18",
    scriptureReferences: ["Genesis 14:18-22", "Numbers 24:16", "Psalm 78:35", "Daniel 7:25"],
    notes: "Name used by Melchizedek when blessing Abram.",
  },
  {
    id: "el-olam",
    category: "elohim-family",
    hebrew: "אֵל עוֹלָם",
    transliteration: "El Olam",
    meaning: "Everlasting God — God of eternity past and future.",
    segments: [
      { hebrew: "אֵל", transliteration: "El", gloss: "God" },
      { hebrew: "עוֹלָם", transliteration: "Olam", gloss: "eternity, age, distant time" },
    ],
    firstOccurrence: "Genesis 21:33",
    scriptureReferences: ["Genesis 21:33", "Isaiah 40:28", "Psalm 90:2"],
  },
  {
    id: "el-roi",
    category: "elohim-family",
    hebrew: "אֵל רֳאִי",
    transliteration: "El Ro'i",
    meaning: "God Who Sees Me — Hagar's name for God in the wilderness.",
    segments: [
      { hebrew: "אֵל", transliteration: "El", gloss: "God" },
      { hebrew: "רֳאִי", transliteration: "Ro'i", gloss: "who sees me, from ra'ah ('to see')" },
    ],
    firstOccurrence: "Genesis 16:13",
    scriptureReferences: ["Genesis 16:13"],
  },
  {
    id: "el-gibbor",
    category: "elohim-family",
    hebrew: "אֵל גִּבּוֹר",
    transliteration: "El Gibbor",
    meaning: "Mighty God — title applied to the promised Messiah.",
    segments: [
      { hebrew: "אֵל", transliteration: "El", gloss: "God" },
      { hebrew: "גִּבּוֹר", transliteration: "Gibbor", gloss: "mighty warrior, hero, from gavar ('to be strong')" },
    ],
    firstOccurrence: "Isaiah 9:6",
    scriptureReferences: ["Isaiah 9:6", "Isaiah 10:21", "Jeremiah 32:18"],
  },
  {
    id: "adonai",
    category: "adonai-family",
    hebrew: "אֲדֹנָי",
    transliteration: "Adonai",
    meaning: "My Lord / My Master — used as a spoken substitute for YHWH.",
    segments: [
      { hebrew: "אֲדֹנָ", transliteration: "Adona", gloss: "from adon, 'lord/master'" },
      { hebrew: "י", transliteration: "i", gloss: "1st-person possessive suffix, 'my'" },
    ],
    firstOccurrence: "Genesis 15:2",
    scriptureReferences: ["Genesis 15:2", "Exodus 4:10", "Psalm 8:1"],
    notes:
      "Out of reverence for YHWH, Jewish tradition reads 'Adonai' wherever the Tetragrammaton appears. The masoretic vowels of YHWH are borrowed from Adonai, producing the hybrid 'Jehovah.'",
  },
  {
    id: "adon",
    category: "adonai-family",
    hebrew: "אָדוֹן",
    transliteration: "Adon",
    meaning: "Lord / Sovereign — non-suffixed form.",
    segments: [
      { hebrew: "אָדוֹן", transliteration: "Adon", gloss: "lord, master, ruler" },
    ],
    firstOccurrence: "Joshua 3:11",
    scriptureReferences: ["Joshua 3:11", "Psalm 97:5", "Malachi 3:1"],
  },
  {
    id: "yhwh-yireh",
    category: "yhwh-compound",
    hebrew: "יְהוָה יִרְאֶה",
    transliteration: "YHWH Yireh",
    meaning: "The LORD Will Provide — named by Abraham after the ram replaced Isaac.",
    segments: [
      { hebrew: "יְהוָה", transliteration: "YHWH", gloss: "the Lord (covenant name)" },
      { hebrew: "יִרְאֶה", transliteration: "Yireh", gloss: "will see / will provide, from ra'ah" },
    ],
    firstOccurrence: "Genesis 22:14",
    scriptureReferences: ["Genesis 22:14"],
    notes: "Traditionally 'Jehovah-Jireh.' Same verb (see) implies God's foresight and provision are one act.",
  },
  {
    id: "yhwh-rapha",
    category: "yhwh-compound",
    hebrew: "יְהוָה רֹפְאֶךָ",
    transliteration: "YHWH Rofecha",
    meaning: "The LORD Who Heals You — covenant promise at Marah after the bitter water.",
    segments: [
      { hebrew: "יְהוָה", transliteration: "YHWH", gloss: "the Lord" },
      { hebrew: "רֹפְאֶ", transliteration: "Rofe", gloss: "healer, physician, from rapha" },
      { hebrew: "ךָ", transliteration: "cha", gloss: "2nd-person masculine suffix, 'you'" },
    ],
    firstOccurrence: "Exodus 15:26",
    scriptureReferences: ["Exodus 15:26"],
    notes: "Often given as 'Jehovah-Rapha.'",
  },
  {
    id: "yhwh-nissi",
    category: "yhwh-compound",
    hebrew: "יְהוָה נִסִּי",
    transliteration: "YHWH Nissi",
    meaning: "The LORD Is My Banner — named by Moses after defeating Amalek.",
    segments: [
      { hebrew: "יְהוָה", transliteration: "YHWH", gloss: "the Lord" },
      { hebrew: "נִסִּ", transliteration: "Niss", gloss: "banner, standard, from nes" },
      { hebrew: "י", transliteration: "i", gloss: "1st-person suffix, 'my'" },
    ],
    firstOccurrence: "Exodus 17:15",
    scriptureReferences: ["Exodus 17:15"],
  },
  {
    id: "yhwh-shalom",
    category: "yhwh-compound",
    hebrew: "יְהוָה שָׁלוֹם",
    transliteration: "YHWH Shalom",
    meaning: "The LORD Is Peace — name of Gideon's altar at Ophrah.",
    segments: [
      { hebrew: "יְהוָה", transliteration: "YHWH", gloss: "the Lord" },
      { hebrew: "שָׁלוֹם", transliteration: "Shalom", gloss: "peace, completeness, welfare" },
    ],
    firstOccurrence: "Judges 6:24",
    scriptureReferences: ["Judges 6:24"],
  },
  {
    id: "yhwh-tsidkenu",
    category: "yhwh-compound",
    hebrew: "יְהוָה צִדְקֵנוּ",
    transliteration: "YHWH Tsidkenu",
    meaning: "The LORD Our Righteousness — messianic title in Jeremiah.",
    segments: [
      { hebrew: "יְהוָה", transliteration: "YHWH", gloss: "the Lord" },
      { hebrew: "צִדְקֵ", transliteration: "Tsidke", gloss: "righteousness, from tsedek" },
      { hebrew: "נוּ", transliteration: "nu", gloss: "1st-person plural suffix, 'our'" },
    ],
    firstOccurrence: "Jeremiah 23:6",
    scriptureReferences: ["Jeremiah 23:6", "Jeremiah 33:16"],
    notes: "Applied to the coming righteous Branch from David's line.",
  },
  {
    id: "yhwh-ro'i",
    category: "yhwh-compound",
    hebrew: "יְהוָה רֹעִי",
    transliteration: "YHWH Ro'i",
    meaning: "The LORD Is My Shepherd — opening of Psalm 23.",
    segments: [
      { hebrew: "יְהוָה", transliteration: "YHWH", gloss: "the Lord" },
      { hebrew: "רֹעִ", transliteration: "Ro'", gloss: "shepherd, from ra'ah ('to pasture')" },
      { hebrew: "י", transliteration: "i", gloss: "1st-person suffix, 'my'" },
    ],
    firstOccurrence: "Psalm 23:1",
    scriptureReferences: ["Psalm 23:1"],
  },
  {
    id: "yhwh-shammah",
    category: "yhwh-compound",
    hebrew: "יְהוָה שָׁמָּה",
    transliteration: "YHWH Shammah",
    meaning: "The LORD Is There — name of the restored eschatological Jerusalem.",
    segments: [
      { hebrew: "יְהוָה", transliteration: "YHWH", gloss: "the Lord" },
      { hebrew: "שָׁמָּה", transliteration: "Shammah", gloss: "there, in that place" },
    ],
    firstOccurrence: "Ezekiel 48:35",
    scriptureReferences: ["Ezekiel 48:35"],
  },
  {
    id: "yhwh-tsevaot",
    category: "yhwh-compound",
    hebrew: "יְהוָה צְבָאוֹת",
    transliteration: "YHWH Tsevaot",
    meaning: "LORD of Hosts / Armies — the LORD commanding the heavenly armies.",
    segments: [
      { hebrew: "יְהוָה", transliteration: "YHWH", gloss: "the Lord" },
      { hebrew: "צְבָא", transliteration: "Tseva", gloss: "army, host" },
      { hebrew: "וֹת", transliteration: "ot", gloss: "feminine plural ending" },
    ],
    firstOccurrence: "1 Samuel 1:3",
    scriptureReferences: ["1 Samuel 1:3", "Psalm 24:10", "Isaiah 6:3", "Malachi 1:14"],
    notes: "Often rendered 'Lord of Sabaoth' in older English translations.",
  },
  {
    id: "yhwh-mekaddesh",
    category: "yhwh-compound",
    hebrew: "יְהוָה מְקַדִּשְׁכֶם",
    transliteration: "YHWH Mekaddishkhem",
    meaning: "The LORD Who Sanctifies You — title bound to the covenant law in Leviticus.",
    segments: [
      { hebrew: "יְהוָה", transliteration: "YHWH", gloss: "the Lord" },
      { hebrew: "מְקַדִּשְׁ", transliteration: "Mekaddish", gloss: "the one sanctifying, from qadash ('to be holy')" },
      { hebrew: "כֶם", transliteration: "khem", gloss: "2nd-person plural suffix, 'you' (pl.)" },
    ],
    firstOccurrence: "Exodus 31:13",
    scriptureReferences: ["Exodus 31:13", "Leviticus 20:8", "Leviticus 21:8", "Ezekiel 20:12"],
  },
  {
    id: "qadosh-yisrael",
    category: "title",
    hebrew: "קְדוֹשׁ יִשְׂרָאֵל",
    transliteration: "Qadosh Yisrael",
    meaning: "The Holy One of Israel — Isaiah's signature title for God.",
    segments: [
      { hebrew: "קְדוֹשׁ", transliteration: "Qadosh", gloss: "holy, set apart" },
      { hebrew: "יִשְׂרָאֵל", transliteration: "Yisrael", gloss: "Israel" },
    ],
    firstOccurrence: "2 Kings 19:22",
    scriptureReferences: ["2 Kings 19:22", "Psalm 71:22", "Isaiah 1:4", "Isaiah 41:14"],
  },
  {
    id: "atik-yomin",
    category: "title",
    hebrew: "עַתִּיק יוֹמִין",
    transliteration: "Atiq Yomin",
    meaning: "Ancient of Days — Aramaic title in Daniel's throne vision.",
    segments: [
      { hebrew: "עַתִּיק", transliteration: "Atiq", gloss: "ancient, advanced in age (Aramaic)" },
      { hebrew: "יוֹמִין", transliteration: "Yomin", gloss: "days (Aramaic plural)" },
    ],
    firstOccurrence: "Daniel 7:9",
    scriptureReferences: ["Daniel 7:9", "Daniel 7:13", "Daniel 7:22"],
    notes: "One of the few divine titles in Aramaic rather than Hebrew.",
  },
  {
    id: "avinu",
    category: "title",
    hebrew: "אָבִינוּ",
    transliteration: "Avinu",
    meaning: "Our Father — covenant address of God in prayer.",
    segments: [
      { hebrew: "אָבִי", transliteration: "Avi", gloss: "from av, 'father'" },
      { hebrew: "נוּ", transliteration: "nu", gloss: "1st-person plural suffix, 'our'" },
    ],
    firstOccurrence: "Isaiah 63:16",
    scriptureReferences: ["Isaiah 63:16", "Isaiah 64:8", "Malachi 2:10"],
    notes: "The basis of the opening of the Lord's Prayer (Avinu shebashamayim).",
  },
];

export const HEBREW_NAMES: HebrewName[] = [
  /* ───── Patriarchs & matriarchs ───── */
  {
    id: "adam",
    englishName: "Adam",
    hebrew: "אָדָם",
    transliteration: "Adam",
    meaning: "Man / humankind — from adamah, 'ground.'",
    segments: [
      { hebrew: "אָדָ", transliteration: "Ada", gloss: "from adamah, 'ground/red earth'" },
      { hebrew: "ם", transliteration: "m", gloss: "closing mem" },
    ],
    language: "hebrew",
    category: "patriarch",
    personId: "adam",
    firstOccurrence: "Genesis 1:26",
    notes: "Wordplay in Genesis 2:7: God formed adam from the adamah.",
  },
  {
    id: "chavvah",
    englishName: "Eve",
    alternateEnglish: ["Chavvah"],
    hebrew: "חַוָּה",
    transliteration: "Chavvah",
    meaning: "Life-giver — 'the mother of all living.'",
    segments: [
      { hebrew: "חַוָּ", transliteration: "Chavva", gloss: "from chayah ('to live'), 'life-giver'" },
      { hebrew: "ה", transliteration: "h", gloss: "feminine ending" },
    ],
    language: "hebrew",
    category: "matriarch",
    personId: "eve",
    firstOccurrence: "Genesis 3:20",
    notes: "Pop-etymology in Genesis 3:20: 'because she was the mother of all living.'",
  },
  {
    id: "noach",
    englishName: "Noah",
    alternateEnglish: ["Noach"],
    hebrew: "נֹחַ",
    transliteration: "Noach",
    meaning: "Rest / comfort.",
    segments: [
      { hebrew: "נֹ", transliteration: "No", gloss: "from nuach, 'to rest'" },
      { hebrew: "חַ", transliteration: "ach", gloss: "closing chet" },
    ],
    language: "hebrew",
    category: "patriarch",
    personId: "noah",
    firstOccurrence: "Genesis 5:29",
    notes: "Genesis 5:29: 'This one shall give us rest from our work.'",
  },
  {
    id: "avraham",
    englishName: "Abraham",
    alternateEnglish: ["Avraham", "Abram"],
    hebrew: "אַבְרָהָם",
    transliteration: "Avraham",
    meaning: "Father of a multitude — renamed from Abram.",
    segments: [
      { hebrew: "אַבְ", transliteration: "Av", gloss: "father" },
      { hebrew: "רָהָם", transliteration: "raham", gloss: "of a multitude (hamon)" },
    ],
    language: "hebrew",
    category: "patriarch",
    personId: "abraham",
    firstOccurrence: "Genesis 17:5",
    notes: "Renamed from Avram ('exalted father') in Genesis 17:5 with this etymological gloss.",
  },
  {
    id: "sarah",
    englishName: "Sarah",
    hebrew: "שָׂרָה",
    transliteration: "Sarah",
    meaning: "Princess.",
    segments: [
      { hebrew: "שָׂרָ", transliteration: "Sara", gloss: "from sar, 'prince/noble'" },
      { hebrew: "ה", transliteration: "h", gloss: "feminine ending" },
    ],
    language: "hebrew",
    category: "matriarch",
    personId: "sarah",
    firstOccurrence: "Genesis 17:15",
    notes: "Renamed from Sarai in Genesis 17:15.",
  },
  {
    id: "yitzchak",
    englishName: "Isaac",
    alternateEnglish: ["Yitzchak"],
    hebrew: "יִצְחָק",
    transliteration: "Yitzchak",
    meaning: "He laughs.",
    segments: [
      { hebrew: "יִ", transliteration: "Yi", gloss: "3rd-person prefix 'he'" },
      { hebrew: "צְחָק", transliteration: "tzchak", gloss: "from tsachaq, 'to laugh'" },
    ],
    language: "hebrew",
    category: "patriarch",
    personId: "isaac",
    firstOccurrence: "Genesis 17:19",
    notes: "Named for Abraham and Sarah's laughter at the promise of a son in old age (Gen 17:17; 18:12; 21:6).",
  },
  {
    id: "rivkah",
    englishName: "Rebekah",
    alternateEnglish: ["Rivkah"],
    hebrew: "רִבְקָה",
    transliteration: "Rivkah",
    meaning: "Captivating / ensnaring.",
    segments: [
      { hebrew: "רִבְ", transliteration: "Riv", gloss: "from a root meaning to bind/tie" },
      { hebrew: "קָה", transliteration: "kah", gloss: "ending" },
    ],
    language: "hebrew",
    category: "matriarch",
    personId: "rebekah",
    firstOccurrence: "Genesis 22:23",
  },
  {
    id: "yaakov",
    englishName: "Jacob",
    alternateEnglish: ["Ya'akov"],
    hebrew: "יַעֲקֹב",
    transliteration: "Ya'akov",
    meaning: "Heel-grabber / supplanter.",
    segments: [
      { hebrew: "יַ", transliteration: "Ya", gloss: "3rd-person prefix 'he'" },
      { hebrew: "עֲקֹב", transliteration: "akov", gloss: "from akev, 'heel'; verb 'to grasp the heel'" },
    ],
    language: "hebrew",
    category: "patriarch",
    personId: "jacob",
    firstOccurrence: "Genesis 25:26",
    notes: "Named because he gripped Esau's heel at birth (Gen 25:26); later renamed Israel (Gen 32:28).",
  },
  {
    id: "yisrael",
    englishName: "Israel",
    alternateEnglish: ["Yisra'el"],
    hebrew: "יִשְׂרָאֵל",
    transliteration: "Yisra'el",
    meaning: "He strives with God / God strives.",
    segments: [
      { hebrew: "יִשְׂרָ", transliteration: "Yisra", gloss: "from sarah, 'to strive/contend/persevere'" },
      { hebrew: "אֵל", transliteration: "El", gloss: "God" },
    ],
    language: "hebrew",
    category: "patriarch",
    personId: "jacob",
    firstOccurrence: "Genesis 32:28",
    notes: "Given to Jacob after wrestling at Peniel: 'for you have struggled with God and with men and have prevailed' (Gen 32:28).",
  },
  {
    id: "esav",
    englishName: "Esau",
    alternateEnglish: ["Esav"],
    hebrew: "עֵשָׂו",
    transliteration: "Esav",
    meaning: "Hairy.",
    segments: [
      { hebrew: "עֵ", transliteration: "E", gloss: "(ayin) opening" },
      { hebrew: "שָׂו", transliteration: "sav", gloss: "from a root meaning hairy/rough" },
    ],
    language: "hebrew",
    category: "patriarch",
    personId: "esau",
    firstOccurrence: "Genesis 25:25",
    notes: "Named for his appearance at birth — covered in red hair (Gen 25:25). Also called Edom ('red').",
  },
  {
    id: "leah",
    englishName: "Leah",
    hebrew: "לֵאָה",
    transliteration: "Leah",
    meaning: "Weary.",
    segments: [
      { hebrew: "לֵאָ", transliteration: "Lea", gloss: "from la'ah, 'to be weary'" },
      { hebrew: "ה", transliteration: "h", gloss: "feminine ending" },
    ],
    language: "hebrew",
    category: "matriarch",
    personId: "leah",
    firstOccurrence: "Genesis 29:16",
  },
  {
    id: "rachel",
    englishName: "Rachel",
    hebrew: "רָחֵל",
    transliteration: "Rachel",
    meaning: "Ewe.",
    segments: [
      { hebrew: "רָחֵל", transliteration: "Rachel", gloss: "female sheep, ewe" },
    ],
    language: "hebrew",
    category: "matriarch",
    personId: "rachel",
    firstOccurrence: "Genesis 29:6",
    notes: "Fitting for a shepherdess of her father's flock (Gen 29:9).",
  },

  /* ───── Sons of Jacob (tribe heads) ───── */
  {
    id: "reuven",
    englishName: "Reuben",
    alternateEnglish: ["Re'uven"],
    hebrew: "רְאוּבֵן",
    transliteration: "Re'uven",
    meaning: "See, a son! — Leah's cry at his birth.",
    segments: [
      { hebrew: "רְאוּ", transliteration: "Re'u", gloss: "imperative 'see!', from ra'ah" },
      { hebrew: "בֵן", transliteration: "ven", gloss: "from ben, 'son'" },
    ],
    language: "hebrew",
    category: "tribe-head",
    personId: "reuben",
    firstOccurrence: "Genesis 29:32",
  },
  {
    id: "shimon",
    englishName: "Simeon",
    alternateEnglish: ["Shim'on"],
    hebrew: "שִׁמְעוֹן",
    transliteration: "Shim'on",
    meaning: "Hearing — 'because the LORD has heard.'",
    segments: [
      { hebrew: "שִׁמְ", transliteration: "Shim", gloss: "from shama, 'to hear'" },
      { hebrew: "עוֹן", transliteration: "on", gloss: "noun-forming suffix" },
    ],
    language: "hebrew",
    category: "tribe-head",
    personId: "simeon",
    firstOccurrence: "Genesis 29:33",
  },
  {
    id: "levi",
    englishName: "Levi",
    hebrew: "לֵוִי",
    transliteration: "Levi",
    meaning: "Joined / attached.",
    segments: [
      { hebrew: "לֵוִ", transliteration: "Lev", gloss: "from lavah, 'to join/attach'" },
      { hebrew: "י", transliteration: "i", gloss: "ending" },
    ],
    language: "hebrew",
    category: "tribe-head",
    personId: "levi",
    firstOccurrence: "Genesis 29:34",
    notes: "Genesis 29:34: 'Now this time my husband will be joined to me.'",
  },
  {
    id: "yehudah",
    englishName: "Judah",
    alternateEnglish: ["Yehudah"],
    hebrew: "יְהוּדָה",
    transliteration: "Yehudah",
    meaning: "Praise YHWH.",
    segments: [
      { hebrew: "יְהוּ", transliteration: "Yehu", gloss: "from YHWH (Yah)" },
      { hebrew: "דָה", transliteration: "dah", gloss: "from yadah, 'to praise/give thanks'" },
    ],
    language: "hebrew",
    category: "tribe-head",
    personId: "judah",
    firstOccurrence: "Genesis 29:35",
    notes: "Genesis 29:35: 'This time I will praise the LORD.' The messianic tribe.",
  },
  {
    id: "yosef",
    englishName: "Joseph",
    alternateEnglish: ["Yosef"],
    hebrew: "יוֹסֵף",
    transliteration: "Yosef",
    meaning: "May he add — Rachel's prayer for another son.",
    segments: [
      { hebrew: "יוֹ", transliteration: "Yo", gloss: "3rd-person prefix" },
      { hebrew: "סֵף", transliteration: "sef", gloss: "from yasaph, 'to add'" },
    ],
    language: "hebrew",
    category: "tribe-head",
    personId: "joseph",
    firstOccurrence: "Genesis 30:24",
  },
  {
    id: "binyamin",
    englishName: "Benjamin",
    alternateEnglish: ["Binyamin"],
    hebrew: "בִּנְיָמִין",
    transliteration: "Binyamin",
    meaning: "Son of the right hand — Jacob's rename from Ben-oni.",
    segments: [
      { hebrew: "בִּן", transliteration: "Bin", gloss: "from ben, 'son'" },
      { hebrew: "יָמִין", transliteration: "yamin", gloss: "right hand (of favor/strength)" },
    ],
    language: "hebrew",
    category: "tribe-head",
    personId: "benjamin",
    firstOccurrence: "Genesis 35:18",
    notes: "Rachel named him Ben-oni ('son of my sorrow') as she died; Jacob renamed him Benjamin (Gen 35:18).",
  },
  {
    id: "dan",
    englishName: "Dan",
    hebrew: "דָּן",
    transliteration: "Dan",
    meaning: "He judged / vindicated.",
    segments: [
      { hebrew: "דָּן", transliteration: "Dan", gloss: "from din, 'to judge'" },
    ],
    language: "hebrew",
    category: "tribe-head",
    personId: "dan",
    firstOccurrence: "Genesis 30:6",
    notes: "Genesis 30:6: 'God has judged me.'",
  },
  {
    id: "naphtali",
    englishName: "Naphtali",
    hebrew: "נַפְתָּלִי",
    transliteration: "Naphtali",
    meaning: "My wrestling — Rachel's struggle with her sister.",
    segments: [
      { hebrew: "נַפְתָּלִ", transliteration: "Naftali", gloss: "from patal, 'to wrestle/twist'" },
      { hebrew: "י", transliteration: "i", gloss: "1st-person suffix, 'my'" },
    ],
    language: "hebrew",
    category: "tribe-head",
    personId: "naphtali",
    firstOccurrence: "Genesis 30:8",
  },
  {
    id: "gad",
    englishName: "Gad",
    hebrew: "גָּד",
    transliteration: "Gad",
    meaning: "Good fortune / troop.",
    segments: [
      { hebrew: "גָּד", transliteration: "Gad", gloss: "good fortune (one tradition) / troop (another)" },
    ],
    language: "hebrew",
    category: "tribe-head",
    personId: "gad",
    firstOccurrence: "Genesis 30:11",
  },
  {
    id: "asher",
    englishName: "Asher",
    hebrew: "אָשֵׁר",
    transliteration: "Asher",
    meaning: "Happy / blessed.",
    segments: [
      { hebrew: "אָשֵׁר", transliteration: "Asher", gloss: "from ashar, 'to be happy/blessed'" },
    ],
    language: "hebrew",
    category: "tribe-head",
    personId: "asher",
    firstOccurrence: "Genesis 30:13",
    notes: "Genesis 30:13: 'Happy am I! For the daughters will call me blessed.'",
  },
  {
    id: "yissachar",
    englishName: "Issachar",
    alternateEnglish: ["Yissachar"],
    hebrew: "יִשָּׂשכָר",
    transliteration: "Yissachar",
    meaning: "There is reward / a man of hire.",
    segments: [
      { hebrew: "יִשּׂ", transliteration: "Yis", gloss: "from yesh, 'there is'" },
      { hebrew: "ָשכָר", transliteration: "sachar", gloss: "from sakar, 'wages/reward'" },
    ],
    language: "hebrew",
    category: "tribe-head",
    personId: "issachar",
    firstOccurrence: "Genesis 30:18",
  },
  {
    id: "zebulun",
    englishName: "Zebulun",
    hebrew: "זְבוּלוּן",
    transliteration: "Zevulun",
    meaning: "Dwelling / honor.",
    segments: [
      { hebrew: "זְבוּלוּן", transliteration: "Zevulun", gloss: "from zaval, 'to dwell/honor'" },
    ],
    language: "hebrew",
    category: "tribe-head",
    personId: "zebulun",
    firstOccurrence: "Genesis 30:20",
  },

  /* ───── Exodus & wilderness ───── */
  {
    id: "moshe",
    englishName: "Moses",
    alternateEnglish: ["Moshe"],
    hebrew: "מֹשֶׁה",
    transliteration: "Moshe",
    meaning: "Drawn out — from the water.",
    segments: [
      { hebrew: "מֹשֶׁ", transliteration: "Moshe", gloss: "from mashah, 'to draw out'" },
      { hebrew: "ה", transliteration: "h", gloss: "ending" },
    ],
    language: "hebrew",
    category: "leader",
    personId: "moses",
    firstOccurrence: "Exodus 2:10",
    notes: "Exodus 2:10: 'because I drew him out of the water.' May also derive from Egyptian 'msi' ('to give birth, son of'), as in Thutmose, Ramses.",
  },
  {
    id: "aharon",
    englishName: "Aaron",
    alternateEnglish: ["Aharon"],
    hebrew: "אַהֲרֹן",
    transliteration: "Aharon",
    meaning: "Meaning uncertain — possibly 'mountain of strength' or 'enlightened.'",
    segments: [
      { hebrew: "אַהֲ", transliteration: "Aha", gloss: "opening (etymology debated)" },
      { hebrew: "רֹן", transliteration: "ron", gloss: "ending (possibly 'mountain' from har)" },
    ],
    language: "hebrew",
    category: "priest",
    personId: "aaron",
    firstOccurrence: "Exodus 4:14",
    notes: "Etymology genuinely uncertain. May be non-Hebrew (possibly Egyptian) in origin.",
  },
  {
    id: "miryam",
    englishName: "Miriam",
    alternateEnglish: ["Miryam"],
    hebrew: "מִרְיָם",
    transliteration: "Miryam",
    meaning: "Meaning debated — 'bitterness,' 'rebellion,' or 'beloved.'",
    segments: [
      { hebrew: "מִרְ", transliteration: "Mir", gloss: "possibly from mar, 'bitter'" },
      { hebrew: "יָם", transliteration: "yam", gloss: "ending (uncertain — possibly Egyptian 'mry,' 'beloved')" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "miriam",
    firstOccurrence: "Exodus 15:20",
    notes: "Same name as Mary in the New Testament. Etymology genuinely debated.",
  },
  {
    id: "yehoshua",
    englishName: "Joshua",
    alternateEnglish: ["Yehoshua"],
    hebrew: "יְהוֹשֻׁעַ",
    transliteration: "Yehoshua",
    meaning: "YHWH saves.",
    segments: [
      { hebrew: "יְהוֹ", transliteration: "Yeho", gloss: "from YHWH" },
      { hebrew: "שֻׁעַ", transliteration: "shua", gloss: "from yasha, 'to save'" },
    ],
    language: "hebrew",
    category: "leader",
    personId: "joshua",
    firstOccurrence: "Numbers 13:16",
    notes: "Renamed by Moses from Hoshea ('salvation') to Yehoshua ('YHWH is salvation') in Num 13:16. Greek form: Iēsous → Jesus.",
  },

  /* ───── Judges ───── */
  {
    id: "devorah",
    englishName: "Deborah",
    alternateEnglish: ["Devorah"],
    hebrew: "דְּבוֹרָה",
    transliteration: "Devorah",
    meaning: "Bee.",
    segments: [
      { hebrew: "דְּבוֹרָ", transliteration: "Devora", gloss: "from davar (related to honey/bee)" },
      { hebrew: "ה", transliteration: "h", gloss: "feminine ending" },
    ],
    language: "hebrew",
    category: "judge",
    personId: "deborah-judge",
    firstOccurrence: "Judges 4:4",
  },
  {
    id: "gidon",
    englishName: "Gideon",
    alternateEnglish: ["Gid'on"],
    hebrew: "גִּדְעוֹן",
    transliteration: "Gid'on",
    meaning: "Hewer / cutter.",
    segments: [
      { hebrew: "גִּדְ", transliteration: "Gid", gloss: "from gada, 'to cut down/hew'" },
      { hebrew: "עוֹן", transliteration: "on", gloss: "noun-forming suffix" },
    ],
    language: "hebrew",
    category: "judge",
    personId: "gideon",
    firstOccurrence: "Judges 6:11",
    notes: "Fitting: he cut down the Asherah pole of Baal (Judg 6:25-27).",
  },
  {
    id: "shimshon",
    englishName: "Samson",
    alternateEnglish: ["Shimshon"],
    hebrew: "שִׁמְשׁוֹן",
    transliteration: "Shimshon",
    meaning: "Of the sun / sunny.",
    segments: [
      { hebrew: "שִׁמְשׁ", transliteration: "Shimsh", gloss: "from shemesh, 'sun'" },
      { hebrew: "וֹן", transliteration: "on", gloss: "noun-forming suffix" },
    ],
    language: "hebrew",
    category: "judge",
    personId: "samson",
    firstOccurrence: "Judges 13:24",
  },
  {
    id: "shmuel",
    englishName: "Samuel",
    alternateEnglish: ["Shmu'el"],
    hebrew: "שְׁמוּאֵל",
    transliteration: "Shmu'el",
    meaning: "Heard by God / asked of God.",
    segments: [
      { hebrew: "שְׁמוּ", transliteration: "Shmu", gloss: "from shama, 'to hear' (or sha'al, 'to ask')" },
      { hebrew: "אֵל", transliteration: "el", gloss: "God" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "samuel",
    firstOccurrence: "1 Samuel 1:20",
    notes: "1 Sam 1:20: 'I have asked him of the LORD' — the verb sha'al puns on Sha'ul (Saul), whom Samuel will anoint.",
  },

  /* ───── Kings ───── */
  {
    id: "shaul",
    englishName: "Saul",
    alternateEnglish: ["Sha'ul"],
    hebrew: "שָׁאוּל",
    transliteration: "Sha'ul",
    meaning: "Asked for / requested.",
    segments: [
      { hebrew: "שָׁא", transliteration: "Sha", gloss: "from sha'al, 'to ask'" },
      { hebrew: "וּל", transliteration: "ul", gloss: "passive ending" },
    ],
    language: "hebrew",
    category: "king",
    personId: "saul",
    firstOccurrence: "1 Samuel 9:2",
    notes: "Same Hebrew name as the apostle Paul (Saul of Tarsus).",
  },
  {
    id: "david",
    englishName: "David",
    hebrew: "דָּוִד",
    transliteration: "David",
    meaning: "Beloved.",
    segments: [
      { hebrew: "דָּוִד", transliteration: "David", gloss: "from dod, 'beloved'" },
    ],
    language: "hebrew",
    category: "king",
    personId: "david",
    firstOccurrence: "1 Samuel 16:13",
  },
  {
    id: "shlomo",
    englishName: "Solomon",
    alternateEnglish: ["Shlomo"],
    hebrew: "שְׁלֹמֹה",
    transliteration: "Shlomo",
    meaning: "Peaceful — from shalom.",
    segments: [
      { hebrew: "שְׁלֹ", transliteration: "Shlo", gloss: "from shalom, 'peace/wholeness'" },
      { hebrew: "מֹה", transliteration: "mo", gloss: "ending" },
    ],
    language: "hebrew",
    category: "king",
    personId: "solomon",
    firstOccurrence: "2 Samuel 12:24",
  },
  {
    id: "chizkiyahu",
    englishName: "Hezekiah",
    alternateEnglish: ["Chizkiyahu"],
    hebrew: "חִזְקִיָּהוּ",
    transliteration: "Chizkiyahu",
    meaning: "YHWH strengthens.",
    segments: [
      { hebrew: "חִזְקִ", transliteration: "Chizki", gloss: "from chazaq, 'to be strong/strengthen'" },
      { hebrew: "יָּהוּ", transliteration: "yahu", gloss: "short for YHWH" },
    ],
    language: "hebrew",
    category: "king",
    personId: "hezekiah",
    firstOccurrence: "2 Kings 18:1",
  },
  {
    id: "yoshiyahu",
    englishName: "Josiah",
    alternateEnglish: ["Yoshiyahu"],
    hebrew: "יֹאשִׁיָּהוּ",
    transliteration: "Yoshiyahu",
    meaning: "YHWH supports / heals.",
    segments: [
      { hebrew: "יֹאשִׁ", transliteration: "Yoshi", gloss: "from a root meaning 'support/give'" },
      { hebrew: "יָּהוּ", transliteration: "yahu", gloss: "short for YHWH" },
    ],
    language: "hebrew",
    category: "king",
    personId: "josiah",
    firstOccurrence: "1 Kings 13:2",
  },

  /* ───── Prophets ───── */
  {
    id: "eliyahu",
    englishName: "Elijah",
    alternateEnglish: ["Eliyahu"],
    hebrew: "אֵלִיָּהוּ",
    transliteration: "Eliyahu",
    meaning: "My God is YHWH.",
    segments: [
      { hebrew: "אֵלִ", transliteration: "Eli", gloss: "El + 1st-person suffix, 'my God'" },
      { hebrew: "יָּהוּ", transliteration: "yahu", gloss: "short for YHWH" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "elijah",
    firstOccurrence: "1 Kings 17:1",
    notes: "His very name is the manifesto he proclaimed against Baal worship.",
  },
  {
    id: "elisha",
    englishName: "Elisha",
    hebrew: "אֱלִישָׁע",
    transliteration: "Elisha",
    meaning: "My God is salvation.",
    segments: [
      { hebrew: "אֱלִי", transliteration: "Eli", gloss: "El + 1st-person suffix, 'my God'" },
      { hebrew: "שָׁע", transliteration: "sha", gloss: "from yasha, 'to save'" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "elisha",
    firstOccurrence: "1 Kings 19:16",
  },
  {
    id: "yeshayahu",
    englishName: "Isaiah",
    alternateEnglish: ["Yeshayahu"],
    hebrew: "יְשַׁעְיָהוּ",
    transliteration: "Yeshayahu",
    meaning: "YHWH is salvation / YHWH saves.",
    segments: [
      { hebrew: "יְשַׁעְ", transliteration: "Yesha", gloss: "from yasha, 'salvation/to save'" },
      { hebrew: "יָהוּ", transliteration: "yahu", gloss: "short for YHWH" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "isaiah",
    firstOccurrence: "Isaiah 1:1",
  },
  {
    id: "yirmeyahu",
    englishName: "Jeremiah",
    alternateEnglish: ["Yirmeyahu"],
    hebrew: "יִרְמְיָהוּ",
    transliteration: "Yirmeyahu",
    meaning: "YHWH raises up / appoints.",
    segments: [
      { hebrew: "יִרְמְ", transliteration: "Yirme", gloss: "from rum, 'to be high/raise up'" },
      { hebrew: "יָהוּ", transliteration: "yahu", gloss: "short for YHWH" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "jeremiah",
    firstOccurrence: "Jeremiah 1:1",
  },
  {
    id: "yechezkel",
    englishName: "Ezekiel",
    alternateEnglish: ["Yechezkel"],
    hebrew: "יְחֶזְקֵאל",
    transliteration: "Yechezkel",
    meaning: "God strengthens.",
    segments: [
      { hebrew: "יְחֶזְקֵ", transliteration: "Yechezke", gloss: "from chazaq, 'to be strong/strengthen'" },
      { hebrew: "אל", transliteration: "el", gloss: "God" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "ezekiel",
    firstOccurrence: "Ezekiel 1:3",
  },
  {
    id: "daniel",
    englishName: "Daniel",
    hebrew: "דָּנִיֵּאל",
    transliteration: "Daniel",
    meaning: "God is my judge.",
    segments: [
      { hebrew: "דָּנִ", transliteration: "Dan", gloss: "from din, 'to judge'" },
      { hebrew: "יֵּ", transliteration: "i", gloss: "1st-person suffix, 'my'" },
      { hebrew: "אל", transliteration: "el", gloss: "God" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "daniel",
    firstOccurrence: "Daniel 1:6",
  },
  {
    id: "hoshea",
    englishName: "Hosea",
    alternateEnglish: ["Hoshea"],
    hebrew: "הוֹשֵׁעַ",
    transliteration: "Hoshea",
    meaning: "Salvation.",
    segments: [
      { hebrew: "הוֹ", transliteration: "Ho", gloss: "infinitive-construct prefix" },
      { hebrew: "שֵׁעַ", transliteration: "shea", gloss: "from yasha, 'to save'" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "hosea",
    firstOccurrence: "Hosea 1:1",
    notes: "Same root as Yehoshua (Joshua). Hoshea was also Joshua's original name (Num 13:8).",
  },
  {
    id: "yoel",
    englishName: "Joel",
    alternateEnglish: ["Yo'el"],
    hebrew: "יוֹאֵל",
    transliteration: "Yo'el",
    meaning: "YHWH is God.",
    segments: [
      { hebrew: "יוֹ", transliteration: "Yo", gloss: "short for YHWH" },
      { hebrew: "אֵל", transliteration: "el", gloss: "God" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "joel",
    firstOccurrence: "Joel 1:1",
    notes: "The same confession as Elijah ('My God is YHWH'), just inverted: YHWH is [the true] God.",
  },
  {
    id: "amos",
    englishName: "Amos",
    hebrew: "עָמוֹס",
    transliteration: "Amos",
    meaning: "Burden-bearer.",
    segments: [
      { hebrew: "עָמוֹס", transliteration: "Amos", gloss: "from amas, 'to load/carry a burden'" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "amos",
    firstOccurrence: "Amos 1:1",
  },
  {
    id: "ovadyah",
    englishName: "Obadiah",
    alternateEnglish: ["Ovadyah"],
    hebrew: "עֹבַדְיָה",
    transliteration: "Ovadyah",
    meaning: "Servant of YHWH.",
    segments: [
      { hebrew: "עֹבַדְ", transliteration: "Ovad", gloss: "from eved, 'servant'" },
      { hebrew: "יָה", transliteration: "yah", gloss: "short for YHWH" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "obadiah",
    firstOccurrence: "Obadiah 1:1",
  },
  {
    id: "yonah",
    englishName: "Jonah",
    alternateEnglish: ["Yonah"],
    hebrew: "יוֹנָה",
    transliteration: "Yonah",
    meaning: "Dove.",
    segments: [
      { hebrew: "יוֹנָ", transliteration: "Yona", gloss: "dove" },
      { hebrew: "ה", transliteration: "h", gloss: "ending" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "jonah",
    firstOccurrence: "Jonah 1:1",
  },
  {
    id: "mikhah",
    englishName: "Micah",
    alternateEnglish: ["Mikhah"],
    hebrew: "מִיכָה",
    transliteration: "Mikhah",
    meaning: "Who is like [YHWH]? — short form of Mikha-el.",
    segments: [
      { hebrew: "מִי", transliteration: "Mi", gloss: "interrogative 'who?'" },
      { hebrew: "כָה", transliteration: "khah", gloss: "from ka, 'like'" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "micah",
    firstOccurrence: "Micah 1:1",
    notes: "The implicit answer: no one. Longer form Mikha-el ('who is like God?') is the archangel's name.",
  },
  {
    id: "nachum",
    englishName: "Nahum",
    alternateEnglish: ["Nachum"],
    hebrew: "נַחוּם",
    transliteration: "Nachum",
    meaning: "Comforted / consoled.",
    segments: [
      { hebrew: "נַחוּם", transliteration: "Nachum", gloss: "from nacham, 'to comfort'" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "nahum",
    firstOccurrence: "Nahum 1:1",
  },
  {
    id: "chavaqquq",
    englishName: "Habakkuk",
    alternateEnglish: ["Chavaqquq"],
    hebrew: "חֲבַקּוּק",
    transliteration: "Chavaqquq",
    meaning: "Embrace / clinging.",
    segments: [
      { hebrew: "חֲבַקּוּק", transliteration: "Chavaqquq", gloss: "from chavaq, 'to embrace'" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "habakkuk",
    firstOccurrence: "Habakkuk 1:1",
  },
  {
    id: "tsefanyah",
    englishName: "Zephaniah",
    alternateEnglish: ["Tsefanyah"],
    hebrew: "צְפַנְיָה",
    transliteration: "Tsefanyah",
    meaning: "YHWH hides / protects.",
    segments: [
      { hebrew: "צְפַנְ", transliteration: "Tsefan", gloss: "from tsafan, 'to hide/protect/treasure up'" },
      { hebrew: "יָה", transliteration: "yah", gloss: "short for YHWH" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "zephaniah",
    firstOccurrence: "Zephaniah 1:1",
  },
  {
    id: "chaggai",
    englishName: "Haggai",
    alternateEnglish: ["Chaggai"],
    hebrew: "חַגַּי",
    transliteration: "Chaggai",
    meaning: "Festive — 'my feast.'",
    segments: [
      { hebrew: "חַגַּ", transliteration: "Chagga", gloss: "from chag, 'feast/festival'" },
      { hebrew: "י", transliteration: "i", gloss: "1st-person suffix, 'my'" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "haggai",
    firstOccurrence: "Haggai 1:1",
  },
  {
    id: "zekharyah",
    englishName: "Zechariah",
    alternateEnglish: ["Zekharyah"],
    hebrew: "זְכַרְיָה",
    transliteration: "Zekharyah",
    meaning: "YHWH remembers.",
    segments: [
      { hebrew: "זְכַרְ", transliteration: "Zekhar", gloss: "from zakhar, 'to remember'" },
      { hebrew: "יָה", transliteration: "yah", gloss: "short for YHWH" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "zechariah-prophet",
    firstOccurrence: "Zechariah 1:1",
  },
  {
    id: "malakhi",
    englishName: "Malachi",
    alternateEnglish: ["Mal'akhi"],
    hebrew: "מַלְאָכִי",
    transliteration: "Mal'akhi",
    meaning: "My messenger.",
    segments: [
      { hebrew: "מַלְאָכִ", transliteration: "Mal'akhi", gloss: "from mal'akh, 'messenger/angel'" },
      { hebrew: "י", transliteration: "i", gloss: "1st-person suffix, 'my'" },
    ],
    language: "hebrew",
    category: "prophet",
    personId: "malachi",
    firstOccurrence: "Malachi 1:1",
    notes: "The last prophet of the Hebrew Bible — his name a one-word prophecy of the messenger to come (Mal 3:1).",
  },

  /* ───── Post-exile leaders ───── */
  {
    id: "ezra",
    englishName: "Ezra",
    hebrew: "עֶזְרָא",
    transliteration: "Ezra",
    meaning: "Help — short for 'YHWH helps' (Azariah).",
    segments: [
      { hebrew: "עֶזְרָ", transliteration: "Ezra", gloss: "from azar, 'to help'" },
      { hebrew: "א", transliteration: "a", gloss: "ending" },
    ],
    language: "hebrew",
    category: "leader",
    personId: "ezra",
    firstOccurrence: "Ezra 7:1",
  },
  {
    id: "nechemyah",
    englishName: "Nehemiah",
    alternateEnglish: ["Nechemyah"],
    hebrew: "נְחֶמְיָה",
    transliteration: "Nechemyah",
    meaning: "YHWH comforts.",
    segments: [
      { hebrew: "נְחֶמְ", transliteration: "Nechem", gloss: "from nacham, 'to comfort'" },
      { hebrew: "יָה", transliteration: "yah", gloss: "short for YHWH" },
    ],
    language: "hebrew",
    category: "leader",
    personId: "nehemiah",
    firstOccurrence: "Nehemiah 1:1",
  },

  /* ───── Messianic-line names (NT) ───── */
  {
    id: "yeshua",
    englishName: "Jesus",
    alternateEnglish: ["Yeshua", "Yehoshua"],
    hebrew: "יֵשׁוּעַ",
    transliteration: "Yeshua",
    meaning: "YHWH saves — short form of Yehoshua.",
    segments: [
      { hebrew: "יֵ", transliteration: "Ye", gloss: "from YHWH" },
      { hebrew: "שׁוּעַ", transliteration: "shua", gloss: "from yasha, 'to save'" },
    ],
    language: "hebrew",
    category: "messianic",
    personId: "jesus-of-nazareth",
    firstOccurrence: "Matthew 1:21",
    notes: "Matthew 1:21: 'You shall call his name Jesus, for he will save his people from their sins.' The Greek 'Iēsous' transliterates the post-exilic short form of Joshua.",
  },
  {
    id: "miryam-mary",
    englishName: "Mary",
    alternateEnglish: ["Maryam", "Miryam"],
    hebrew: "מִרְיָם",
    transliteration: "Miryam",
    meaning: "Same as Miriam — bitterness / beloved (debated).",
    segments: [
      { hebrew: "מִרְ", transliteration: "Mir", gloss: "possibly from mar, 'bitter'" },
      { hebrew: "יָם", transliteration: "yam", gloss: "uncertain ending" },
    ],
    language: "hebrew",
    category: "messianic",
    personId: "mary-mother-of-jesus",
    firstOccurrence: "Matthew 1:16",
    notes: "Mary of Nazareth bears the same name as Moses' sister.",
  },
  {
    id: "yosef-nt",
    englishName: "Joseph",
    alternateEnglish: ["Yosef"],
    hebrew: "יוֹסֵף",
    transliteration: "Yosef",
    meaning: "May he add — same as the patriarch.",
    segments: [
      { hebrew: "יוֹ", transliteration: "Yo", gloss: "3rd-person prefix" },
      { hebrew: "סֵף", transliteration: "sef", gloss: "from yasaph, 'to add'" },
    ],
    language: "hebrew",
    category: "messianic",
    personId: "joseph-husband-of-mary",
    firstOccurrence: "Matthew 1:16",
  },
  {
    id: "yochanan",
    englishName: "John",
    alternateEnglish: ["Yochanan"],
    hebrew: "יוֹחָנָן",
    transliteration: "Yochanan",
    meaning: "YHWH is gracious.",
    segments: [
      { hebrew: "יוֹ", transliteration: "Yo", gloss: "short for YHWH" },
      { hebrew: "חָנָן", transliteration: "chanan", gloss: "from chanan, 'to be gracious'" },
    ],
    language: "hebrew",
    category: "apostle",
    personId: "john-apostle",
    firstOccurrence: "Matthew 3:1",
    notes: "Born to a barren mother (Elizabeth) — a name that confesses unearned grace.",
  },
  {
    id: "mattityahu",
    englishName: "Matthew",
    alternateEnglish: ["Mattityahu"],
    hebrew: "מַתִּתְיָהוּ",
    transliteration: "Mattityahu",
    meaning: "Gift of YHWH.",
    segments: [
      { hebrew: "מַתִּתְ", transliteration: "Mattit", gloss: "from mattan, 'gift'" },
      { hebrew: "יָהוּ", transliteration: "yahu", gloss: "short for YHWH" },
    ],
    language: "hebrew",
    category: "apostle",
    personId: "matthew-apostle",
    firstOccurrence: "Matthew 9:9",
  },
  {
    id: "kephas",
    englishName: "Cephas",
    alternateEnglish: ["Kepha", "Peter"],
    hebrew: "כֵּיפָא",
    transliteration: "Kepha",
    meaning: "Rock — Aramaic; translated to Greek as Petros (Peter).",
    segments: [
      { hebrew: "כֵּיפָא", transliteration: "Kepha", gloss: "rock, stone (Aramaic)" },
    ],
    language: "aramaic",
    category: "apostle",
    personId: "peter",
    firstOccurrence: "John 1:42",
    notes: "Jesus renamed Simon as Kepha (Aramaic); the Greek Gospels render this as Petros, which English brings over as Peter.",
  },
  {
    id: "shaul-paul",
    englishName: "Saul (Paul)",
    alternateEnglish: ["Sha'ul"],
    hebrew: "שָׁאוּל",
    transliteration: "Sha'ul",
    meaning: "Asked for — the apostle's Hebrew name before his Roman Paulus.",
    segments: [
      { hebrew: "שָׁא", transliteration: "Sha", gloss: "from sha'al, 'to ask'" },
      { hebrew: "וּל", transliteration: "ul", gloss: "passive ending" },
    ],
    language: "hebrew",
    category: "apostle",
    personId: "paul",
    firstOccurrence: "Acts 7:58",
    notes: "Same Hebrew name as Israel's first king. Acts 13:9 marks the shift to his Roman name Paulus on the Gentile mission.",
  },
];
