import type { Person } from "./types";

export const people: Person[] = [
  {
    id: "adam",
    name: "Adam",
    gender: "male",
    alternateNames: ["The Man"],
    era: "antediluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description:
      "First human, formed from the dust of the ground; placed in Eden with his wife Eve. After the fall, he became the progenitor of all humanity through his sons Cain, Abel, and Seth.",
    lifespanYears: 930,
    ageAtDeathRef: "Genesis 5:5",
    scriptureReferences: [
      "Genesis 1:26-27",
      "Genesis 2:7",
      "Genesis 5:3-5",
      "1 Chronicles 1:1",
      "Luke 3:38",
      "Romans 5:14",
      "1 Corinthians 15:22",
      "1 Corinthians 15:45",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "eve",
    name: "Eve",
    gender: "female",
    alternateNames: ["Chavah", "Hawwah", "Mother of all living"],
    era: "antediluvian",
    roles: ["matriarch"],
    description:
      "The first woman, formed from Adam's side; named 'Eve' because she would be the mother of all living. Mother of Cain, Abel, and Seth, with other unnamed sons and daughters.",
    scriptureReferences: [
      "Genesis 2:21-23",
      "Genesis 3:20",
      "Genesis 4:1",
      "Genesis 4:25",
      "2 Corinthians 11:3",
      "1 Timothy 2:13",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "cain",
    name: "Cain",
    gender: "male",
    era: "antediluvian",
    description:
      "Firstborn son of Adam and Eve; a tiller of the ground. Murdered his brother Abel in jealousy after his offering was rejected, then was marked and exiled by Yahweh. Founded a city named after his son Enoch.",
    scriptureReferences: [
      "Genesis 4:1-17",
      "Hebrews 11:4",
      "1 John 3:12",
      "Jude 1:11",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "abel",
    name: "Abel",
    gender: "male",
    era: "antediluvian",
    description:
      "Second son of Adam and Eve; a keeper of sheep. His offering was accepted by Yahweh; murdered by his brother Cain, becoming the first martyr.",
    scriptureReferences: [
      "Genesis 4:2-10",
      "Matthew 23:35",
      "Luke 11:51",
      "Hebrews 11:4",
      "Hebrews 12:24",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "seth",
    name: "Seth",
    gender: "male",
    era: "antediluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description:
      "Third named son of Adam and Eve, born after Abel's death; the line through whom the godly seed continued. Father of Enosh.",
    lifespanYears: 912,
    ageAtDeathRef: "Genesis 5:8",
    scriptureReferences: ["Genesis 4:25-26", "Genesis 5:3-8", "1 Chronicles 1:1", "Luke 3:38"],
    confidenceLevel: "explicit",
  },
  {
    id: "enoch-of-cain",
    name: "Enoch (son of Cain)",
    gender: "male",
    alternateNames: ["Hanok"],
    era: "antediluvian",
    description:
      "Son of Cain, after whom Cain named the first city built by humanity. Distinct from the later Sethite Enoch who walked with God.",
    scriptureReferences: ["Genesis 4:17-18"],
    confidenceLevel: "explicit",
  },
  {
    id: "irad",
    name: "Irad",
    gender: "male",
    era: "antediluvian",
    description: "Son of Cain's son Enoch; second generation of the Cainite line.",
    scriptureReferences: ["Genesis 4:18"],
    confidenceLevel: "explicit",
  },
  {
    id: "mehujael",
    name: "Mehujael",
    gender: "male",
    era: "antediluvian",
    description: "Third generation of the Cainite line, son of Irad and father of Methushael.",
    scriptureReferences: ["Genesis 4:18"],
    confidenceLevel: "explicit",
  },
  {
    id: "methushael",
    name: "Methushael",
    gender: "male",
    era: "antediluvian",
    description: "Fourth generation of the Cainite line, father of Lamech.",
    scriptureReferences: ["Genesis 4:18"],
    confidenceLevel: "explicit",
  },
  {
    id: "lamech-of-cain",
    name: "Lamech (Cainite)",
    gender: "male",
    era: "antediluvian",
    description:
      "Fifth generation of the Cainite line; the first recorded polygamist (married Adah and Zillah). Boasted to his wives of killing a man for wounding him. Distinct from the later Sethite Lamech, father of Noah.",
    scriptureReferences: ["Genesis 4:18-24"],
    confidenceLevel: "explicit",
  },
  {
    id: "adah",
    name: "Adah",
    gender: "female",
    era: "antediluvian",
    description:
      "First wife of the Cainite Lamech; mother of Jabal (ancestor of nomadic herdsmen) and Jubal (father of musicians).",
    scriptureReferences: ["Genesis 4:19-21"],
    confidenceLevel: "explicit",
  },
  {
    id: "zillah",
    name: "Zillah",
    gender: "female",
    era: "antediluvian",
    description:
      "Second wife of the Cainite Lamech; mother of Tubal-Cain (forger of bronze and iron) and Naamah.",
    scriptureReferences: ["Genesis 4:19", "Genesis 4:22-23"],
    confidenceLevel: "explicit",
  },
  {
    id: "jabal",
    name: "Jabal",
    gender: "male",
    era: "antediluvian",
    description:
      "Son of Cainite Lamech and Adah; described as the ancestor of those who dwell in tents and have livestock.",
    scriptureReferences: ["Genesis 4:20"],
    confidenceLevel: "explicit",
  },
  {
    id: "jubal",
    name: "Jubal",
    gender: "male",
    era: "antediluvian",
    description:
      "Son of Cainite Lamech and Adah; described as the ancestor of all who play the lyre and pipe.",
    scriptureReferences: ["Genesis 4:21"],
    confidenceLevel: "explicit",
  },
  {
    id: "tubal-cain",
    name: "Tubal-Cain",
    gender: "male",
    era: "antediluvian",
    description: "Son of Cainite Lamech and Zillah; forger of all instruments of bronze and iron.",
    scriptureReferences: ["Genesis 4:22"],
    confidenceLevel: "explicit",
  },
  {
    id: "naamah",
    name: "Naamah (sister of Tubal-Cain)",
    gender: "female",
    era: "antediluvian",
    description:
      "Daughter of Cainite Lamech and Zillah; named without further detail. Distinct from later women of the same name (e.g. Solomon's Ammonite wife).",
    scriptureReferences: ["Genesis 4:22"],
    confidenceLevel: "explicit",
  },
  {
    id: "enosh",
    name: "Enosh",
    gender: "male",
    alternateNames: ["Enos"],
    era: "antediluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description:
      "Son of Seth; in his days people began to call upon the name of Yahweh. Father of Kenan.",
    lifespanYears: 905,
    ageAtDeathRef: "Genesis 5:11",
    scriptureReferences: ["Genesis 4:26", "Genesis 5:6-11", "1 Chronicles 1:1", "Luke 3:38"],
    confidenceLevel: "explicit",
  },
  {
    id: "kenan",
    name: "Kenan",
    gender: "male",
    alternateNames: ["Cainan"],
    era: "antediluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description: "Son of Enosh, father of Mahalalel.",
    lifespanYears: 910,
    ageAtDeathRef: "Genesis 5:14",
    scriptureReferences: ["Genesis 5:9-14", "1 Chronicles 1:2", "Luke 3:37"],
    confidenceLevel: "explicit",
  },
  {
    id: "mahalalel",
    name: "Mahalalel",
    gender: "male",
    alternateNames: ["Maleleel"],
    era: "antediluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description: "Son of Kenan, father of Jared.",
    lifespanYears: 895,
    ageAtDeathRef: "Genesis 5:17",
    scriptureReferences: ["Genesis 5:12-17", "1 Chronicles 1:2", "Luke 3:37"],
    confidenceLevel: "explicit",
  },
  {
    id: "jared",
    name: "Jared",
    gender: "male",
    era: "antediluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description: "Son of Mahalalel, father of Enoch.",
    lifespanYears: 962,
    ageAtDeathRef: "Genesis 5:20",
    scriptureReferences: ["Genesis 5:15-20", "1 Chronicles 1:2", "Luke 3:37"],
    confidenceLevel: "explicit",
  },
  {
    id: "enoch",
    name: "Enoch",
    gender: "male",
    alternateNames: ["Henoch"],
    era: "antediluvian",
    roles: ["patriarch", "prophet", "ancestor-of-christ"],
    description:
      "Seventh from Adam through the Sethite line; 'walked with God', and after 365 years 'was not, for God took him' — the only antediluvian who did not die. Father of Methuselah. Distinct from Cain's son Enoch.",
    lifespanYears: 365,
    ageAtDeathRef: "Genesis 5:23",
    scriptureReferences: [
      "Genesis 5:18-24",
      "1 Chronicles 1:3",
      "Luke 3:37",
      "Hebrews 11:5",
      "Jude 1:14-15",
    ],
    confidenceLevel: "explicit",
    notes:
      "Hebrews 11:5 confirms Enoch was translated without seeing death. The Book of 1 Enoch is pseudepigraphal and not part of the protestant or catholic canon (though it is in the Ethiopian Orthodox canon).",
  },
  {
    id: "methuselah",
    name: "Methuselah",
    gender: "male",
    era: "antediluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description:
      "Son of Enoch, longest-lived person recorded in scripture (969 years). Died in the year of the Flood per the chronology of Genesis 5 + 7:6.",
    lifespanYears: 969,
    ageAtDeathRef: "Genesis 5:27",
    scriptureReferences: ["Genesis 5:21-27", "1 Chronicles 1:3", "Luke 3:37"],
    confidenceLevel: "explicit",
  },
  {
    id: "lamech",
    name: "Lamech",
    gender: "male",
    era: "antediluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description:
      "Son of Methuselah; father of Noah, whom he prophetically named ('this one will give us comfort'). Distinct from the Cainite Lamech.",
    lifespanYears: 777,
    ageAtDeathRef: "Genesis 5:31",
    scriptureReferences: ["Genesis 5:25-31", "1 Chronicles 1:3", "Luke 3:36"],
    confidenceLevel: "explicit",
  },
  {
    id: "noah",
    name: "Noah",
    gender: "male",
    era: "antediluvian",
    roles: ["patriarch", "prophet", "ancestor-of-christ"],
    description:
      "Tenth from Adam; found favor in Yahweh's eyes amid universal corruption. Built the ark by divine command, preserving his family and the animal kinds through the Flood. Through his three sons Shem, Ham, and Japheth, all post-flood humanity descends.",
    lifespanYears: 950,
    ageAtDeathRef: "Genesis 9:29",
    scriptureReferences: [
      "Genesis 5:28-32",
      "Genesis 6-9",
      "1 Chronicles 1:4",
      "Luke 3:36",
      "Hebrews 11:7",
      "1 Peter 3:20",
      "2 Peter 2:5",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "shem",
    name: "Shem",
    gender: "male",
    era: "postdiluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description:
      "Son of Noah; ancestor of the Semitic peoples and of the line that culminates in Abraham. Lived 600 years and saw nine generations of his descendants.",
    lifespanYears: 600,
    ageAtDeathRef: "Genesis 11:11",
    scriptureReferences: [
      "Genesis 5:32",
      "Genesis 9:18-27",
      "Genesis 10:21-31",
      "Genesis 11:10-11",
      "1 Chronicles 1:4",
      "1 Chronicles 1:17-27",
      "Luke 3:36",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "ham",
    name: "Ham",
    gender: "male",
    era: "postdiluvian",
    description:
      "Son of Noah; father of Cush, Mizraim (Egypt), Put, and Canaan. Saw his father's nakedness, prompting Noah's curse on Ham's son Canaan.",
    scriptureReferences: [
      "Genesis 5:32",
      "Genesis 9:18-25",
      "Genesis 10:6-20",
      "1 Chronicles 1:4",
      "1 Chronicles 1:8-16",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "japheth",
    name: "Japheth",
    gender: "male",
    era: "postdiluvian",
    description:
      "Son of Noah; ancestor of the peoples spread across the coastlands (cf. Genesis 10:5). Listed first by birth-order in some passages, third in the Table of Nations.",
    scriptureReferences: [
      "Genesis 5:32",
      "Genesis 9:18-27",
      "Genesis 10:1-5",
      "1 Chronicles 1:4-7",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "arphaxad",
    name: "Arphaxad",
    gender: "male",
    alternateNames: ["Arpachshad", "Arphachshad"],
    era: "postdiluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description:
      "Son of Shem, born two years after the Flood. Father of Shelah (per the Masoretic text) or of Cainan (per the Septuagint and Luke 3:36).",
    lifespanYears: 438,
    ageAtDeathRef: "Genesis 11:13",
    scriptureReferences: [
      "Genesis 10:22",
      "Genesis 11:10-13",
      "1 Chronicles 1:17-18",
      "Luke 3:36",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "cainan-lxx",
    name: "Cainan (son of Arphaxad)",
    gender: "male",
    alternateNames: ["Kenan (Septuagint)"],
    era: "postdiluvian",
    roles: ["ancestor-of-christ"],
    description:
      "A figure attested in the Septuagint (Genesis 11:13 LXX) and in Luke 3:36 between Arphaxad and Shelah. Absent from the Masoretic Hebrew text and from 1 Chronicles 1:18 MT. Distinct from the earlier Sethite Kenan, son of Enosh.",
    scriptureReferences: ["Luke 3:36"],
    confidenceLevel: "debated",
    traditionTags: ["septuagint", "lukan-genealogy"],
    notes:
      "Present in the Septuagint and in the New Testament Lukan genealogy; absent from the Hebrew Masoretic Text. Some manuscript traditions of the LXX also vary on his inclusion. Stored as a separate person so that Masoretic and Lukan/Septuagint genealogies can both be represented faithfully.",
  },
  {
    id: "shelah",
    name: "Shelah",
    gender: "male",
    alternateNames: ["Salah", "Sala"],
    era: "postdiluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description: "Son of Arphaxad (MT) or of Cainan (LXX/Luke); father of Eber.",
    lifespanYears: 433,
    ageAtDeathRef: "Genesis 11:15",
    scriptureReferences: [
      "Genesis 10:24",
      "Genesis 11:12-15",
      "1 Chronicles 1:18-24",
      "Luke 3:35",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "eber",
    name: "Eber",
    gender: "male",
    alternateNames: ["Heber"],
    era: "postdiluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description:
      "Son of Shelah; father of Peleg and Joktan. Traditionally linked to the name 'Hebrew' as the eponymous ancestor of the Hebrews.",
    lifespanYears: 464,
    ageAtDeathRef: "Genesis 11:17",
    scriptureReferences: [
      "Genesis 10:24-25",
      "Genesis 11:14-17",
      "1 Chronicles 1:18-25",
      "Luke 3:35",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "peleg",
    name: "Peleg",
    gender: "male",
    alternateNames: ["Phalec"],
    era: "postdiluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description:
      "Son of Eber; named because 'in his days the earth was divided' — traditionally connected to the dispersion at Babel.",
    lifespanYears: 239,
    ageAtDeathRef: "Genesis 11:19",
    scriptureReferences: [
      "Genesis 10:25",
      "Genesis 11:16-19",
      "1 Chronicles 1:19",
      "1 Chronicles 1:25",
      "Luke 3:35",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "reu",
    name: "Reu",
    gender: "male",
    alternateNames: ["Ragau"],
    era: "postdiluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description: "Son of Peleg; father of Serug.",
    lifespanYears: 239,
    ageAtDeathRef: "Genesis 11:21",
    scriptureReferences: ["Genesis 11:18-21", "1 Chronicles 1:25", "Luke 3:35"],
    confidenceLevel: "explicit",
  },
  {
    id: "serug",
    name: "Serug",
    gender: "male",
    alternateNames: ["Saruch"],
    era: "postdiluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description: "Son of Reu; father of Nahor (the elder).",
    lifespanYears: 230,
    ageAtDeathRef: "Genesis 11:23",
    scriptureReferences: ["Genesis 11:20-23", "1 Chronicles 1:26", "Luke 3:35"],
    confidenceLevel: "explicit",
  },
  {
    id: "nahor-elder",
    name: "Nahor (grandfather of Abraham)",
    gender: "male",
    era: "postdiluvian",
    roles: ["patriarch", "ancestor-of-christ"],
    description:
      "Son of Serug; father of Terah and grandfather of Abraham. Distinct from his namesake grandson, Abraham's brother.",
    lifespanYears: 148,
    ageAtDeathRef: "Genesis 11:25",
    scriptureReferences: ["Genesis 11:22-25", "1 Chronicles 1:26", "Luke 3:34"],
    confidenceLevel: "explicit",
  },
  {
    id: "terah",
    name: "Terah",
    gender: "male",
    alternateNames: ["Thara"],
    era: "patriarchal",
    roles: ["patriarch", "ancestor-of-christ"],
    description:
      "Son of Nahor; father of Abram, Nahor (the younger), and Haran. Departed Ur of the Chaldeans for Canaan but settled in Haran, where he died at 205. According to Joshua 24:2, served other gods.",
    lifespanYears: 205,
    ageAtDeathRef: "Genesis 11:32",
    scriptureReferences: [
      "Genesis 11:24-32",
      "Joshua 24:2",
      "1 Chronicles 1:26",
      "Luke 3:34",
    ],
    confidenceLevel: "explicit",
    notes:
      "Per Genesis 20:12, Sarah was Abraham's half-sister 'the daughter of my father, but not the daughter of my mother', implying Terah had at least two wives.",
  },
  {
    id: "abraham",
    name: "Abraham",
    gender: "male",
    alternateNames: ["Abram", "Father of a multitude"],
    era: "patriarchal",
    roles: ["patriarch", "ancestor-of-christ"],
    description:
      "Originally Abram of Ur; called by Yahweh to leave his homeland and become a great nation. Renamed Abraham ('father of a multitude') at the institution of circumcision. Father of Ishmael by Hagar and of Isaac by Sarah, through whom the covenant line continued.",
    lifespanYears: 175,
    ageAtDeathRef: "Genesis 25:7",
    scriptureReferences: [
      "Genesis 11:26-25:11",
      "Genesis 17:5",
      "1 Chronicles 1:27-28",
      "Matthew 1:1-2",
      "Luke 3:34",
      "Romans 4",
      "Galatians 3",
      "Hebrews 11:8-19",
      "James 2:21-23",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "nahor",
    name: "Nahor (brother of Abraham)",
    gender: "male",
    era: "patriarchal",
    description:
      "Son of Terah and brother of Abraham; married Milcah, the daughter of his other brother Haran. Father of twelve sons including Bethuel, the grandfather of Rebekah and Laban. Distinct from his grandfather of the same name.",
    scriptureReferences: ["Genesis 11:26-29", "Genesis 22:20-24", "Genesis 24:15"],
    confidenceLevel: "explicit",
  },
  {
    id: "haran",
    name: "Haran",
    gender: "male",
    era: "patriarchal",
    description:
      "Son of Terah and brother of Abraham; father of Lot, Milcah, and Iscah. Died in Ur of the Chaldeans before his father. Not to be confused with the city of Haran where Terah later settled.",
    scriptureReferences: ["Genesis 11:26-31"],
    confidenceLevel: "explicit",
  },
  {
    id: "sarah",
    name: "Sarah",
    gender: "female",
    alternateNames: ["Sarai", "Princess"],
    era: "patriarchal",
    roles: ["matriarch", "ancestor-of-christ"],
    description:
      "Wife and half-sister of Abraham (same father, different mother). Originally Sarai; renamed Sarah ('princess') at age 90 with the promise of Isaac. Mother of Isaac. The only woman whose age at death is recorded in the Hebrew Bible (127 years).",
    lifespanYears: 127,
    ageAtDeathRef: "Genesis 23:1",
    scriptureReferences: [
      "Genesis 11:29-31",
      "Genesis 17:15-21",
      "Genesis 18",
      "Genesis 20:12",
      "Genesis 21",
      "Genesis 23",
      "Isaiah 51:2",
      "Romans 4:19",
      "Romans 9:9",
      "Hebrews 11:11",
      "1 Peter 3:6",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "lot",
    name: "Lot",
    gender: "male",
    era: "patriarchal",
    description:
      "Son of Haran and nephew of Abraham; accompanied Abraham from Ur to Canaan. Settled in Sodom and was rescued from its destruction. Through his daughters, ancestor of Moab and Ammon.",
    scriptureReferences: [
      "Genesis 11:27-31",
      "Genesis 12:4-5",
      "Genesis 13",
      "Genesis 14",
      "Genesis 19",
      "Deuteronomy 2:9",
      "Deuteronomy 2:19",
      "2 Peter 2:7-8",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "milcah",
    name: "Milcah",
    gender: "female",
    era: "patriarchal",
    description:
      "Daughter of Haran and sister of Lot and Iscah; wife of her uncle Nahor and grandmother of Rebekah.",
    scriptureReferences: ["Genesis 11:29", "Genesis 22:20-23", "Genesis 24:15", "Genesis 24:24"],
    confidenceLevel: "explicit",
  },
  {
    id: "iscah",
    name: "Iscah",
    gender: "female",
    era: "patriarchal",
    description:
      "Daughter of Haran; mentioned only once. Some Jewish traditions identify her with Sarah, but the biblical text does not state this and Genesis 20:12 specifies Sarah's father as Terah, not Haran.",
    scriptureReferences: ["Genesis 11:29"],
    confidenceLevel: "explicit",
    notes:
      "Identification with Sarah is rabbinic tradition (Megillah 14a, Sanhedrin 69b) and is followed by Josephus, but is not asserted in scripture; Genesis 20:12 conflicts with this identification by naming Terah, not Haran, as Sarah's father.",
  },

  {
    id: "hagar",
    name: "Hagar",
    gender: "female",
    era: "patriarchal",
    description:
      "Egyptian handmaid given by Sarah to Abraham as a secondary wife; mother of Ishmael. Driven into the wilderness twice; promised by the Angel of Yahweh that her son would father a great nation.",
    scriptureReferences: [
      "Genesis 16",
      "Genesis 21:9-21",
      "Genesis 25:12",
      "Galatians 4:24-25",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "ishmael",
    name: "Ishmael",
    gender: "male",
    alternateNames: ["Yishma'el"],
    era: "patriarchal",
    roles: ["patriarch"],
    tribes: ["ishmaelites"],
    description:
      "Firstborn son of Abraham by Hagar; circumcised at age 13. Father of twelve princes, ancestor of Arab peoples. Buried his father Abraham alongside Isaac.",
    lifespanYears: 137,
    ageAtDeathRef: "Genesis 25:17",
    scriptureReferences: [
      "Genesis 16:11-16",
      "Genesis 17:23-26",
      "Genesis 21:9-21",
      "Genesis 25:9",
      "Genesis 25:12-18",
      "1 Chronicles 1:28-31",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "keturah",
    name: "Keturah",
    gender: "female",
    era: "patriarchal",
    description:
      "Wife (or concubine) Abraham took after Sarah's death; mother of six sons through whom various Arabian peoples descended.",
    scriptureReferences: ["Genesis 25:1-4", "1 Chronicles 1:32-33"],
    confidenceLevel: "explicit",
    notes:
      "Genesis 25:1 calls her 'wife', but 1 Chronicles 1:32 calls her 'concubine'. Tradition resolves this by treating her as a concubine elevated to wife status, or as a separate woman; the text is genuinely ambiguous.",
  },

  {
    id: "isaac",
    name: "Isaac",
    gender: "male",
    alternateNames: ["Yitzchak", "He laughs"],
    era: "patriarchal",
    roles: ["patriarch", "ancestor-of-christ"],
    tribes: ["israelites"],
    description:
      "Only son of Abraham and Sarah, born when Abraham was 100 and Sarah 90. The promised son through whom Yahweh's covenant would continue. Bound by his father at Moriah but spared by divine substitute. Father of Esau and Jacob.",
    lifespanYears: 180,
    ageAtDeathRef: "Genesis 35:28",
    scriptureReferences: [
      "Genesis 17:19-21",
      "Genesis 21:1-8",
      "Genesis 22",
      "Genesis 24",
      "Genesis 25:19-26",
      "Genesis 26",
      "Genesis 27",
      "Genesis 35:27-29",
      "Matthew 1:2",
      "Luke 3:34",
      "Hebrews 11:17-20",
      "James 2:21",
    ],
    confidenceLevel: "explicit",
  },

  {
    id: "bethuel",
    name: "Bethuel",
    gender: "male",
    era: "patriarchal",
    description:
      "Son of Nahor (Abraham's brother) and Milcah; father of Rebekah and Laban. An Aramean dwelling in Paddan-Aram.",
    scriptureReferences: [
      "Genesis 22:22-23",
      "Genesis 24:15",
      "Genesis 24:50",
      "Genesis 25:20",
      "Genesis 28:5",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "rebekah",
    name: "Rebekah",
    gender: "female",
    alternateNames: ["Rivkah"],
    era: "patriarchal",
    roles: ["matriarch", "ancestor-of-christ"],
    description:
      "Daughter of Bethuel, sister of Laban; betrothed to Isaac through the providential journey of Abraham's servant. Mother of Esau and Jacob; received the oracle that 'the elder shall serve the younger'. Engineered Jacob's reception of the patriarchal blessing.",
    scriptureReferences: [
      "Genesis 22:23",
      "Genesis 24",
      "Genesis 25:20-28",
      "Genesis 26:6-11",
      "Genesis 27",
      "Genesis 49:31",
      "Romans 9:10-13",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "laban",
    name: "Laban",
    gender: "male",
    era: "patriarchal",
    description:
      "Son of Bethuel, brother of Rebekah; father of Leah and Rachel. Hosted Jacob for twenty years and gave both daughters in marriage. Repeatedly altered Jacob's wages but was overcome by divine prosperity.",
    scriptureReferences: [
      "Genesis 24:29-60",
      "Genesis 28:2",
      "Genesis 29-31",
    ],
    confidenceLevel: "explicit",
  },

  {
    id: "esau",
    name: "Esau",
    gender: "male",
    alternateNames: ["Edom", "Hairy"],
    era: "patriarchal",
    tribes: ["edomites"],
    description:
      "Firstborn of Isaac and Rebekah, twin of Jacob; a skillful hunter. Sold his birthright to Jacob for a meal of red lentil stew, and lost his blessing to Jacob through Rebekah's stratagem. Settled in Seir; father of the Edomite peoples.",
    scriptureReferences: [
      "Genesis 25:24-34",
      "Genesis 26:34-35",
      "Genesis 27",
      "Genesis 28:6-9",
      "Genesis 32:3",
      "Genesis 33",
      "Genesis 35:29",
      "Genesis 36",
      "Malachi 1:2-3",
      "Romans 9:13",
      "Hebrews 11:20",
      "Hebrews 12:16-17",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "jacob",
    name: "Jacob",
    gender: "male",
    alternateNames: ["Israel", "Yaakov", "Heel-grabber"],
    era: "patriarchal",
    roles: ["patriarch", "ancestor-of-christ"],
    tribes: ["israelites"],
    description:
      "Younger twin of Esau; obtained the birthright and blessing. Fled to Paddan-Aram; served Laban twenty years and married Leah and Rachel (and their handmaids Bilhah and Zilpah). Wrestled with the Angel of Yahweh and was renamed Israel ('he strives with God'). Father of the twelve tribes of Israel.",
    lifespanYears: 147,
    ageAtDeathRef: "Genesis 47:28",
    scriptureReferences: [
      "Genesis 25:24-34",
      "Genesis 27",
      "Genesis 28-31",
      "Genesis 32",
      "Genesis 35:9-15",
      "Genesis 47:28-31",
      "Genesis 49",
      "Matthew 1:2",
      "Luke 3:34",
      "Hebrews 11:21",
    ],
    confidenceLevel: "explicit",
  },

  {
    id: "moab",
    name: "Moab",
    gender: "male",
    era: "patriarchal",
    tribes: ["moabites"],
    description:
      "Son of Lot by his elder daughter, conceived in incest after the destruction of Sodom; eponymous ancestor of the Moabite people.",
    scriptureReferences: ["Genesis 19:37", "Deuteronomy 2:9"],
    confidenceLevel: "explicit",
  },
  {
    id: "ben-ammi",
    name: "Ben-Ammi",
    gender: "male",
    alternateNames: ["Son of my people"],
    era: "patriarchal",
    tribes: ["ammonites"],
    description:
      "Son of Lot by his younger daughter, conceived in incest after the destruction of Sodom; eponymous ancestor of the Ammonite people.",
    scriptureReferences: ["Genesis 19:38", "Deuteronomy 2:19"],
    confidenceLevel: "explicit",
  },

  {
    id: "zimran",
    name: "Zimran",
    gender: "male",
    era: "patriarchal",
    description: "Eldest son of Abraham by Keturah.",
    scriptureReferences: ["Genesis 25:2", "1 Chronicles 1:32"],
    confidenceLevel: "explicit",
  },
  {
    id: "jokshan",
    name: "Jokshan",
    gender: "male",
    era: "patriarchal",
    description: "Son of Abraham by Keturah; father of Sheba and Dedan.",
    scriptureReferences: ["Genesis 25:2-3", "1 Chronicles 1:32"],
    confidenceLevel: "explicit",
  },
  {
    id: "medan",
    name: "Medan",
    gender: "male",
    era: "patriarchal",
    description: "Son of Abraham by Keturah.",
    scriptureReferences: ["Genesis 25:2", "1 Chronicles 1:32"],
    confidenceLevel: "explicit",
  },
  {
    id: "midian",
    name: "Midian",
    gender: "male",
    era: "patriarchal",
    tribes: ["midianites"],
    description:
      "Son of Abraham by Keturah; eponymous ancestor of the Midianites, the desert people whose later descendants included Jethro, Moses' father-in-law.",
    scriptureReferences: ["Genesis 25:2", "Genesis 25:4", "1 Chronicles 1:32-33"],
    confidenceLevel: "explicit",
  },
  {
    id: "ishbak",
    name: "Ishbak",
    gender: "male",
    era: "patriarchal",
    description: "Son of Abraham by Keturah.",
    scriptureReferences: ["Genesis 25:2", "1 Chronicles 1:32"],
    confidenceLevel: "explicit",
  },
  {
    id: "shuah",
    name: "Shuah",
    gender: "male",
    era: "patriarchal",
    description:
      "Youngest son of Abraham by Keturah; later associated with the Shuhites (cf. Job's friend Bildad the Shuhite).",
    scriptureReferences: ["Genesis 25:2", "1 Chronicles 1:32", "Job 2:11"],
    confidenceLevel: "explicit",
  },

  {
    id: "nebaioth",
    name: "Nebaioth",
    gender: "male",
    era: "patriarchal",
    tribes: ["ishmaelites"],
    description: "Firstborn son of Ishmael; brother of Esau's wife Basemath.",
    scriptureReferences: [
      "Genesis 25:13",
      "Genesis 28:9",
      "Genesis 36:3",
      "1 Chronicles 1:29",
      "Isaiah 60:7",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "kedar",
    name: "Kedar",
    gender: "male",
    era: "patriarchal",
    tribes: ["ishmaelites"],
    description:
      "Second son of Ishmael; later associated with a powerful nomadic Arab people frequently named in the prophets.",
    scriptureReferences: [
      "Genesis 25:13",
      "1 Chronicles 1:29",
      "Psalm 120:5",
      "Isaiah 21:16-17",
      "Jeremiah 49:28-29",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "adbeel",
    name: "Adbeel",
    gender: "male",
    era: "patriarchal",
    tribes: ["ishmaelites"],
    description: "Son of Ishmael.",
    scriptureReferences: ["Genesis 25:13", "1 Chronicles 1:29"],
    confidenceLevel: "explicit",
  },
  {
    id: "mibsam",
    name: "Mibsam",
    gender: "male",
    era: "patriarchal",
    tribes: ["ishmaelites"],
    description: "Son of Ishmael.",
    scriptureReferences: ["Genesis 25:13", "1 Chronicles 1:29"],
    confidenceLevel: "explicit",
  },
  {
    id: "mishma",
    name: "Mishma",
    gender: "male",
    era: "patriarchal",
    tribes: ["ishmaelites"],
    description: "Son of Ishmael.",
    scriptureReferences: ["Genesis 25:14", "1 Chronicles 1:30"],
    confidenceLevel: "explicit",
  },
  {
    id: "dumah",
    name: "Dumah",
    gender: "male",
    era: "patriarchal",
    tribes: ["ishmaelites"],
    description:
      "Son of Ishmael; gave his name to a place in Arabia mentioned in Isaiah 21:11.",
    scriptureReferences: ["Genesis 25:14", "1 Chronicles 1:30", "Isaiah 21:11"],
    confidenceLevel: "explicit",
  },
  {
    id: "massa",
    name: "Massa",
    gender: "male",
    era: "patriarchal",
    tribes: ["ishmaelites"],
    description: "Son of Ishmael.",
    scriptureReferences: ["Genesis 25:14", "1 Chronicles 1:30"],
    confidenceLevel: "explicit",
  },
  {
    id: "hadad-of-ishmael",
    name: "Hadad (son of Ishmael)",
    gender: "male",
    era: "patriarchal",
    tribes: ["ishmaelites"],
    description:
      "Son of Ishmael. The name appears for several distinct figures in scripture; this is the Ishmaelite Hadad.",
    scriptureReferences: ["Genesis 25:15", "1 Chronicles 1:30"],
    confidenceLevel: "explicit",
  },
  {
    id: "tema",
    name: "Tema",
    gender: "male",
    era: "patriarchal",
    tribes: ["ishmaelites"],
    description:
      "Son of Ishmael; gave his name to an oasis in northwestern Arabia.",
    scriptureReferences: [
      "Genesis 25:15",
      "1 Chronicles 1:30",
      "Job 6:19",
      "Isaiah 21:14",
      "Jeremiah 25:23",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "jetur",
    name: "Jetur",
    gender: "male",
    era: "patriarchal",
    tribes: ["ishmaelites"],
    description:
      "Son of Ishmael; ancestor of the Itureans, an Arab people of northern Transjordan.",
    scriptureReferences: ["Genesis 25:15", "1 Chronicles 1:31", "1 Chronicles 5:19"],
    confidenceLevel: "explicit",
  },
  {
    id: "naphish",
    name: "Naphish",
    gender: "male",
    era: "patriarchal",
    tribes: ["ishmaelites"],
    description: "Son of Ishmael.",
    scriptureReferences: ["Genesis 25:15", "1 Chronicles 1:31", "1 Chronicles 5:19"],
    confidenceLevel: "explicit",
  },
  {
    id: "kedemah",
    name: "Kedemah",
    gender: "male",
    era: "patriarchal",
    tribes: ["ishmaelites"],
    description: "Twelfth and youngest son of Ishmael.",
    scriptureReferences: ["Genesis 25:15", "1 Chronicles 1:31"],
    confidenceLevel: "explicit",
  },

  {
    id: "leah",
    name: "Leah",
    gender: "female",
    era: "patriarchal",
    roles: ["matriarch", "ancestor-of-christ"],
    tribes: ["israelites"],
    description:
      "Elder daughter of Laban; given to Jacob through deception in place of Rachel. Mother of six of Jacob's sons (Reuben, Simeon, Levi, Judah, Issachar, Zebulun) and of his only named daughter Dinah. Buried in the cave of Machpelah.",
    scriptureReferences: [
      "Genesis 29:16-30",
      "Genesis 29:31-35",
      "Genesis 30:9-21",
      "Genesis 35:23",
      "Genesis 49:31",
      "Ruth 4:11",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "rachel",
    name: "Rachel",
    gender: "female",
    era: "patriarchal",
    roles: ["matriarch", "ancestor-of-christ"],
    tribes: ["israelites"],
    description:
      "Younger daughter of Laban; the wife Jacob loved. Mother of Joseph and Benjamin; died giving birth to Benjamin and was buried near Bethlehem.",
    scriptureReferences: [
      "Genesis 29:6-30",
      "Genesis 30:1-8",
      "Genesis 30:22-24",
      "Genesis 35:16-20",
      "Ruth 4:11",
      "Jeremiah 31:15",
      "Matthew 2:18",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "bilhah",
    name: "Bilhah",
    gender: "female",
    era: "patriarchal",
    tribes: ["israelites"],
    description:
      "Rachel's handmaid; given to Jacob as a secondary wife to bear children for Rachel. Mother of Dan and Naphtali.",
    scriptureReferences: [
      "Genesis 29:29",
      "Genesis 30:3-8",
      "Genesis 35:22",
      "Genesis 35:25",
      "Genesis 37:2",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "zilpah",
    name: "Zilpah",
    gender: "female",
    era: "patriarchal",
    tribes: ["israelites"],
    description:
      "Leah's handmaid; given to Jacob as a secondary wife to bear children for Leah. Mother of Gad and Asher.",
    scriptureReferences: ["Genesis 29:24", "Genesis 30:9-13", "Genesis 35:26", "Genesis 37:2"],
    confidenceLevel: "explicit",
  },

  {
    id: "reuben",
    name: "Reuben",
    gender: "male",
    era: "patriarchal",
    tribes: ["reuben"],
    description:
      "Firstborn of Jacob and Leah; founder of the tribe of Reuben. Forfeited his preeminence by lying with his father's concubine Bilhah. Tried to save Joseph from his brothers.",
    scriptureReferences: [
      "Genesis 29:32",
      "Genesis 35:22",
      "Genesis 37:21-22",
      "Genesis 37:29-30",
      "Genesis 49:3-4",
      "Numbers 26:5-7",
      "1 Chronicles 5:1-3",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "simeon",
    name: "Simeon",
    gender: "male",
    era: "patriarchal",
    tribes: ["simeon"],
    description:
      "Second son of Jacob and Leah; founder of the tribe of Simeon. With Levi, executed the men of Shechem in vengeance for Dinah; Jacob cursed their fierce anger.",
    scriptureReferences: [
      "Genesis 29:33",
      "Genesis 34:25-31",
      "Genesis 42:24",
      "Genesis 43:23",
      "Genesis 49:5-7",
      "Numbers 26:12-14",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "levi",
    name: "Levi",
    gender: "male",
    era: "patriarchal",
    tribes: ["levi"],
    description:
      "Third son of Jacob and Leah; founder of the priestly tribe of Levi. Joined Simeon in the slaughter at Shechem. Ancestor of Moses, Aaron, and the Aaronic priesthood.",
    lifespanYears: 137,
    ageAtDeathRef: "Exodus 6:16",
    scriptureReferences: [
      "Genesis 29:34",
      "Genesis 34:25-31",
      "Genesis 49:5-7",
      "Exodus 6:16",
      "Numbers 26:57-62",
      "1 Chronicles 6",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "judah",
    name: "Judah",
    gender: "male",
    era: "patriarchal",
    roles: ["ancestor-of-christ"],
    tribes: ["judah"],
    description:
      "Fourth son of Jacob and Leah; founder of the royal tribe of Judah from which David and Christ descend. Suggested selling Joseph; later interceded for Benjamin. Father of Perez through Tamar.",
    scriptureReferences: [
      "Genesis 29:35",
      "Genesis 37:26-27",
      "Genesis 38",
      "Genesis 43:8-10",
      "Genesis 44:14-34",
      "Genesis 49:8-12",
      "Numbers 26:19-22",
      "Ruth 4:18-22",
      "Matthew 1:2-3",
      "Luke 3:33",
      "Revelation 5:5",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "dan",
    name: "Dan",
    gender: "male",
    era: "patriarchal",
    tribes: ["dan"],
    description:
      "Son of Jacob by Bilhah, Rachel's handmaid; founder of the tribe of Dan. The name means 'he has judged'.",
    scriptureReferences: [
      "Genesis 30:5-6",
      "Genesis 35:25",
      "Genesis 49:16-17",
      "Numbers 26:42-43",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "naphtali",
    name: "Naphtali",
    gender: "male",
    era: "patriarchal",
    tribes: ["naphtali"],
    description:
      "Son of Jacob by Bilhah; founder of the tribe of Naphtali. Blessed by Jacob as 'a hind let loose'.",
    scriptureReferences: [
      "Genesis 30:7-8",
      "Genesis 35:25",
      "Genesis 49:21",
      "Numbers 26:48-50",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "gad",
    name: "Gad",
    gender: "male",
    era: "patriarchal",
    tribes: ["gad"],
    description:
      "Son of Jacob by Zilpah, Leah's handmaid; founder of the tribe of Gad. Settled east of the Jordan.",
    scriptureReferences: [
      "Genesis 30:9-11",
      "Genesis 35:26",
      "Genesis 49:19",
      "Numbers 26:15-18",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "asher",
    name: "Asher",
    gender: "male",
    era: "patriarchal",
    tribes: ["asher"],
    description:
      "Son of Jacob by Zilpah; founder of the tribe of Asher. The name means 'happy'.",
    scriptureReferences: [
      "Genesis 30:12-13",
      "Genesis 35:26",
      "Genesis 49:20",
      "Numbers 26:44-47",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "issachar",
    name: "Issachar",
    gender: "male",
    era: "patriarchal",
    tribes: ["issachar"],
    description:
      "Son of Jacob and Leah; founder of the tribe of Issachar.",
    scriptureReferences: [
      "Genesis 30:17-18",
      "Genesis 35:23",
      "Genesis 49:14-15",
      "Numbers 26:23-25",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "zebulun",
    name: "Zebulun",
    gender: "male",
    era: "patriarchal",
    tribes: ["zebulun"],
    description:
      "Sixth son of Jacob and Leah; founder of the tribe of Zebulun. Blessed to dwell at the haven of the seas.",
    scriptureReferences: [
      "Genesis 30:19-20",
      "Genesis 35:23",
      "Genesis 49:13",
      "Numbers 26:26-27",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "dinah",
    name: "Dinah",
    gender: "female",
    era: "patriarchal",
    tribes: ["israelites"],
    description:
      "Daughter of Jacob and Leah; defiled by Shechem son of Hamor, prompting the violent retaliation of her brothers Simeon and Levi.",
    scriptureReferences: ["Genesis 30:21", "Genesis 34", "Genesis 46:15"],
    confidenceLevel: "explicit",
  },
  {
    id: "joseph",
    name: "Joseph",
    gender: "male",
    era: "patriarchal",
    roles: ["patriarch"],
    tribes: ["joseph"],
    description:
      "Eleventh son of Jacob, firstborn of Rachel; sold by his brothers into Egyptian slavery. Rose from prison to become Pharaoh's vizier through divine interpretation of dreams. Preserved his family during famine; through his sons Manasseh and Ephraim received a double inheritance among the tribes.",
    lifespanYears: 110,
    ageAtDeathRef: "Genesis 50:22",
    scriptureReferences: [
      "Genesis 30:22-24",
      "Genesis 37",
      "Genesis 39-50",
      "Numbers 26:28",
      "Hebrews 11:21-22",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "benjamin",
    name: "Benjamin",
    gender: "male",
    alternateNames: ["Ben-oni"],
    era: "patriarchal",
    tribes: ["benjamin"],
    description:
      "Twelfth and youngest son of Jacob, second-born of Rachel who died bearing him near Bethlehem. Originally named Ben-oni ('son of my sorrow') by Rachel, renamed Benjamin ('son of the right hand') by Jacob. Founder of the tribe of Benjamin (later including Saul and Paul).",
    scriptureReferences: [
      "Genesis 35:16-20",
      "Genesis 42-45",
      "Genesis 49:27",
      "Numbers 26:38-41",
      "Philippians 3:5",
    ],
    confidenceLevel: "explicit",
  },

  {
    id: "asenath",
    name: "Asenath",
    gender: "female",
    era: "patriarchal",
    description:
      "Egyptian wife of Joseph, given to him by Pharaoh; daughter of Potiphera priest of On (Heliopolis). Mother of Manasseh and Ephraim.",
    scriptureReferences: ["Genesis 41:45", "Genesis 41:50", "Genesis 46:20"],
    confidenceLevel: "explicit",
  },
  {
    id: "manasseh",
    name: "Manasseh (son of Joseph)",
    gender: "male",
    era: "patriarchal",
    tribes: ["manasseh"],
    description:
      "Firstborn son of Joseph and Asenath; adopted by Jacob and given a tribal inheritance equal to Jacob's other sons. Ancestor of the half-tribe east and west of the Jordan. Distinct from the later king Manasseh of Judah.",
    scriptureReferences: [
      "Genesis 41:51",
      "Genesis 48:5",
      "Genesis 48:13-20",
      "Genesis 50:23",
      "Numbers 26:28-34",
      "Joshua 17",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "ephraim",
    name: "Ephraim",
    gender: "male",
    era: "patriarchal",
    tribes: ["ephraim"],
    description:
      "Younger son of Joseph and Asenath; received the greater blessing from Jacob, who crossed his hands to favor him over Manasseh. Ancestor of the most numerous and politically dominant of the northern tribes; in prophetic literature, 'Ephraim' often stands for the northern kingdom of Israel.",
    scriptureReferences: [
      "Genesis 41:52",
      "Genesis 48:5",
      "Genesis 48:13-20",
      "Numbers 26:35-37",
      "Joshua 16",
      "Hosea 4:17",
      "Hosea 11",
    ],
    confidenceLevel: "explicit",
  },

  {
    id: "adah-of-elon",
    name: "Adah (daughter of Elon)",
    gender: "female",
    alternateNames: ["Basemath (Genesis 26:34)"],
    era: "patriarchal",
    tribes: ["edomites"],
    description:
      "Hittite wife of Esau, daughter of Elon. Genesis 26:34 names her Basemath; Genesis 36:2 names her Adah. Mother of Eliphaz. Distinct from the Cainite Adah, wife of Lamech.",
    scriptureReferences: ["Genesis 26:34", "Genesis 36:2", "Genesis 36:4", "Genesis 36:10"],
    confidenceLevel: "explicit",
    notes:
      "Genesis 26:34 and Genesis 36:2 give different names for Esau's Hittite wife (daughter of Elon). Whether due to renaming, scribal variation, or harmonization is debated; this entry follows Gen 36 as the canonical genealogical chapter and notes Gen 26:34 as an alternate.",
  },
  {
    id: "aholibamah-of-anah",
    name: "Aholibamah",
    gender: "female",
    alternateNames: ["Oholibamah", "Judith (Genesis 26:34)"],
    era: "patriarchal",
    tribes: ["edomites"],
    description:
      "Hivite wife of Esau, daughter of Anah, granddaughter of Zibeon. Genesis 26:34 calls her Judith daughter of Beeri the Hittite. Mother of Jeush, Jaalam, and Korah.",
    scriptureReferences: ["Genesis 26:34", "Genesis 36:2", "Genesis 36:5", "Genesis 36:14"],
    confidenceLevel: "explicit",
    notes:
      "Conflicting names with Gen 26:34 are unresolved; this entry follows Gen 36 as canonical naming.",
  },
  {
    id: "basemath-of-ishmael",
    name: "Basemath (daughter of Ishmael)",
    gender: "female",
    alternateNames: ["Mahalath (Genesis 28:9)"],
    era: "patriarchal",
    tribes: ["edomites"],
    description:
      "Daughter of Ishmael, sister of Nebaioth; third wife of Esau. Genesis 28:9 calls her Mahalath; Genesis 36:3 calls her Basemath. Mother of Reuel.",
    scriptureReferences: ["Genesis 28:9", "Genesis 36:3", "Genesis 36:4", "Genesis 36:10"],
    confidenceLevel: "explicit",
    notes:
      "Same person, two names. Distinct from Adah-of-Elon who is also called Basemath in Gen 26:34.",
  },
  {
    id: "eliphaz-of-esau",
    name: "Eliphaz (son of Esau)",
    gender: "male",
    era: "patriarchal",
    tribes: ["edomites"],
    description:
      "Son of Esau by Adah; chief progenitor of the Edomite clans through five named sons plus Amalek by his concubine Timna. Distinct from Eliphaz the Temanite of the book of Job (though that figure is traditionally connected to this line).",
    scriptureReferences: ["Genesis 36:4", "Genesis 36:10-12", "Genesis 36:15-16"],
    confidenceLevel: "explicit",
  },
  {
    id: "reuel-of-esau",
    name: "Reuel (son of Esau)",
    gender: "male",
    era: "patriarchal",
    tribes: ["edomites"],
    description:
      "Son of Esau by Basemath daughter of Ishmael; father of four Edomite chieftains. Distinct from Reuel the priest of Midian (Jethro), Moses' father-in-law.",
    scriptureReferences: ["Genesis 36:4", "Genesis 36:10", "Genesis 36:13", "Genesis 36:17"],
    confidenceLevel: "explicit",
  },
  {
    id: "jeush",
    name: "Jeush",
    gender: "male",
    era: "patriarchal",
    tribes: ["edomites"],
    description: "Son of Esau by Aholibamah; an Edomite chieftain.",
    scriptureReferences: ["Genesis 36:5", "Genesis 36:14", "Genesis 36:18"],
    confidenceLevel: "explicit",
  },
  {
    id: "jaalam",
    name: "Jaalam",
    gender: "male",
    alternateNames: ["Jalam"],
    era: "patriarchal",
    tribes: ["edomites"],
    description: "Son of Esau by Aholibamah; an Edomite chieftain.",
    scriptureReferences: ["Genesis 36:5", "Genesis 36:14", "Genesis 36:18"],
    confidenceLevel: "explicit",
  },
  {
    id: "korah-of-esau",
    name: "Korah (son of Esau)",
    gender: "male",
    era: "patriarchal",
    tribes: ["edomites"],
    description:
      "Son of Esau by Aholibamah; an Edomite chieftain. Distinct from the Levite Korah son of Izhar who led the rebellion in Numbers 16.",
    scriptureReferences: ["Genesis 36:5", "Genesis 36:14", "Genesis 36:18"],
    confidenceLevel: "explicit",
  },

  {
    id: "teman",
    name: "Teman",
    gender: "male",
    era: "patriarchal",
    tribes: ["edomites"],
    description:
      "Firstborn son of Eliphaz; eponymous ancestor of the Temanites and the region of Teman in Edom. Often associated with wisdom (cf. Jeremiah 49:7).",
    scriptureReferences: [
      "Genesis 36:11",
      "Genesis 36:15",
      "1 Chronicles 1:36",
      "Jeremiah 49:7",
      "Jeremiah 49:20",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "omar",
    name: "Omar",
    gender: "male",
    era: "patriarchal",
    tribes: ["edomites"],
    description: "Son of Eliphaz; an Edomite chief.",
    scriptureReferences: ["Genesis 36:11", "Genesis 36:15", "1 Chronicles 1:36"],
    confidenceLevel: "explicit",
  },
  {
    id: "zepho",
    name: "Zepho",
    gender: "male",
    alternateNames: ["Zephi"],
    era: "patriarchal",
    tribes: ["edomites"],
    description: "Son of Eliphaz; an Edomite chief.",
    scriptureReferences: ["Genesis 36:11", "Genesis 36:15", "1 Chronicles 1:36"],
    confidenceLevel: "explicit",
  },
  {
    id: "gatam",
    name: "Gatam",
    gender: "male",
    era: "patriarchal",
    tribes: ["edomites"],
    description: "Son of Eliphaz; an Edomite chief.",
    scriptureReferences: ["Genesis 36:11", "Genesis 36:16", "1 Chronicles 1:36"],
    confidenceLevel: "explicit",
  },
  {
    id: "kenaz-of-edom",
    name: "Kenaz (son of Eliphaz)",
    gender: "male",
    era: "patriarchal",
    tribes: ["edomites"],
    description:
      "Son of Eliphaz; an Edomite chief. Distinct from the later Kenaz the brother of Caleb (cf. Joshua 15:17), though that line is sometimes connected by the Kenizzites.",
    scriptureReferences: ["Genesis 36:11", "Genesis 36:15", "1 Chronicles 1:36"],
    confidenceLevel: "explicit",
  },
  {
    id: "timna",
    name: "Timna (concubine of Eliphaz)",
    gender: "female",
    era: "patriarchal",
    tribes: ["edomites"],
    description:
      "Horite concubine of Eliphaz son of Esau; mother of Amalek. Sister of Lotan the Horite chief.",
    scriptureReferences: ["Genesis 36:12", "Genesis 36:22", "1 Chronicles 1:36", "1 Chronicles 1:39"],
    confidenceLevel: "explicit",
  },
  {
    id: "amalek",
    name: "Amalek",
    gender: "male",
    era: "patriarchal",
    tribes: ["amalekites"],
    description:
      "Son of Eliphaz by his concubine Timna; eponymous ancestor of the Amalekites, perpetual enemies of Israel from the wilderness onward (Exodus 17, Numbers 24, 1 Samuel 15).",
    scriptureReferences: [
      "Genesis 36:12",
      "Genesis 36:16",
      "1 Chronicles 1:36",
      "Exodus 17:8-16",
      "Numbers 24:20",
      "Deuteronomy 25:17-19",
      "1 Samuel 15",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "nahath",
    name: "Nahath",
    gender: "male",
    era: "patriarchal",
    tribes: ["edomites"],
    description: "Son of Reuel; an Edomite chief.",
    scriptureReferences: ["Genesis 36:13", "Genesis 36:17", "1 Chronicles 1:37"],
    confidenceLevel: "explicit",
  },
  {
    id: "zerah-of-edom",
    name: "Zerah (son of Reuel)",
    gender: "male",
    era: "patriarchal",
    tribes: ["edomites"],
    description:
      "Son of Reuel; an Edomite chief. Distinct from Zerah son of Judah (Genesis 38:30) and other figures of the same name.",
    scriptureReferences: ["Genesis 36:13", "Genesis 36:17", "1 Chronicles 1:37"],
    confidenceLevel: "explicit",
  },
  {
    id: "shammah",
    name: "Shammah (son of Reuel)",
    gender: "male",
    era: "patriarchal",
    tribes: ["edomites"],
    description:
      "Son of Reuel; an Edomite chief. Distinct from later figures of the same name (e.g. David's mighty man).",
    scriptureReferences: ["Genesis 36:13", "Genesis 36:17", "1 Chronicles 1:37"],
    confidenceLevel: "explicit",
  },
  {
    id: "mizzah",
    name: "Mizzah",
    gender: "male",
    era: "patriarchal",
    tribes: ["edomites"],
    description: "Son of Reuel; an Edomite chief.",
    scriptureReferences: ["Genesis 36:13", "Genesis 36:17", "1 Chronicles 1:37"],
    confidenceLevel: "explicit",
  },
];
