import type { Tribe } from "./types";

export const tribes: Tribe[] = [
  {
    id: "israelites",
    name: "Israelites",
    alternateNames: ["Children of Israel", "Sons of Jacob", "Bnei Yisrael"],
    type: "nation",
    founderId: "jacob",
    description:
      "The covenant nation descended from Jacob (renamed Israel), comprising the twelve tribes that emerged from his sons. Recipient of the Sinai covenant and the land promises given to Abraham, Isaac, and Jacob.",
    scriptureReferences: [
      "Genesis 32:28",
      "Genesis 35:10-12",
      "Exodus 1:1-7",
      "Exodus 19:5-6",
    ],
    confidenceLevel: "stated",
  },

  {
    id: "reuben",
    name: "Reuben",
    type: "patriarchal",
    founderId: "reuben",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's firstborn son. Settled east of the Jordan in the Mishor; first in census order but lost the firstborn status. Eventually carried into Assyrian exile.",
    scriptureReferences: [
      "Genesis 49:3-4",
      "Numbers 1:20-21",
      "Numbers 26:5-7",
      "Numbers 32",
      "Joshua 13:15-23",
      "1 Chronicles 5:1-10",
    ],
    confidenceLevel: "stated",
    jacobsBlessing: {
      reference: "Genesis 49:3-4",
      type: "curse",
      translation: "WEB",
      text: "Reuben, you are my firstborn, my might, and the beginning of my strength, excelling in dignity, and excelling in power. Boiling over like water, you shall not excel, because you went up to your father's bed, then defiled it. He went up to my couch.",
    },
  },
  {
    id: "simeon",
    name: "Simeon",
    type: "patriarchal",
    founderId: "simeon",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's second son. Received an inheritance scattered within Judah's territory (Joshua 19:1-9), fulfilling Jacob's prophecy of dispersion (Gen 49:7).",
    scriptureReferences: [
      "Genesis 49:5-7",
      "Numbers 1:22-23",
      "Numbers 26:12-14",
      "Joshua 19:1-9",
    ],
    confidenceLevel: "stated",
    jacobsBlessing: {
      reference: "Genesis 49:5-7",
      type: "curse",
      translation: "WEB",
      text: "Simeon and Levi are brothers. Their swords are weapons of violence. My soul, don't come into their council. My glory, don't be united to their assembly; for in their anger they killed men. In their self-will they hamstrung cattle. Cursed be their anger, for it was fierce; and their wrath, for it was cruel. I will divide them in Jacob, and scatter them in Israel.",
    },
  },
  {
    id: "levi",
    name: "Levi",
    type: "patriarchal",
    founderId: "levi",
    parentTribeId: "israelites",
    description:
      "The priestly tribe, set apart for service of the tabernacle and temple. Did not receive a contiguous territorial inheritance but was given forty-eight cities throughout the land (Numbers 35; Joshua 21). Includes the Aaronic priesthood.",
    scriptureReferences: [
      "Genesis 49:5-7",
      "Exodus 32:26-29",
      "Numbers 3-4",
      "Numbers 18",
      "Numbers 35",
      "Joshua 21",
    ],
    confidenceLevel: "stated",
    jacobsBlessing: {
      reference: "Genesis 49:5-7",
      type: "curse",
      translation: "WEB",
      text: "Simeon and Levi are brothers. Their swords are weapons of violence. My soul, don't come into their council. My glory, don't be united to their assembly; for in their anger they killed men. In their self-will they hamstrung cattle. Cursed be their anger, for it was fierce; and their wrath, for it was cruel. I will divide them in Jacob, and scatter them in Israel.",
    },
  },
  {
    id: "judah",
    name: "Judah",
    type: "patriarchal",
    founderId: "judah",
    parentTribeId: "israelites",
    description:
      "The royal tribe of David and the messianic line. Received the largest southern inheritance and gave its name to the southern kingdom after the schism. Returned from exile largely intact and gave its name to the postexilic Jewish people.",
    scriptureReferences: [
      "Genesis 49:8-12",
      "Numbers 1:26-27",
      "Numbers 26:19-22",
      "Joshua 15",
      "1 Kings 12",
      "Matthew 1",
      "Hebrews 7:14",
      "Revelation 5:5",
    ],
    confidenceLevel: "stated",
    jacobsBlessing: {
      reference: "Genesis 49:8-12",
      type: "blessing",
      translation: "WEB",
      text: "Judah, your brothers will praise you. Your hand will be on the neck of your enemies. Your father's sons will bow down before you. Judah is a lion's cub. From the prey, my son, you have gone up. He stooped down, he crouched as a lion, as a lioness. Who will rouse him up? The scepter will not depart from Judah, nor the ruler's staff from between his feet, until he comes to whom it belongs. To him will the obedience of the peoples be. Binding his foal to the vine, his donkey's colt to the choice vine, he has washed his garments in wine, his robes in the blood of grapes. His eyes will be red with wine, his teeth white with milk.",
    },
  },
  {
    id: "dan",
    name: "Dan",
    type: "patriarchal",
    founderId: "dan",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's son by Bilhah. Originally allotted territory in the coastal lowlands, but later migrated north to Laish, renaming it Dan (Judges 18). Notably absent from the list of sealed tribes in Revelation 7.",
    scriptureReferences: [
      "Genesis 49:16-17",
      "Numbers 26:42-43",
      "Joshua 19:40-48",
      "Judges 18",
      "Revelation 7:5-8",
    ],
    confidenceLevel: "stated",
    jacobsBlessing: {
      reference: "Genesis 49:16-18",
      type: "mixed",
      translation: "WEB",
      text: "Dan will judge his people, as one of the tribes of Israel. Dan will be a serpent on the trail, an adder in the path, that bites the horse's heels, so that his rider falls backward. I have waited for your salvation, Yahweh.",
    },
  },
  {
    id: "naphtali",
    name: "Naphtali",
    type: "patriarchal",
    founderId: "naphtali",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's son by Bilhah. Settled in the upper Galilee. The land of Naphtali later became the region of Jesus' Galilean ministry (cf. Matthew 4:13-16, Isaiah 9:1).",
    scriptureReferences: [
      "Genesis 49:21",
      "Numbers 26:48-50",
      "Joshua 19:32-39",
      "Isaiah 9:1",
      "Matthew 4:13-16",
    ],
    confidenceLevel: "stated",
    jacobsBlessing: {
      reference: "Genesis 49:21",
      type: "blessing",
      translation: "WEB",
      text: "Naphtali is a doe set free, who bears beautiful fawns.",
    },
  },
  {
    id: "gad",
    name: "Gad",
    type: "patriarchal",
    founderId: "gad",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's son by Zilpah. Settled east of the Jordan between Reuben and Manasseh.",
    scriptureReferences: [
      "Genesis 49:19",
      "Numbers 26:15-18",
      "Numbers 32",
      "Joshua 13:24-28",
    ],
    confidenceLevel: "stated",
    jacobsBlessing: {
      reference: "Genesis 49:19",
      type: "blessing",
      translation: "WEB",
      text: "A troop will press on Gad, but he will press on their heel.",
    },
  },
  {
    id: "asher",
    name: "Asher",
    type: "patriarchal",
    founderId: "asher",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's son by Zilpah. Settled in the fertile coastal region of western Galilee, between Carmel and Tyre.",
    scriptureReferences: [
      "Genesis 49:20",
      "Numbers 26:44-47",
      "Joshua 19:24-31",
    ],
    confidenceLevel: "stated",
    jacobsBlessing: {
      reference: "Genesis 49:20",
      type: "blessing",
      translation: "WEB",
      text: "Asher's food will be rich. He will produce royal dainties.",
    },
  },
  {
    id: "issachar",
    name: "Issachar",
    type: "patriarchal",
    founderId: "issachar",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's son by Leah. Settled in the Jezreel Valley.",
    scriptureReferences: [
      "Genesis 49:14-15",
      "Numbers 26:23-25",
      "Joshua 19:17-23",
    ],
    confidenceLevel: "stated",
    jacobsBlessing: {
      reference: "Genesis 49:14-15",
      type: "mixed",
      translation: "WEB",
      text: "Issachar is a strong donkey, lying down between the saddlebags. He saw a resting place, that it was good, the land, that it was pleasant. He bows his shoulder to the burden, and becomes a servant doing forced labor.",
    },
  },
  {
    id: "zebulun",
    name: "Zebulun",
    type: "patriarchal",
    founderId: "zebulun",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's son by Leah. Settled in lower Galilee between the Jezreel Valley and the Sea of Galilee.",
    scriptureReferences: [
      "Genesis 49:13",
      "Numbers 26:26-27",
      "Joshua 19:10-16",
      "Isaiah 9:1",
      "Matthew 4:13-16",
    ],
    confidenceLevel: "stated",
    jacobsBlessing: {
      reference: "Genesis 49:13",
      type: "blessing",
      translation: "WEB",
      text: "Zebulun will dwell at the haven of the sea. He will be for a haven of ships. His border will be on Sidon.",
    },
  },
  {
    id: "joseph",
    name: "Joseph",
    type: "patriarchal",
    founderId: "joseph",
    parentTribeId: "israelites",
    description:
      "The 'house of Joseph' is treated as one tribe in Jacob's blessing (Gen 49:22-26) but divided into two in the territorial allotments through Joseph's sons Manasseh and Ephraim. The double inheritance reflects Jacob's adoption of his grandsons in Genesis 48.",
    scriptureReferences: [
      "Genesis 48",
      "Genesis 49:22-26",
      "Joshua 16",
      "Joshua 17",
      "Revelation 7:8",
    ],
    confidenceLevel: "stated",
    notes:
      "Most lists of the twelve tribes substitute Manasseh and Ephraim for Joseph and Levi in territorial contexts, while Jacob's blessing names Joseph directly.",
    jacobsBlessing: {
      reference: "Genesis 49:22-26",
      type: "blessing",
      translation: "WEB",
      text: "Joseph is a fruitful vine, a fruitful vine by a spring. His branches run over the wall. The archers have severely grieved him, shot at him, and persecuted him: but his bow remained strong. The arms of his hands were made strong, by the hands of the Mighty One of Jacob (from there is the shepherd, the stone of Israel), even by the God of your father, who will help you, by the Almighty, who will bless you, with blessings of heaven above, blessings of the deep that lies below, blessings of the breasts, and of the womb. The blessings of your father have prevailed above the blessings of my ancestors, above the boundaries of the ancient hills. They will be on the head of Joseph, on the crown of the head of him who is separated from his brothers.",
    },
  },
  {
    id: "manasseh",
    name: "Manasseh",
    type: "patriarchal",
    founderId: "manasseh",
    parentTribeId: "joseph",
    description:
      "Tribe descended from Joseph's elder son. Received a divided inheritance: a half-tribe east of the Jordan (the largest single allotment) and a half-tribe west, between Ephraim and Issachar.",
    scriptureReferences: [
      "Genesis 48:13-20",
      "Numbers 26:28-34",
      "Numbers 32:39-42",
      "Joshua 17",
      "1 Chronicles 5:23-26",
    ],
    confidenceLevel: "stated",
    jacobsBlessing: {
      reference: "Genesis 48:14-20",
      type: "mixed",
      translation: "WEB",
      text: "Israel stretched out his right hand, and laid it on Ephraim's head, who was the younger, and his left hand on Manasseh's head, guiding his hands knowingly, for Manasseh was the firstborn… When Joseph saw that his father laid his right hand on the head of Ephraim, it displeased him… and Joseph said to his father, 'Not so, my father; for this is the firstborn. Put your right hand on his head.' His father refused, and said, 'I know, my son, I know. He also will become a people, and he also will be great. However, his younger brother will be greater than he, and his offspring will become a multitude of nations.' He blessed them that day, saying, 'Israel will bless in you, saying, \"God make you as Ephraim and as Manasseh\"' — and he set Ephraim before Manasseh.",
    },
  },
  {
    id: "ephraim",
    name: "Ephraim",
    type: "patriarchal",
    founderId: "ephraim",
    parentTribeId: "joseph",
    description:
      "Tribe descended from Joseph's younger son, who received Jacob's preferential blessing. The most populous and politically dominant northern tribe; in prophetic literature 'Ephraim' often stands for the entire northern kingdom.",
    scriptureReferences: [
      "Genesis 48:13-20",
      "Numbers 26:35-37",
      "Joshua 16",
      "Hosea 4:17",
      "Hosea 11:1-9",
    ],
    confidenceLevel: "stated",
    jacobsBlessing: {
      reference: "Genesis 48:14-20",
      type: "blessing",
      translation: "WEB",
      text: "Israel stretched out his right hand, and laid it on Ephraim's head, who was the younger… 'The God before whom my fathers Abraham and Isaac walked, the God who has fed me all my life long to this day, the angel who has redeemed me from all evil, bless the lads, and let my name be named on them, and the name of my fathers Abraham and Isaac. Let them grow into a multitude in the middle of the earth.' … 'I know, my son, I know. He [Manasseh] also will become a people, and he also will be great. However, his younger brother will be greater than he, and his offspring will become a multitude of nations.' He blessed them that day, saying, 'Israel will bless in you, saying, \"God make you as Ephraim and as Manasseh\"' — and he set Ephraim before Manasseh.",
    },
  },
  {
    id: "benjamin",
    name: "Benjamin",
    type: "patriarchal",
    founderId: "benjamin",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's youngest son, born to Rachel near Bethlehem. Received a small but strategically vital territory between Judah and Ephraim, including Jerusalem on its border. Produced Israel's first king (Saul) and later the apostle Paul.",
    scriptureReferences: [
      "Genesis 49:27",
      "Numbers 26:38-41",
      "Joshua 18:11-28",
      "Judges 19-21",
      "1 Samuel 9-10",
      "Philippians 3:5",
    ],
    confidenceLevel: "stated",
    jacobsBlessing: {
      reference: "Genesis 49:27",
      type: "blessing",
      translation: "WEB",
      text: "Benjamin is a ravenous wolf. In the morning he will devour the prey. At evening he will divide the plunder.",
    },
  },

  {
    id: "edomites",
    name: "Edomites",
    alternateNames: ["Sons of Esau", "Idumeans"],
    type: "nation",
    founderId: "esau",
    description:
      "Nation descended from Esau (Edom); settled in the mountainous region of Seir south of the Dead Sea. Persistent antagonists of Israel; later partially absorbed and Hellenized as the Idumeans (cf. Herod the Great).",
    scriptureReferences: [
      "Genesis 36",
      "Numbers 20:14-21",
      "1 Samuel 14:47",
      "2 Kings 8:20-22",
      "Obadiah",
      "Malachi 1:2-4",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "horites",
    name: "Horites",
    alternateNames: ["Hurrians (possibly)", "Hivites (Genesis 36:2 conflation)"],
    type: "ethnic-group",
    founderId: "seir-the-horite",
    description: "Pre-Edomite inhabitants of the hill country of Seir, descended from Seir the Horite. Genesis 36:20-30 lists their seven chiefs and many descendants. Driven out and absorbed by the descendants of Esau (Deuteronomy 2:12, 22). Sometimes confused with the Hivites in the textual tradition.",
    scriptureReferences: ["Genesis 14:6", "Genesis 36:20-30", "Deuteronomy 2:12", "Deuteronomy 2:22", "1 Chronicles 1:38-42"],
    confidenceLevel: "stated",
  },
  {
    id: "ishmaelites",
    name: "Ishmaelites",
    type: "nation",
    founderId: "ishmael",
    description:
      "Confederation of Arab peoples descended from Ishmael's twelve sons; nomadic dwellers of the northern Arabian peninsula. Frequently associated with the Midianites in scripture.",
    scriptureReferences: [
      "Genesis 25:12-18",
      "Genesis 37:25-28",
      "Judges 8:24",
      "1 Chronicles 1:28-31",
      "Psalm 83:6",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "moabites",
    name: "Moabites",
    type: "nation",
    founderId: "moab",
    description:
      "Nation descended from Lot's elder daughter; settled east of the Dead Sea on the Moabite plateau. Frequent enemies of Israel; Ruth the Moabitess became the great-grandmother of David.",
    scriptureReferences: [
      "Genesis 19:36-37",
      "Numbers 22-25",
      "Deuteronomy 2:9",
      "Judges 3:12-30",
      "Ruth",
      "1 Samuel 14:47",
      "Isaiah 15-16",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "ammonites",
    name: "Ammonites",
    alternateNames: ["Sons of Ammon", "Bene-Ammon"],
    type: "nation",
    founderId: "ben-ammi",
    description:
      "Nation descended from Lot's younger daughter; settled in Transjordan north of Moab around their capital Rabbah (modern Amman).",
    scriptureReferences: [
      "Genesis 19:36",
      "Genesis 19:38",
      "Deuteronomy 2:19",
      "Judges 11",
      "1 Samuel 11",
      "Nehemiah 2:10",
      "Nehemiah 13:1-3",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "midianites",
    name: "Midianites",
    type: "nation",
    founderId: "midian",
    description:
      "Nation descended from Abraham's son Midian by Keturah; nomadic traders and pastoralists of the northwestern Arabian peninsula. Moses lived among them with his father-in-law Jethro; later they oppressed Israel under Gideon.",
    scriptureReferences: [
      "Genesis 25:2",
      "Genesis 37:28-36",
      "Exodus 2:15-22",
      "Exodus 18",
      "Numbers 22",
      "Numbers 25",
      "Numbers 31",
      "Judges 6-8",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "aaronic-priesthood",
    name: "Aaronic priesthood",
    alternateNames: ["Sons of Aaron", "Kohanim"],
    type: "priestly-line",
    founderId: "aaron",
    parentTribeId: "levi",
    description:
      "The priestly line within Levi, restricted to the male descendants of Aaron. Held the exclusive right to officiate at the altar; from this line came the high priest.",
    scriptureReferences: [
      "Exodus 28",
      "Leviticus 8-10",
      "Numbers 3:1-4",
      "Numbers 18",
      "1 Chronicles 24",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "davidic-dynasty",
    name: "House of David",
    alternateNames: ["Davidic line", "Beit David"],
    type: "kingdom",
    founderId: "david",
    parentTribeId: "judah",
    description:
      "The royal line of David within Judah, holders of Yahweh's covenant promise of an everlasting throne (2 Samuel 7). Provided every legitimate king of Judah and, per Christian confession, culminates in Jesus the Messiah.",
    scriptureReferences: [
      "2 Samuel 7",
      "1 Kings 2",
      "Psalm 89",
      "Isaiah 9:6-7",
      "Jeremiah 23:5-6",
      "Matthew 1:1",
      "Luke 1:32-33",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "kenites",
    name: "Kenites",
    type: "ethnic-group",
    description:
      "Midianite-related clan associated with metallurgy and nomadic life around the Negev and Sinai. Jethro/Reuel, Moses' father-in-law, was a Kenite priest of Midian; Heber the Kenite was Jael's husband (Judges 4-5). Considered allies of Israel and partly absorbed into Judah.",
    scriptureReferences: [
      "Genesis 15:19",
      "Numbers 24:21-22",
      "Judges 1:16",
      "Judges 4:11",
      "Judges 5:24",
      "1 Samuel 15:6",
      "1 Chronicles 2:55",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "philistines",
    name: "Philistines",
    type: "ethnic-group",
    description:
      "Sea-Peoples-related coastal nation of the southwest Levant; settled in the pentapolis of Gaza, Ashkelon, Ashdod, Gath, and Ekron. Israel's chief national enemy through the period of the judges and Saul; broken decisively by David. Listed in Genesis 10:14 as descended from Mizraim through Casluhim/Caphtor.",
    scriptureReferences: [
      "Genesis 10:14",
      "Genesis 21:32-34",
      "Genesis 26:1-18",
      "Exodus 13:17",
      "Joshua 13:2-3",
      "Judges 3:31",
      "Judges 13-16",
      "1 Samuel 4-7",
      "1 Samuel 13-14",
      "1 Samuel 17",
      "1 Samuel 27-31",
      "2 Samuel 5:17-25",
      "2 Samuel 8:1",
      "2 Samuel 21:15-22",
      "Amos 1:6-8",
      "Zephaniah 2:4-7",
      "Zechariah 9:5-7",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "hittites",
    name: "Hittites",
    type: "ethnic-group",
    description:
      "Descendants of Heth son of Canaan (Genesis 10:15). The biblical Hittites are scattered Canaanite hill-country clans (Genesis 23; 26:34) and not directly the great Anatolian empire of the same Akkadian name, though the two may share a deeper ethnic root. Frequently named among the seven Canaanite nations.",
    scriptureReferences: [
      "Genesis 10:15",
      "Genesis 15:20",
      "Genesis 23",
      "Genesis 26:34",
      "Genesis 27:46",
      "Exodus 3:8",
      "Numbers 13:29",
      "Deuteronomy 7:1",
      "Joshua 1:4",
      "Judges 1:26",
      "1 Kings 10:29",
      "1 Kings 11:1",
      "2 Kings 7:6",
      "Ezekiel 16:3",
      "Ezekiel 16:45",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "arameans",
    name: "Arameans",
    alternateNames: ["Syrians"],
    type: "ethnic-group",
    founderId: "aram-son-of-shem",
    description:
      "Semitic peoples of the upper Euphrates and Syria descended from Aram son of Shem. The kingdoms of Aram-Damascus, Aram-Zobah, and others were Israel's most frequent foreign neighbors and adversaries. Aramaic, their language, became the lingua franca of the ancient Near East and the language of much of Daniel and Ezra.",
    scriptureReferences: [
      "Genesis 10:22-23",
      "Genesis 22:21",
      "Genesis 24:10",
      "Genesis 25:20",
      "Genesis 28:5",
      "Deuteronomy 26:5",
      "1 Samuel 14:47",
      "2 Samuel 8:5-6",
      "2 Samuel 10",
      "1 Kings 11:23-25",
      "1 Kings 15:18-20",
      "1 Kings 19-22",
      "2 Kings 5",
      "2 Kings 6:24-7:20",
      "2 Kings 8:7-15",
      "2 Kings 13",
      "2 Kings 16:5-9",
      "Isaiah 7-9",
      "Amos 1:3-5",
      "Amos 9:7",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "israel-northern",
    name: "Northern Kingdom of Israel",
    alternateNames: ["Ephraim", "Samaria", "the Ten Tribes"],
    type: "kingdom",
    description:
      "The breakaway kingdom under Jeroboam I (931 BC) and his successors comprising ten tribes north of Judah. Capital cities: Shechem, Tirzah, then Samaria from Omri onward. Fell to Assyria 722 BC; the people were deported and their land resettled with foreigners who became part of the later Samaritans.",
    scriptureReferences: [
      "1 Kings 12-22",
      "2 Kings 1-17",
      "Hosea 1:4-7",
      "Amos 7:10-17",
      "Micah 1:5-7",
      "Ezekiel 23",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "kenizzites",
    name: "Kenizzites",
    type: "ethnic-group",
    description:
      "Clan named for Kenaz; absorbed into Judah. Caleb son of Jephunneh is called a Kenizzite (Numbers 32:12; Joshua 14:6); his nephew Othniel and the Calebite descendants of 1 Chronicles 4 are Kenizzites by clan even though counted with Judah.",
    scriptureReferences: [
      "Genesis 15:19",
      "Numbers 32:12",
      "Joshua 14:6",
      "Joshua 14:14",
      "Judges 1:13",
      "Judges 3:9",
      "1 Chronicles 4:13-15",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "egyptians",
    name: "Egyptians",
    alternateNames: ["Mizraim"],
    type: "nation",
    founderId: "mizraim",
    description:
      "People of the land of the Nile, descended from Mizraim son of Ham. Hosts of Israel during the sojourn; Pharaoh's house is the seat of the second great oppression in scripture. Several Egyptians enter Israelite genealogies, e.g., Hagar, Bithiah daughter of Pharaoh, and the unnamed Egyptian who fathered the blasphemer of Leviticus 24.",
    scriptureReferences: [
      "Genesis 10:6",
      "Genesis 12:10-20",
      "Genesis 39-50",
      "Exodus 1-15",
      "1 Kings 3:1",
      "2 Kings 23:29",
      "Isaiah 19",
      "Ezekiel 29-32",
      "Hosea 11:1",
      "Matthew 2:13-15",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "herodians",
    name: "Herodian dynasty",
    type: "kingdom",
    description:
      "Idumean (Edomite) family raised to client-kingship by Rome through Antipater the Idumean and his son Herod the Great. Ruled Judea and adjacent territories from 37 BC to AD 100 in shifting subdivisions; intermarried with Hasmonean and Roman elites. Includes Herod the Great, Antipas, Philip the tetrarch, Agrippa I, Agrippa II, Drusilla, and Bernice.",
    scriptureReferences: [
      "Matthew 2",
      "Matthew 14:1-12",
      "Mark 6:14-29",
      "Luke 3:1",
      "Luke 23:6-12",
      "Acts 12",
      "Acts 23-26",
    ],
    confidenceLevel: "stated",
    notes:
      "The Herodians are not a tribe in the patriarchal sense; they are listed here as a dynastic kingdom-line because biblical figures (Herod the Great, the Tetrarchs, Agrippa I, Agrippa II, Bernice, Drusilla) belong by household to it.",
  },
  {
    id: "babylonians",
    name: "Babylonians",
    alternateNames: ["Chaldeans"],
    type: "nation",
    description:
      "People of the southern Mesopotamian plain whose city of Babylon rose to imperial power under Nebuchadnezzar II, conquered Judah in 605-586 BC, deported its leadership, and destroyed Solomon's temple. Daniel and the exilic literature unfold in their court.",
    scriptureReferences: [
      "Genesis 10:10",
      "Genesis 11:9",
      "2 Kings 24-25",
      "Isaiah 13",
      "Isaiah 47",
      "Jeremiah 25",
      "Jeremiah 50-51",
      "Daniel 1-7",
      "Habakkuk 1",
      "Revelation 17-18",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "assyrians",
    name: "Assyrians",
    type: "nation",
    description:
      "People of the upper Tigris whose Neo-Assyrian Empire (911-609 BC) conquered Aram-Damascus and the Northern Kingdom (722 BC), deported the ten tribes, and besieged Jerusalem under Hezekiah. Repeatedly named through Tiglath-Pileser, Shalmaneser, Sargon, Sennacherib, and Esarhaddon.",
    scriptureReferences: [
      "Genesis 10:11-12",
      "2 Kings 15:19",
      "2 Kings 15:29",
      "2 Kings 17-19",
      "Isaiah 10",
      "Isaiah 36-37",
      "Jonah",
      "Nahum",
      "Zephaniah 2:13",
    ],
    confidenceLevel: "stated",
  },
  {
    id: "amalekites",
    name: "Amalekites",
    type: "nation",
    founderId: "amalek",
    description:
      "Nation descended from Amalek son of Eliphaz, grandson of Esau. Perpetual archetypal enemies of Israel from Rephidim onward; Yahweh decreed total destruction (Deut 25:17-19) which Saul partially executed (1 Sam 15).",
    scriptureReferences: [
      "Genesis 36:12",
      "Exodus 17:8-16",
      "Numbers 24:20",
      "Deuteronomy 25:17-19",
      "1 Samuel 15",
      "1 Samuel 30",
      "Esther 3:1",
    ],
    confidenceLevel: "stated",
    notes:
      "Haman the Agagite (Esther 3) is traditionally identified as a late descendant of the Amalekite royal house through Agag (1 Sam 15), making Mordecai's confrontation with him an echo of Saul-Amalek.",
  },
];
