import type { Tribe } from "./types";

export const tribes: Tribe[] = [
  {
    id: "israelites",
    name: "Israelites",
    alternateNames: ["Children of Israel", "Sons of Jacob", "Bnei Yisrael"],
    type: "nation",
    founderId: "jacob",
    description:
      "The covenant nation descended from Jacob (renamed Israel), comprising the twelve tribes that emerged from his sons. Recipient of the Sinai covenant and the land promises given to Abraham, Isaac, and Jacob.",
    scriptureReferences: [
      "Genesis 32:28",
      "Genesis 35:10-12",
      "Exodus 1:1-7",
      "Exodus 19:5-6",
    ],
    confidenceLevel: "explicit",
  },

  {
    id: "reuben",
    name: "Reuben",
    type: "patriarchal",
    founderId: "reuben",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's firstborn son. Settled east of the Jordan in the Mishor; first in census order but lost the firstborn status. Eventually carried into Assyrian exile.",
    scriptureReferences: [
      "Genesis 49:3-4",
      "Numbers 1:20-21",
      "Numbers 26:5-7",
      "Numbers 32",
      "Joshua 13:15-23",
      "1 Chronicles 5:1-10",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "simeon",
    name: "Simeon",
    type: "patriarchal",
    founderId: "simeon",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's second son. Received an inheritance scattered within Judah's territory (Joshua 19:1-9), fulfilling Jacob's prophecy of dispersion (Gen 49:7).",
    scriptureReferences: [
      "Genesis 49:5-7",
      "Numbers 1:22-23",
      "Numbers 26:12-14",
      "Joshua 19:1-9",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "levi",
    name: "Levi",
    type: "patriarchal",
    founderId: "levi",
    parentTribeId: "israelites",
    description:
      "The priestly tribe, set apart for service of the tabernacle and temple. Did not receive a contiguous territorial inheritance but was given forty-eight cities throughout the land (Numbers 35; Joshua 21). Includes the Aaronic priesthood.",
    scriptureReferences: [
      "Genesis 49:5-7",
      "Exodus 32:26-29",
      "Numbers 3-4",
      "Numbers 18",
      "Numbers 35",
      "Joshua 21",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "judah",
    name: "Judah",
    type: "patriarchal",
    founderId: "judah",
    parentTribeId: "israelites",
    description:
      "The royal tribe of David and the messianic line. Received the largest southern inheritance and gave its name to the southern kingdom after the schism. Returned from exile largely intact and gave its name to the postexilic Jewish people.",
    scriptureReferences: [
      "Genesis 49:8-12",
      "Numbers 1:26-27",
      "Numbers 26:19-22",
      "Joshua 15",
      "1 Kings 12",
      "Matthew 1",
      "Hebrews 7:14",
      "Revelation 5:5",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "dan",
    name: "Dan",
    type: "patriarchal",
    founderId: "dan",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's son by Bilhah. Originally allotted territory in the coastal lowlands, but later migrated north to Laish, renaming it Dan (Judges 18). Notably absent from the list of sealed tribes in Revelation 7.",
    scriptureReferences: [
      "Genesis 49:16-17",
      "Numbers 26:42-43",
      "Joshua 19:40-48",
      "Judges 18",
      "Revelation 7:5-8",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "naphtali",
    name: "Naphtali",
    type: "patriarchal",
    founderId: "naphtali",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's son by Bilhah. Settled in the upper Galilee. The land of Naphtali later became the region of Jesus' Galilean ministry (cf. Matthew 4:13-16, Isaiah 9:1).",
    scriptureReferences: [
      "Genesis 49:21",
      "Numbers 26:48-50",
      "Joshua 19:32-39",
      "Isaiah 9:1",
      "Matthew 4:13-16",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "gad",
    name: "Gad",
    type: "patriarchal",
    founderId: "gad",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's son by Zilpah. Settled east of the Jordan between Reuben and Manasseh.",
    scriptureReferences: [
      "Genesis 49:19",
      "Numbers 26:15-18",
      "Numbers 32",
      "Joshua 13:24-28",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "asher",
    name: "Asher",
    type: "patriarchal",
    founderId: "asher",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's son by Zilpah. Settled in the fertile coastal region of western Galilee, between Carmel and Tyre.",
    scriptureReferences: [
      "Genesis 49:20",
      "Numbers 26:44-47",
      "Joshua 19:24-31",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "issachar",
    name: "Issachar",
    type: "patriarchal",
    founderId: "issachar",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's son by Leah. Settled in the Jezreel Valley.",
    scriptureReferences: [
      "Genesis 49:14-15",
      "Numbers 26:23-25",
      "Joshua 19:17-23",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "zebulun",
    name: "Zebulun",
    type: "patriarchal",
    founderId: "zebulun",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's son by Leah. Settled in lower Galilee between the Jezreel Valley and the Sea of Galilee.",
    scriptureReferences: [
      "Genesis 49:13",
      "Numbers 26:26-27",
      "Joshua 19:10-16",
      "Isaiah 9:1",
      "Matthew 4:13-16",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "joseph",
    name: "Joseph",
    type: "patriarchal",
    founderId: "joseph",
    parentTribeId: "israelites",
    description:
      "The 'house of Joseph' is treated as one tribe in Jacob's blessing (Gen 49:22-26) but divided into two in the territorial allotments through Joseph's sons Manasseh and Ephraim. The double inheritance reflects Jacob's adoption of his grandsons in Genesis 48.",
    scriptureReferences: [
      "Genesis 48",
      "Genesis 49:22-26",
      "Joshua 16",
      "Joshua 17",
      "Revelation 7:8",
    ],
    confidenceLevel: "explicit",
    notes:
      "Most lists of the twelve tribes substitute Manasseh and Ephraim for Joseph and Levi in territorial contexts, while Jacob's blessing names Joseph directly.",
  },
  {
    id: "manasseh",
    name: "Manasseh",
    type: "patriarchal",
    founderId: "manasseh",
    parentTribeId: "joseph",
    description:
      "Tribe descended from Joseph's elder son. Received a divided inheritance: a half-tribe east of the Jordan (the largest single allotment) and a half-tribe west, between Ephraim and Issachar.",
    scriptureReferences: [
      "Genesis 48:13-20",
      "Numbers 26:28-34",
      "Numbers 32:39-42",
      "Joshua 17",
      "1 Chronicles 5:23-26",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "ephraim",
    name: "Ephraim",
    type: "patriarchal",
    founderId: "ephraim",
    parentTribeId: "joseph",
    description:
      "Tribe descended from Joseph's younger son, who received Jacob's preferential blessing. The most populous and politically dominant northern tribe; in prophetic literature 'Ephraim' often stands for the entire northern kingdom.",
    scriptureReferences: [
      "Genesis 48:13-20",
      "Numbers 26:35-37",
      "Joshua 16",
      "Hosea 4:17",
      "Hosea 11:1-9",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "benjamin",
    name: "Benjamin",
    type: "patriarchal",
    founderId: "benjamin",
    parentTribeId: "israelites",
    description:
      "Tribe descended from Jacob's youngest son, born to Rachel near Bethlehem. Received a small but strategically vital territory between Judah and Ephraim, including Jerusalem on its border. Produced Israel's first king (Saul) and later the apostle Paul.",
    scriptureReferences: [
      "Genesis 49:27",
      "Numbers 26:38-41",
      "Joshua 18:11-28",
      "Judges 19-21",
      "1 Samuel 9-10",
      "Philippians 3:5",
    ],
    confidenceLevel: "explicit",
  },

  {
    id: "edomites",
    name: "Edomites",
    alternateNames: ["Sons of Esau", "Idumeans"],
    type: "nation",
    founderId: "esau",
    description:
      "Nation descended from Esau (Edom); settled in the mountainous region of Seir south of the Dead Sea. Persistent antagonists of Israel; later partially absorbed and Hellenized as the Idumeans (cf. Herod the Great).",
    scriptureReferences: [
      "Genesis 36",
      "Numbers 20:14-21",
      "1 Samuel 14:47",
      "2 Kings 8:20-22",
      "Obadiah",
      "Malachi 1:2-4",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "ishmaelites",
    name: "Ishmaelites",
    type: "nation",
    founderId: "ishmael",
    description:
      "Confederation of Arab peoples descended from Ishmael's twelve sons; nomadic dwellers of the northern Arabian peninsula. Frequently associated with the Midianites in scripture.",
    scriptureReferences: [
      "Genesis 25:12-18",
      "Genesis 37:25-28",
      "Judges 8:24",
      "1 Chronicles 1:28-31",
      "Psalm 83:6",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "moabites",
    name: "Moabites",
    type: "nation",
    founderId: "moab",
    description:
      "Nation descended from Lot's elder daughter; settled east of the Dead Sea on the Moabite plateau. Frequent enemies of Israel; Ruth the Moabitess became the great-grandmother of David.",
    scriptureReferences: [
      "Genesis 19:36-37",
      "Numbers 22-25",
      "Deuteronomy 2:9",
      "Judges 3:12-30",
      "Ruth",
      "1 Samuel 14:47",
      "Isaiah 15-16",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "ammonites",
    name: "Ammonites",
    alternateNames: ["Sons of Ammon", "Bene-Ammon"],
    type: "nation",
    founderId: "ben-ammi",
    description:
      "Nation descended from Lot's younger daughter; settled in Transjordan north of Moab around their capital Rabbah (modern Amman).",
    scriptureReferences: [
      "Genesis 19:36",
      "Genesis 19:38",
      "Deuteronomy 2:19",
      "Judges 11",
      "1 Samuel 11",
      "Nehemiah 2:10",
      "Nehemiah 13:1-3",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "midianites",
    name: "Midianites",
    type: "nation",
    founderId: "midian",
    description:
      "Nation descended from Abraham's son Midian by Keturah; nomadic traders and pastoralists of the northwestern Arabian peninsula. Moses lived among them with his father-in-law Jethro; later they oppressed Israel under Gideon.",
    scriptureReferences: [
      "Genesis 25:2",
      "Genesis 37:28-36",
      "Exodus 2:15-22",
      "Exodus 18",
      "Numbers 22",
      "Numbers 25",
      "Numbers 31",
      "Judges 6-8",
    ],
    confidenceLevel: "explicit",
  },
  {
    id: "amalekites",
    name: "Amalekites",
    type: "nation",
    founderId: "amalek",
    description:
      "Nation descended from Amalek son of Eliphaz, grandson of Esau. Perpetual archetypal enemies of Israel from Rephidim onward; Yahweh decreed total destruction (Deut 25:17-19) which Saul partially executed (1 Sam 15).",
    scriptureReferences: [
      "Genesis 36:12",
      "Exodus 17:8-16",
      "Numbers 24:20",
      "Deuteronomy 25:17-19",
      "1 Samuel 15",
      "1 Samuel 30",
      "Esther 3:1",
    ],
    confidenceLevel: "explicit",
    notes:
      "Haman the Agagite (Esther 3) is traditionally identified as a late descendant of the Amalekite royal house through Agag (1 Sam 15), making Mordecai's confrontation with him an echo of Saul-Amalek.",
  },
];
