// Server-only verse access. Reads the static corpus generated by
// `tools/ingest gen:verses`: book metadata from the generated manifest module,
// and per-book verse text via a variable dynamic import the bundler
// code-splits. No database, no runtime fs/cwd assumptions — works under both a
// static export and a serverless runtime.
//
// Do NOT import this from a Client Component: the dynamic import pulls in verse
// JSON that should only ever resolve on the server / at build time.

import { books } from "./books";
import { verseManifest } from "./verse-manifest";

/** A book's verses: chapter number (as string key) -> [verseNumber, text][]. */
export type VerseFile = Record<string, Array<[number, string]>>;

export interface ChapterVerse {
  verse: number;
  text: string;
}

export interface VerseLocation extends ChapterVerse {
  bookCode: string;
  chapter: number;
}

const { translations } = verseManifest;

/** Canonical book codes in canonical order (from the static book metadata). */
const BOOK_ORDER: string[] = [...books].sort((a, b) => a.order - b.order).map((b) => b.id);

export function getAvailableTranslationCodes(): string[] {
  return Object.keys(translations);
}

export function hasTranslation(code: string): boolean {
  return code in translations;
}

/** Translation codes that contain the given book, in manifest order. */
export function getTranslationCodesForBook(bookCode: string): string[] {
  return getAvailableTranslationCodes().filter((code) =>
    Boolean(translations[code]?.books[bookCode]),
  );
}

/**
 * Highest chapter number present for a book. With a translation, the count for
 * that translation; otherwise the max across every translation that has it.
 */
export function getMaxChapter(bookCode: string, translationCode?: string): number {
  if (translationCode) {
    return translations[translationCode]?.books[bookCode]?.chapters ?? 0;
  }
  let max = 0;
  for (const code of getAvailableTranslationCodes()) {
    const chapters = translations[code]?.books[bookCode]?.chapters ?? 0;
    if (chapters > max) max = chapters;
  }
  return max;
}

/** Total verse count per translation code (for the homepage / source stats). */
export function getTotalVerseCounts(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const [code, entry] of Object.entries(translations)) {
    counts[code] = entry.totalVerses;
  }
  return counts;
}

// Cache each loaded book file for the lifetime of the process (build or
// serverless instance), keyed by "<TR>/<book>".
const fileCache = new Map<string, Promise<VerseFile>>();

function loadBookFile(translationCode: string, bookCode: string): Promise<VerseFile> | null {
  if (!translations[translationCode]?.books[bookCode]) return null;
  const key = `${translationCode}/${bookCode}`;
  let cached = fileCache.get(key);
  if (!cached) {
    // Variable specifier: the bundler builds one lazy context over
    // ../data/verses/**/*.json; tsc leaves the path unresolved (stays light).
    cached = import(`../data/verses/${translationCode}/${bookCode}.json`).then(
      (m) => (m.default ?? m) as VerseFile,
    );
    fileCache.set(key, cached);
  }
  return cached;
}

export async function getChapterVerses(
  translationCode: string,
  bookCode: string,
  chapter: number,
): Promise<ChapterVerse[]> {
  const filePromise = loadBookFile(translationCode, bookCode);
  if (!filePromise) return [];
  const file = await filePromise;
  const rows = file[String(chapter)];
  if (!rows) return [];
  return rows.map(([verse, text]) => ({ verse, text }));
}

// --- Search -----------------------------------------------------------------
// Simple linear substring scan, preserving the previous DB behavior
// (`contains`, case-insensitive). Loaded verses are cached per translation.
// A dedicated search index is a later-phase optimization.

const translationVersesCache = new Map<string, Promise<VerseLocation[]>>();

function loadTranslationVerses(translationCode: string): Promise<VerseLocation[]> {
  let cached = translationVersesCache.get(translationCode);
  if (cached) return cached;

  const build = (async (): Promise<VerseLocation[]> => {
    const out: VerseLocation[] = [];
    const entry = translations[translationCode];
    if (!entry) return out;
    for (const bookCode of BOOK_ORDER) {
      if (!entry.books[bookCode]) continue;
      const filePromise = loadBookFile(translationCode, bookCode);
      if (!filePromise) continue;
      const file = await filePromise;
      const chapterNums = Object.keys(file)
        .map(Number)
        .sort((a, b) => a - b);
      for (const chapter of chapterNums) {
        for (const [verse, text] of file[String(chapter)]!) {
          out.push({ bookCode, chapter, verse, text });
        }
      }
    }
    return out;
  })();

  translationVersesCache.set(translationCode, build);
  return build;
}

export async function searchTranslationVerses(
  translationCode: string,
  query: string,
  limit: number,
): Promise<{ hits: VerseLocation[]; total: number }> {
  const needle = query.trim().toLowerCase();
  if (needle.length < 2) return { hits: [], total: 0 };

  const all = await loadTranslationVerses(translationCode);
  const hits: VerseLocation[] = [];
  let total = 0;
  for (const location of all) {
    if (location.text.toLowerCase().includes(needle)) {
      total += 1;
      if (hits.length < limit) hits.push(location);
    }
  }
  return { hits, total };
}
